### ISSUE TITLE
Mouse Pointer size is not consistent

### ISSUE THREAD

**Issue by finetuned89** [elementary/gala#558] opened 2019-06-16 18:50 UTC
In Juno on a 1x monitor (2560x1440 at 27 inches, display setting to LoDPI), the mouse pointer is sometimes the correct size, and sometimes too large. See this, hovering in and out of different parts of a Files window and the desktop:

![mousepointer](https://user-images.githubusercontent.com/12174852/59568233-59e27780-9078-11e9-8d75-eb07f6b146fd.gif)

**Comment by peteruithoven** [comment] 2019-06-16 20:04
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/115

**Closed by peteruithoven** 2019-06-16 20:04 UTC

**Comment by finetuned89** [comment] 2019-06-17 04:38
Issue #115 is closed too, yet the problem remains. What is the recommended thing for me to do?

**Comment by peteruithoven** [comment] 2019-06-17 06:17
It looks like it's closed because of a fix in the Greeter. This Greeter version hasn't been released yet so... you'll have to wait for that or compile the greeter itself. 
(Issues are closed when issues are fixed in code, not when the code with fix is released to the public)

**Comment by finetuned89** [comment] 2019-06-18 19:58
Shame that the releases are so infrequent. The problem also goes away when enabling Auto Login, possibly bypassing the Greeter that is causing the problem.
