### ISSUE TITLE
While holding Shift during Alt Shift Tab, windows are not cycled as expected.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/gala#227] opened 2018-04-19 13:59 UTC
### Base Behaviour

While holding <kbd>Alt</kbd> and repeatedly pressing <kbd>Tab</kbd> the system cycles through windows most recent to least recent.

### Expected Behaviour

While holding <kbd>Alt</kbd> and <kbd>Shift</kbd> and repeatedly pressing <kbd>Tab</kbd>, I expect it to cycle through windows in the opposite direction.

### Current Behaviour

While holding <kbd>Alt</kbd> and <kbd>Shift</kbd> and repeatedly pressing <kbd>Tab</kbd>, it **cycles through windows once in the opposite direction, and then back in the direction thereafter as if the <kbd>Shift</kbd> key is no longer being held**. This makes it impossible to go back two or more windows without leaving the window switcher (which would then change the order the windows are in, as there is a new most recent window).

**Comment by cassidyjames** [comment] 2018-04-21 05:30
@lewisgoddard is this a duplicate of #18? Or is this something different?

**Comment by lewisgoddard** [comment] 2018-04-21 14:04
I'm not sure it is, because it works once for switching back a window, but not more than that. That does seem like it would be a problem with window switching, but that conflict certainly complicates things.

**Comment by marbetschar** [comment] 2021-11-30 08:10
Alt + Shift + Tab to cycle backwards does not work on my end using the new window switcher introduced this month (Nov 2021). I simply installed the latest updates to get the new window switcher - no fresh install of elementary OS.

**Comment by peteruithoven** [comment] 2023-04-15 09:46
I'm quite sure the window switcher has changed significantly in the mean time and I can't reproduce this issue anymore. 

@marbetschar if Alt + Shift + Tab simple doesn't work, you might want to check out: https://github.com/elementary/default-settings/issues/4

**Closed by peteruithoven** 2023-04-15 09:46 UTC
Labels: Status: Incomplete
