### ISSUE TITLE
Tiling to the side stops working

### ISSUE THREAD

**Issue by GammaGames** [elementary/gala#345] opened 2018-09-25 02:45 UTC
Rarely when putting the window against the edge of my desktop to tile it the window gets stuck in this strange limbo stage, where the window it isn't properly moved to the tiled position but can still interact with it as if it was.

![plumpfastbarnswallow-size_restricted](https://user-images.githubusercontent.com/7832163/45989849-9aa5e680-c03a-11e8-88ce-0c64e3fffb11.gif)

This is in Juno-beta-2. Are there any logs I can tail to help find the cause, since it's difficult to reproduce?

**Comment by cassidyjames** [comment] 2018-09-25 05:57
I believe this is a Google Chrome/Chromium bug as I've not seen it with other apps.

**Comment by cassidyjames** [comment] 2018-09-25 05:58
I think this is a duplicate of #306

**Closed** 2018-09-25 05:58 UTC
