### ISSUE TITLE
Feature Request: Grid based Tiling

### ISSUE THREAD

**Issue by rolyataylor2** [elementary/gala#212] opened 2018-03-23 22:37 UTC
A nice feature would be to be able to set up a grid in the system preferences that defines where windows snap to on the edges. This would be similar to the way that OSX allows split full screen. I searched around for how to set this up in linux, but I couldn't find it. 

I have been searching the source code and noticed that tiling is still in the works so I figure this is a good time to bring it up. 

> Example of a nice tile for taking notes 
>![screenshot from 2018-03-23 15 25 30](https://user-images.githubusercontent.com/6402800/37855803-77e84318-2eae-11e8-9254-26ec8a8db9ba.jpeg)

For GUI purposes maybe when you are dragging a window you could make a floating target image for each grid square and if you drop the window onto it then it will tile the window into the area defined.

**Comment by peteruithoven** [comment] 2018-03-24 10:04
What I've learned looking into quarter tiling (#105) is that this is probably handled by another library: [Mutter](https://gitlab.gnome.org/GNOME/mutter).
I'd suggest checking their new issue queue: https://gitlab.gnome.org/GNOME/mutter/issues
I hope they migrated all their old issues from bugzilla, since [Gnome and related projects are migrating](https://mail.gnome.org/archives/desktop-devel-list/2018-March/msg00023.html).

**Comment by danrabbit** [comment] 2018-08-09 16:10
Closing this as a duplicate of #105

**Closed by danrabbit** 2018-08-09 16:10 UTC
