### ISSUE TITLE
Gala dependency libmutter-cogl-path

### ISSUE THREAD

**Issue by suhijo** [elementary/gala#865] opened 2020-07-02 15:02 UTC
EHLO 

I am trying to compile Gala in my Mageia Linux, but it request me a dependency libmutter-cogl-path which is not available in mutter 3.37.2, latest release at least. What should I do?

**Comment by decathorpe** [comment] 2020-07-02 19:02
The last release (and git master) of gala do not yet support mutter >= 3.37, as it bumped library name (again :frowning:) and changed APIs (again :frowning_face:).

You should be able to build it against stable mutter releases between 3.28 and 3.26. For work-in-progress 3.37+ support, there's an incomplete PR:  https://github.com/elementary/gala/pull/854

You can look the official fedora package, it should be similar to what you need for Mageia (however, it does not compile on rawhide right now, either): https://src.fedoraproject.org/rpms/gala

**Comment by suhijo** [comment] 2020-07-02 22:47
Yikes... well... I have done it, I downloaded 3.36 and have problems compiling gala stil, the result is as follows:
`
ninja: Entering directory `build'
[6/78] Compiling Vala source ../lib/ActivatableComponent.vala ../lib/Constants.vala ../lib/Plugin.vala ../lib/Utils.vala ../lib/WindowIcon.vala ../lib/WindowManager.vala
../lib/Plugin.vala:89.9-89.38: warning: Type `Meta.Rectangle[]' can not be used for a GLib.Object property
        public Meta.Rectangle[] region { get; private set; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/Plugin.vala:96.9-96.49: warning: Type `Meta.Rectangle[]?' can not be used for a GLib.Object property
        protected Meta.Rectangle[]? custom_region {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../lib/WindowManager.vala:67.9-67.50: warning: Type `Gala.KeybindingFilter?' can not be used for a GLib.Object property
        public KeybindingFilter? keybinding_filter { get; owned set; default = () => true; }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 3 warning(s)
[16/78] Compiling Vala source ../src/DBus.vala ../src/DBusAccelerator.vala ../src/DockThem... ../src/Widgets/WorkspaceClone.vala ../src/Widgets/WorkspaceInsertThumb.vala lib/gala.vapi
FAILED: src/25a6634@@gala@exe/DBus.c src/25a6634@@gala@exe/DBusAccelerator.c src/25a6634@@gala@exe/DockThemeManager.c src/25a6634@@gala@exe/DragDropAction.c src/25a6634@@gala@exe/InternalUtils.c src/25a6634@@gala@exe/KeyboardManager.c src/25a6634@@gala@exe/NotificationStack.c src/25a6634@@gala@exe/Main.c src/25a6634@@gala@exe/MediaFeedback.c src/25a6634@@gala@exe/PluginManager.c src/25a6634@@gala@exe/ScreenSaverManager.c src/25a6634@@gala@exe/ScreenshotManager.c src/25a6634@@gala@exe/SessionManager.c src/25a6634@@gala@exe/Settings.c src/25a6634@@gala@exe/ShadowEffect.c src/25a6634@@gala@exe/WindowListener.c src/25a6634@@gala@exe/WindowManager.c src/25a6634@@gala@exe/WorkspaceManager.c src/25a6634@@gala@exe/Background/Animation.c src/25a6634@@gala@exe/Background/Background.c src/25a6634@@gala@exe/Background/BackgroundCache.c src/25a6634@@gala@exe/Background/BackgroundContainer.c src/25a6634@@gala@exe/Background/BackgroundManager.c src/25a6634@@gala@exe/Background/BackgroundSource.c src/25a6634@@gala@exe/Background/SystemBackground.c src/25a6634@@gala@exe/Widgets/IconGroup.c src/25a6634@@gala@exe/Widgets/IconGroupContainer.c src/25a6634@@gala@exe/Widgets/MonitorClone.c src/25a6634@@gala@exe/Widgets/MultitaskingView.c src/25a6634@@gala@exe/Widgets/PixelPicker.c src/25a6634@@gala@exe/Widgets/SafeWindowClone.c src/25a6634@@gala@exe/Widgets/ScreenShield.c src/25a6634@@gala@exe/Widgets/SelectionArea.c src/25a6634@@gala@exe/Widgets/WindowClone.c src/25a6634@@gala@exe/Widgets/WindowCloneContainer.c src/25a6634@@gala@exe/Widgets/WindowIconActor.c src/25a6634@@gala@exe/Widgets/WindowOverview.c src/25a6634@@gala@exe/Widgets/WindowSwitcher.c src/25a6634@@gala@exe/Widgets/WorkspaceClone.c src/25a6634@@gala@exe/Widgets/WorkspaceInsertThumb.c 
valac -C --debug --debug --target-glib=2.44 --hide-internal --enable-deprecated --vapidir=/usr/src/gala/vapi --define HAS_MUTTER330 --define HAS_MUTTER332 --define HAS_MUTTER334 --define HAS_MUTTER336 /usr/src/gala/vapi/config.vapi --pkg gnome-desktop-3.0 --pkg granite --pkg mutter-clutter-6 --pkg mutter-cogl-path-6 --pkg mutter-cogl-pango-6 --pkg mutter-cogl-6 --pkg libmutter-6 --pkg libbamf3 --pkg plank --pkg gdk-x11-3.0 --pkg gtk+-3.0 --pkg gee-0.8 --pkg gmodule-2.0 --pkg gio-2.0 --pkg gobject-2.0 --target-glib ' 2.44.0' --pkg glib-2.0 --color=always --directory src/25a6634@@gala@exe --basedir ../src ../src/DBus.vala ../src/DBusAccelerator.vala ../src/DockThemeManager.vala ../src/DragDropAction.vala ../src/InternalUtils.vala ../src/KeyboardManager.vala ../src/NotificationStack.vala ../src/Main.vala ../src/MediaFeedback.vala ../src/PluginManager.vala ../src/ScreenSaverManager.vala ../src/ScreenshotManager.vala ../src/SessionManager.vala ../src/Settings.vala ../src/ShadowEffect.vala ../src/WindowListener.vala ../src/WindowManager.vala ../src/WorkspaceManager.vala ../src/Background/Animation.vala ../src/Background/Background.vala ../src/Background/BackgroundCache.vala ../src/Background/BackgroundContainer.vala ../src/Background/BackgroundManager.vala ../src/Background/BackgroundSource.vala ../src/Background/SystemBackground.vala ../src/Widgets/IconGroup.vala ../src/Widgets/IconGroupContainer.vala ../src/Widgets/MonitorClone.vala ../src/Widgets/MultitaskingView.vala ../src/Widgets/PixelPicker.vala ../src/Widgets/SafeWindowClone.vala ../src/Widgets/ScreenShield.vala ../src/Widgets/SelectionArea.vala ../src/Widgets/WindowClone.vala ../src/Widgets/WindowCloneContainer.vala ../src/Widgets/WindowIconActor.vala ../src/Widgets/WindowOverview.vala ../src/Widgets/WindowSwitcher.vala ../src/Widgets/WorkspaceClone.vala ../src/Widgets/WorkspaceInsertThumb.vala lib/gala.vapi
../src/Background/Background.vala:186.33-186.36: warning: Argument 1: Cannot pass null to non-null parameter type
                        finish (null);
                                ^^^^
../src/Background/Background.vala:192.37-192.40: warning: Argument 1: Cannot pass null to non-null parameter type
                            finish (null);
                                    ^^^^
../src/Background/BackgroundSource.vala:123.17-123.34: error: The name `changed' does not exist in the context of `Gee.Map.Entry<int,Gala.Background>?' (gee-0.8)
                background.changed.disconnect (background_changed);
                ^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundSource.vala:124.17-124.34: error: The name `destroy' does not exist in the context of `Gee.Map.Entry<int,Gala.Background>?' (gee-0.8)
                background.destroy ();
                ^^^^^^^^^^^^^^^^^^
../src/Background/BackgroundManager.vala:128.9-128.28: warning: Gala.BackgroundManager.set_size hides inherited method `Clutter.Actor.set_size'. Use the `new' keyword if hiding was intentional
        public void set_size (float width, float height) {
        ^^^^^^^^^^^^^^^^^^^^
../src/ShadowEffect.vala:121.13-122.59: warning: unhandled error `GLib.Error'
../src/Widgets/IconGroup.vala:543.17-543.27: warning: `null' incompatible with return type `Clutter.Actor'
                return null;
                ^^^^^^^^^^^
../src/DBus.vala:89.17-89.68: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                (wm.background_group as BackgroundContainer).changed.connect (() => background_changed ());
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 6 warning(s)
[17/78] Compiling Vala source ../plugins/maskcorners/Main.vala ../plugins/maskcorners/Settings.vala lib/gala.vapi
ninja: build stopped: subcommand failed.

`
the command  I used to compiles are: meson build --prefix=/usr and then ninja inside build drectory

**Comment by decathorpe** [comment] 2020-07-03 14:43
That's weird, the latest gala (both release and git master) compiles fine against mutter 3.36.x on fedora 32.

What's your exact environment? Which version of Mageia? How did you "download" mutter 3.36 and why did you have 3.37.2 before?

**Comment by suhijo** [comment] 2020-07-04 03:13
I am using Mageia Cauldron, and they already have 3.37.2 but I uninstalled and installed 3.36.3.

**Comment by Lucidiot** [comment] 2020-07-04 13:29
I have the same errors on Arch, while trying to install Pantheon by following [this wiki page](https://wiki.archlinux.org/index.php/Pantheon) with mutter 3.36.3. It seems the latest CI build on master failed in the same way: https://github.com/elementary/gala/runs/836618728#step:5:108

**Comment by suhijo** [comment] 2020-07-06 03:46
Yeah that is the same error I have. What could be the problem?

**Comment by Lucidiot** [comment] 2020-07-16 21:53
I no longer have this error since #869 has been merged, so this was probably unrelated to mutter.

**Comment by davidmhewitt** [comment] 2020-10-20 12:23
I'm going to close this issue as it sounds like it was resolved and/or was caused by incompatible mutter versions. Feel free to re-open or open a new issue if you're still experiencing issues.

**Closed by davidmhewitt** 2020-10-20 12:23 UTC
