### ISSUE TITLE
Font smoothing and HiDPI

### ISSUE THREAD

**Issue by TeamPuzel** [elementary/gala#1492] opened 2022-11-03 20:06 UTC
### Problem

Hello!
I think it would be nice to have a font smoothing toggle in the general/display settings :)
It's turned on because text looks noticeably less sharp than on my second, macOS MacBook, with font smoothing disabled. (both have identically sized 2560x1600 displays)

I really miss the toggle macOS used to have before Big Sur and I wish elementary also had one :/

Either way, font smoothing looks horrible on a HiDPI display, especially after getting used to the sharpness of more accurate type; at the same time, without font smoothing text is unreadable on low resolution displays. Thankfully such displays are becoming less common, but they obviously still need support.

I'm not sure about Gtk but on macOS this also negatively affects the sharpness and accuracy of UI symbols.

### Proposal

I think a toggle would be enough, but I also think the default for HiDPI should be to turn off font smoothing (if rendering HiDPI text correctly is even possible on X11).

Detecting this for each display would be cool but even apple doesn't do it so it's probably not that easy.

By the way, I'm not sure what Apple's "font smoothing" refers to 100%, but from testing different font configs disabling hinting made text similar, I assume font smoothing means hinting - disabling anti aliasing makes text pixelated so that's not it.
even so, it's still not quite as sharp, but an improvement nonetheless :)

I don't think casual users will understand such a toggle so it might be a good idea to invest some time into an automated solution.

### Prior Art (Optional)

- macOS Catalina and earlier had a checkbox in System Preferences that disabled font smoothing globally; it's still part of userdefaults but they removed the toggle (likely to compensate for newer MacBooks using uneven scaling)

- iOS doesn't seem to use font smoothing at all since all devices it supports have "retina" displays

- Not sure about other operating systems

**Comment by danirabbit** [comment] 2022-11-03 20:13
Hey thanks for your report! This is a duplicate of https://github.com/elementary/switchboard-plug-pantheon-shell/issues/288 which is in progress :)

**Closed** 2022-11-03 20:13 UTC
