### ISSUE TITLE
Maximized window + fullscreen in secondary monitor breaks application

### ISSUE THREAD

**Issue by inad9300** [elementary/gala#542] opened 2019-05-28 17:32 UTC
If after opening (e.g.) Firefox, maximized, in a second monitory I try to play YouTube or Netflix in full screen mode, Firefox is completely unable to handle this and *breaks* (sounds keep playing, but the video cannot be properly rendered at all, showing a collage of frozen nonsense images). I have been able to consistently reproduce the same issue with other browsers too.

The described sequence works just find on the primary monitory, just not when the windows are on the secondary one. Also, full screen works just fine in the secondary monitory when the window is not initially maximized. I'm being redundant here, but my point is to clarify that only the very combination of settings that I described triggers the issue for me.

**Comment by peteruithoven** [comment] 2019-05-31 18:34
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/404.

**Closed by peteruithoven** 2019-05-31 18:34 UTC
Labels: Status: Duplicate
