### ISSUE TITLE
Windows stuttering when tiled on left or right

### ISSUE THREAD

**Issue by vertpierre** [elementary/gala#1144] opened 2021-05-20 18:31 UTC
## What Happened

The window create a ghost window which is stuttering/lagging when it's tiled on left or right using SUPER + left/right arrow (the ghost window appear between the window and the direction where it is going to be tiled).
To better understand see the link below (the video show the main window lagging, but it doesn't append on my desktop):
https://user-images.githubusercontent.com/74794864/119029417-e2769a80-b9a8-11eb-92a4-da52be2f9eb7.mp4

## Expected Behavior

The window should be tiled on left or right, without creating a ghost window which is stuttering in the direction of the tiling. 

## Steps to Reproduce

1. Tile the window on the left or the right.
2. Repeat the action left/right to better see the bug.

## Platform Information

Elementary OS 6 - Beta (latest release)
Intel® Pentium® Silver N5000 CPU @ 1.10GHz
Intel® UHD Graphics 605 (Geminilake)

**Comment by lenemter** [comment] 2024-04-27 09:56
Closing because I cannot reproduce the issue in OS 7.1

**Closed by lenemter** 2024-04-27 09:56 UTC
