### ISSUE TITLE
Icon Multitasking

### ISSUE THREAD

**Issue by bakamedi** [elementary/gala#372] opened 2018-10-19 15:53 UTC
the icon don't show

**Comment by rscm** [comment] 2018-10-19 16:58
same here

`$ cat /etc/os-release 
NAME="elementary OS"
VERSION="5.0 Juno"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.0 Juno"
VERSION_ID="5.0"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/appcenter/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=juno
UBUNTU_CODENAME=juno`

could you point out the location to manually edit it? thanks

**Comment by peteruithoven** [comment] 2018-10-19 18:50
Thanks for the report! This is actually a duplicate of https://github.com/elementary/gala/issues/358

**Closed by peteruithoven** 2018-10-19 18:50 UTC
