### ISSUE TITLE
Screen freezes when mouse cursor is not moving on Juno

### ISSUE THREAD

**Issue by leonidasv** [elementary/gala#368] opened 2018-10-18 19:31 UTC
I'm using Juno since beta 2 and even with the rc-1, I'm experiencing a bug that freaks me out.

If I start playing a video for example, be in the browser or the Videos app, if I stop using the mouse and lay it resting, after 5~30 seconds, the whole screen freezes. The audio continues to play, tho, but the picture is kept frozen for an undefined amount of time (from 15 seconds to minutes) if I don't move the mouse again.

I can only be sure a video/UI animation will play correctly if I keep moving the cursor around the whole time. The moment I stop moving it, I can expect the picture to freeze in the next seconds. Happens with almost every application.

I wish my explanation went clear. This is very annoying as I can't enjoy watching a video _passively_ on my system.

For instance, I'm running a Intel Core 7th gen processor, my monitor being connected to a HD Graphics 620 (rev a2) card, using the default drivers provided by the system for both. I also note that I've never experienced this issue with Gnome on both X and Wayland on Ubuntu 18.04.

This leads me to believe the bug is trapped somewhere in the Gala compositor, but I lack the technical expertise to debug/stacktrace it. If someone could help me figuring out what's causing it (and, more important, fixing it), I will be glad.

**Comment by leonidasv** [comment] 2018-10-18 19:42
I think I found a related bug on Mutter: https://gitlab.gnome.org/GNOME/mutter/merge_requests/51

My system has 2 GPUs, too. But I didn't install the NVIDIA drivers. I'm using only the integrated one for now, as the display is connected directly to it. 

I will try disabling the dedicated graphics card on the BIOS to see if this solves the issue. If that's the case, the merge request from Gnome can help elucidating it in Gala/Pantheon too.

**Comment by leonidasv** [comment] 2018-10-18 20:01
Disabling it (via driver blacklist) makes the freezing bug **even worse**. Now it happens just 1~5 seconds after the mouse/keyboard is left resting.

This should be corrected as soon as possible, many users may be facing this.

**Comment by Djaler** [comment] 2018-10-18 20:14
Duplicate of https://github.com/elementary/os/issues/121

**Closed** 2018-10-19 21:48 UTC
Labels: Status: Duplicate
