### ISSUE TITLE
Double child window in applications

### ISSUE THREAD

**Issue by lsrzj** [elementary/gala#299] opened 2018-07-16 18:01 UTC
When opening child windows in applications it's appearing with double windows. So it has two title bars and a wider window containing the application's child window itself as in the attached image of this report. I'm using Loki release.

![captura de tela de 2018-07-12 10-56-27](https://user-images.githubusercontent.com/18689770/42774766-f62be0e0-8908-11e8-8602-eeaae03db3b0.png)

**Comment by rsolvang** [comment] 2018-10-29 14:37
I have the same problem with DisplayCal:
![skjermdump fra 2018-10-29 15-32-05](https://user-images.githubusercontent.com/1956027/47656828-31147d00-db90-11e8-8ff3-80b7dcd67463.png)

**Comment by Jiab77** [comment] 2018-11-03 19:52
Got exactly the same issue on the latest #ElementaryOS #Juno. I have it with `BOINC Manager` app.
The same issue was also existing in the Beta versions of Juno

**Comment by cassidyjames** [comment] 2018-11-12 16:48
This appears to be a duplicate of #244

**Closed by cassidyjames** 2018-11-12 16:48 UTC
