### ISSUE TITLE
No wingpanel and plank after Ctrl+Alt+Backspace

### ISSUE THREAD

**Issue by Djaler** [elementary/gala#325] opened 2018-08-29 19:59 UTC
Steps to reproduce:
1. Login
2. Press Ctrl+Alt+Backspace
3. Login again

Session is loaded but there are no plank and wingpanel

**Comment by lenemter** [comment] 2023-08-27 08:59
Closing because I cannot reproduce the issue. Please reply here if you still encounter it.

**Closed by lenemter** 2023-08-27 08:59 UTC
