### ISSUE TITLE
Close button on PiP doesn't scale for HiDPI

### ISSUE THREAD

**Issue by danrabbit** [elementary/gala#280] opened 2018-06-26 21:31 UTC
![screenshot from 2018-06-26 14 30 10 2x](https://user-images.githubusercontent.com/7277719/41940426-8423d798-794d-11e8-8c66-9b977d413487.png)

**Comment by JosephMcc** [comment] 2018-07-11 10:38
@donadigo The fix for the size if the button is actually pretty easy. You fetch the properly sized button with the call to create_close_button() and then on the very next line resize it to the unscaled BUTTON_SIZE: https://github.com/elementary/gala/blob/master/plugins/pip/PopupWindow.vala#L130

Simply removing that line fixes the the button sizing. I'm seeing other issues though that might be HiDPI specific. When you first create the PIP window and then attempt to resize it, the resize buttons changes position. After that your button and the actual grab area are no longer aligned. This seems to be caused by the uses of BUTTON_SIZE in quite a few other areas where the scale probably needs to be taken into account. I was poking about in here but don't know this code very well ;)

**Comment by donadigo** [comment] 2018-07-11 12:04
@JosephMcc oh, that's right, I haven't noticed it gets downscaled. If you want you could do a PR with this one line change or I can do one so we can get the fix merged to master. I'm not really aware of other issues since I don't have a HiDPI display and can't reliably test that. Thank you!

**Comment by JosephMcc** [comment] 2018-07-11 17:03
PR submitted for the button size. I'll try to dig into the other issues.

Sorry for the spammy references. Was committing this too early in the morning and had to fix the wording in the commit message :)

**Closed** 2018-07-15 00:00 UTC
Labels: Status: In Progress
