### ISSUE TITLE
Extra empty workspace is created at startup

### ISSUE THREAD

**Issue by yerbestpal** [elementary/gala#861] opened 2020-06-26 13:12 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
There is an extra empty workspace created on startup. This should not be possible; standard workspace behaviour dictates that empty only one empty workspace can exist at a time, and also, there is no reason it should be created in the first place.

### To Reproduce
1. Login.
2. Access the multitasking view.

### Expected behavior
The current workspace is shown with no open applications visible. 

### Screenshots or screen recordings
I had to take a photo with my phone because it is not possible to take screenshots whilst in multitasking view.
![IMG_20200626_133307](https://user-images.githubusercontent.com/15250241/85860542-dee98c00-b7b6-11ea-9565-65ccf873d02d.jpg)

## Platform Information
![Screenshot from 2020-06-26 14-11-29](https://user-images.githubusercontent.com/15250241/85860628-00e30e80-b7b7-11ea-81c8-c6d127aa8b04.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by Blast-City** [comment] 2020-09-17 06:58
Hi.

Please close this issue. It's a duplicate of #506 

Thanks.

**Closed** 2020-09-20 16:11 UTC
