### ISSUE TITLE
Multimedia keys can't be assigned as shortcuts

### ISSUE THREAD

**Issue by dcervenkov** [elementary/gala#1358] opened 2022-01-05 18:35 UTC
### What Happened?

Multimedia keys can't be assigned as shortcuts. However, Shift + Multimedia Keys can.

### Steps to Reproduce

1. Go to System Settings > Keyboard > Shortcuts
2. Create a custom shortcut
3. Try to assign, e.g., the calculator key (nothing happens)
4. Try to assign, e.g., shift + calculator key (shift + calculator key is assigned)

### Expected Behavior

Multimedia keys are assignable with and without shift (or other modifiers).

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Nvidia 495

**Comment by lenemter** [comment] 2023-10-26 03:43
Duplicate of https://github.com/elementary/switchboard-plug-keyboard/issues/434

**Closed by lenemter** 2023-10-26 03:43 UTC
