### ISSUE TITLE
(elementaryos v8 early access) Wingpanel in middle of the screen when running installer screen

### ISSUE THREAD

**Issue by megatux** [elementary/gala#2052] opened 2024-09-15 19:52 UTC
### What Happened?

When using two monitors setup the wingpanel position goes wrong, see attached photo.
Also the installer app width goes crazy wide.

Not use if this is a Gala or Wingpanel issue.
I can attach more photos if you need it

### Steps to Reproduce

connect external monitor
play a bit with installer and screens and windows

### Expected Behavior

Winpanel in top of primary display

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

internal laptop display 1080x768
external LG monitor 1080x768

![install-dual-monit](https://github.com/user-attachments/assets/fb38c0d6-8a67-4ef6-a5bf-701877ed13ec)

**Comment by lenemter** [comment] 2024-09-15 19:56
Thank you for your report. This is a duplicate of https://github.com/elementary/greeter/issues/748 and it was recently fixed in https://github.com/elementary/greeter/pull/749

**Closed by lenemter** 2024-09-15 19:56 UTC
