### ISSUE TITLE
Odin: Quick glimpse at unlocked Desktop possible after resume

### ISSUE THREAD

**Issue by marbetschar** [elementary/gala#988] opened 2020-10-30 08:23 UTC
## What Happened

When my laptop suspends the screen goes dark. So far everythings fine. But when I wake it up again, I can get a quick glimpse at the unlocked Desktop before the Greeter is shown.

## Expected Behavior

The only thing visible after resume should be the Greeter, so a user must login before they can see anything of the Desktop.

## Steps to Reproduce

1. Boot and login as usual
2. Send the laptop to sleep
3. Resume the laptop and you'll get a quick glimpse at the Desktop at the state it had before hibernation
4. The Greeter is shown and hides the Desktop

## Platform Information

* Using elementary Odin. But if I recall correctly this was also a thing on Hera.

**Comment by vjr** [comment] 2021-03-29 13:25
Yup , split second desktop is visible when resume... this is on a laptop with intel core i5 1135g7 cpu with its integrated iris xe igpu.

**Comment by jeremypw** [comment] 2021-04-25 09:57
This happens for me on Odin daily, when resuming from suspend but *not* when resuming after locking the screen with keyboard or when resuming after suspending from the greeter screen. The desktop shows for about 1 second.  Maybe should lock the screen first then suspend??

**Comment by hanaral** [comment] 2021-04-25 13:03
> This happens for me on Odin daily, when resuming from suspend but _not_ when resuming after locking the screen with keyboard or when resuming after suspending from the greeter screen. The desktop shows for about 1 second. Maybe should lock the screen first then suspend??

I, including some others have suggested making this default beaviour, but it seems to be a part of the 'late  locking' design which has the sole purpose (afaik) to allow music to continue playing. I personally don't think it's worth the risk of the desktop compositor being at the surface after being 'locked', even if the delay is minimised. If lockscreen media is a need, there should be an actual API devs can use rather than a workaround.

**Comment by jeremypw** [comment] 2021-04-25 14:39
>  it seems to be a part of the 'late locking' design which has the sole purpose (afaik) to allow music to continue playing.

For me, "Suspend" implies the computer stops everything it is doing - including playing music.  I can see the point of continuing to play while the screen is locked though.

I don't know enough about the Gala code base atm, but I want to learn more. There are an awful lot of outstanding PRs awaiting review for a start.

**Comment by lenemter** [comment] 2024-12-12 13:43
Duplicate of https://github.com/elementary/greeter/issues/397

**Closed by lenemter** 2024-12-12 13:43 UTC
