### ISSUE TITLE
Conky wiped out by Workspace Switching

### ISSUE THREAD

**Issue by reece146** [elementary/gala#773] opened 2020-04-18 18:40 UTC
Not sure where to post and this is likely a fairly esoteric "bug" or change conflict... There's probably not a lot of elementary users with conky configured.

It seems since the upgrade to 5.1.3 that when switching workspaces the conky configuration running on the X root window is wiped out consistently.

My conky config is started via a Startup script in Settings -> Applications. It's been like that for a year, possibly longer. It is basically a bash src of all the *.conkyrc files in a directory (conky -c file1.conkyrc; conky -c file2.conkyrc; etc.)

None of these configs do anything particularly exotic.

Super+right to the next workspace clears conky from the screen on the new workspace (it used to remain).

Super+left to the previous workspace returns to a blank X root window.

The conky instances remain running in the proc stack.

I've included two screen shots that show before and after workspace navigation.

I don't know if this is a similar issue as reported in #272 : PiP: fast workspace switching causes the PiP window to hide.

![Screenshot from 2020-04-18 14-35-43](https://user-images.githubusercontent.com/6394378/79662257-87a9b880-8182-11ea-858f-3443902991be.png)

![Screenshot from 2020-04-18 14-59-34](https://user-images.githubusercontent.com/6394378/79668789-4bc42280-8185-11ea-9142-3bfb8697ec9c.png)

![Screenshot from 2020-04-18 14-35-53](https://user-images.githubusercontent.com/6394378/79664526-2d5d2780-8183-11ea-9108-420c1fc7db0c.png)

**Comment by reece146** [comment] 2020-04-18 18:48
Also, if I 'killall conky' and restart the script the conky instances are restored without issue.

**Comment by alexeyten** [comment] 2020-04-18 19:11
Maybe related to my issue #764 
There is a comment that all windows with flag “show on all screens” are affected

**Comment by cassidyjames** [comment] 2020-04-30 17:21
I can confirm that windows that are always visible on workspaces are hidden and not re-shown when changing workspaces, and that windows on secondary displays are considered "Always on Visible Workspace" internally by Mutter. So this is indeed a duplicate of #764.

**Closed by cassidyjames** 2020-04-30 17:21 UTC
