### ISSUE TITLE
Window preview edges flickering when any browser video is in full screen

### ISSUE THREAD

**Issue by MaciochO** [elementary/gala#1440] opened 2022-06-15 18:42 UTC
### What Happened?

Screen edges flickering when any browser video is in full screen and you press your button combination for preview window (i.e. windows button in ubuntu).

### Steps to Reproduce

1. Play video in any chosen browser and go fullscreen
2. Hit your button combination for "preview window"
3. Observe window edges "flickering"

### Expected Behavior

No flickering

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-04-02 14:32
Closing because cannot reproduce the issue in OS 7. Reply here if you still encounter the issue in OS 7 please.

**Closed by lenemter** 2023-04-02 14:32 UTC
