### ISSUE TITLE
Some apps close by themselves when going in/out of multitasking view

### ISSUE THREAD

**Issue by Freemason-12** [elementary/gala#1434] opened 2022-05-25 06:40 UTC
### What Happened?

This "bug" is a hit or miss and is a little bit tricky to reproduce and resolve.
Middle click on window (3 finger tap on touchpad) on a window closes it when on multitasking view. Gestures can be 3/4 fingers but sometimes this 3 finger tap is falsely detected when performing a swipe gesture. This results in particular app closing because of that when going in/out of multitasking view.

### Steps to Reproduce

1. Open several windows (does not matter which ones).
2. Perform 3/4 finger swipe gesture repeatedly (in that case you may falsely tap with 3 fingers which can pretty much happen)
3. A window on which a cursor is pointing closes

### Expected Behavior

No app closes and everything works fine

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by ysbaddaden** [comment] 2022-10-27 13:35
See #1485 for explanation. It's 100% reproducible when you quickly swipe up and immediately release your fingers from the trackpad (like your throwing something):

The swipe is interpreted, the multi-tasking view appears, but the quick release of your three fingers is interpreted _again_ as a 3 fingers tap (this is the bug) which happens to be the "close window" gesture of the multi-tasking view.

This doesn't happen if you keep your fingers pressed on the trackpad long enough. Longer than the maximum duration for a tap to no longer be a tap.

**Comment by Freemason-12** [comment] 2022-10-27 16:10
> See #1485 for explanation. It's 100% reproducible when you quickly swipe up and immediately release your fingers from the trackpad (like your throwing something):
> 
> The swipe is interpreted, the multi-tasking view appears, but the quick release of your three fingers is interpreted _again_ as a 3 fingers tap (this is the bug) which happens to be the "close window" gesture of the multi-tasking view.
> 
> This doesn't happen if you keep your fingers pressed on the trackpad long enough. Longer than the maximum duration for a tap to no longer be a tap.

Ok, this is a bug. but will this be resolved soon?

**Comment by lenemter** [comment] 2023-02-05 04:19
Closing as duplicate of #975.

**Closed by lenemter** 2023-02-05 04:19 UTC
