### ISSUE TITLE
Glitchy (right click) menus

### ISSUE THREAD

**Issue by Vite** [elementary/gala#1346] opened 2021-12-18 09:32 UTC
### What Happened?

Sometimes (right click) menus are very glitchy. I can not really tell how to reproduce every time because this seems to happen pretty randomly.

Example in LibreOffice: When opening a menu in the nav bar without closing it first going directly to the text with the pointer creates this buggy window border every time:
![image](https://user-images.githubusercontent.com/25325543/146635973-9fe48b52-1508-4676-a2bf-3612c1da8bb3.png)

But this is not an issue of LibreOffice, because it happens in many other apps too and with every right click menu in nearly every app basically. Exactly this also happens sometimes randomly with for example the right click menu on the desktop wallpaper. Its outher right border often does not even disappear so right clicking 10 times on the desktop wallpaper created 10 borders that stay there until i hover another window over them. Most often it is the right border, sometimes right and bottom borders.

I did reinstall elementaryOS 6 mutlitple times already but this issue happens even directly after a fresh install of elementary.
Did not have this issue with elementaryOS 5. Maybe a flatpak issue?

### Steps to Reproduce

1. Install elementaryOS
2. Right click on desktop / use right click menus in applications like the browser / use nav menus in applications like LibreOffice
3. Randomly experience described issue

### Expected Behavior

No borders left when menu disappears.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I can imagine that the issue is related to my monitor refresh rate and resolution.

Monitor: 144hz WQHD
GPU: Radeon RX 580
CPU: Ryzen 5 1600X

**Comment by ded-ared** [comment] 2021-12-18 23:41
> I can imagine that the issue is related to my monitor refresh rate and resolution.
> 
> Monitor: 144hz WQHD GPU: Radeon RX 580 CPU: Ryzen 5 1600X

Hi. It's surely not related to your monitor.
I have absolutely the same problem on two machines. It really spoils all the pleasure of using eOS.
As far as I get it, this issue goes from long ago and [still in process](https://github.com/elementary/os-patches/issues/80). Hope it will be fixed soon.

**Comment by hirusi** [comment] 2021-12-22 14:07
Also the same issue: https://github.com/elementary/applications-menu/issues/512

**Comment by lenemter** [comment] 2022-12-23 14:16
Duplicate of #605

**Closed by lenemter** 2022-12-23 14:16 UTC
