### ISSUE TITLE
Wallpaper animation not correct with multiple monitors

### ISSUE THREAD

**Issue by GammaGames** [elementary/gala#647] opened 2019-12-03 15:36 UTC
## Describe the bug
When switching workspaces with multiple monitors the wallpaper is not animated correctly. I have a Tie Fighter monitor layout and it appears that the animation tries to use the width of the side monitors.

### To Reproduce
1. Use multiple monitors
2. Switch to another workspace
3. Observe

### Expected behavior
Animation to slide into the new workspace's wallpaper, ignoring all non-primary monitors.

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/7832163/70064842-6d8e8580-15a7-11ea-910b-5d8ea70ddc2e.png)

![Screen record from 2019-12-03 08 31 09](https://user-images.githubusercontent.com/7832163/70064777-4fc12080-15a7-11ea-97c1-e7526a6f7061.gif)

## Platform Information
![image](https://user-images.githubusercontent.com/7832163/70065183-e857a080-15a7-11ea-9c46-65a2e8ffef1e.png)

- [x] I'm using the latest released stable version (with icon theme)

**Comment by lenemter** [comment] 2023-10-30 05:07
Closing because I cannot reproduce the issue in OS 7. If you still encounter it, please reply here.

**Closed by lenemter** 2023-10-30 05:07 UTC
Labels: Status: Incomplete
