### ISSUE TITLE
Window Tiling to side is not working for some apps

### ISSUE THREAD

**Issue by tmak99** [elementary/gala#839] opened 2020-06-04 14:52 UTC
## Describe the bug
Tiling windows to side is not working for all apps. Last week it was not working for Files app but working for Pictures app. This week it is working for Files app but not working for few other apps.

### Expected behaviour
Tiling should be consistent in all apps

Screen Record
/home/tmanikandan/Videos/ScreenRecord/ScreenRecord1

System Info
![image](https://user-images.githubusercontent.com/66071754/83772311-c633fd80-a672-11ea-9751-00a13c00de88.png)

Thanks

**Comment by tmak99** [comment] 2020-06-05 07:27
Today after restart tiling for Files is also not working. Tiling in sides only works for Firefox.
For all the apps the maximize works when i take the window to top, only tiling to sides are not working

**Comment by lenemter** [comment] 2024-04-28 03:54
Closing because I cannot reproduce the issue in OS 7.1

**Closed by lenemter** 2024-04-28 03:54 UTC
Labels: Status: Incomplete
