### ISSUE TITLE
"Always on top/visible workspace" options gets applied to other windows upon right clicking them

### ISSUE THREAD

**Issue by aljelly** [elementary/gala#376] opened 2018-10-21 01:17 UTC
If you right click a window's header bar and select either "Always On Top" or "Always On Visible Workspace", it starts applying the property to other windows you right click the header bars of. It stops if you disable the option you selected on all windows by clicking the option again on the last window that has the property applied.

## Steps to reproduce
1. Open at least two windows of an app that will show the header bar menu. Overlap the windows slightly, horizontally.
2. On one of them (we'll call it the first window), click on "Always On Top" (it also applies to "Always On Visible Workspace" but the issue is more apparent with the other one).
3. Now right click on the second window's header bar. Always On Top now applied to the second window you right clicked and both windows will be able to be in front of each other when you left click them.
4. Right click the second window again, and you'll see the check box on Always On Top, but it was disabled upon right clicking the window (this is self evident as the first window will go on top of the second window as soon as you right click the second window again).
5. Right click the first window again, and click on Always On Top. Since this was the last window with it enabled, the behaviour will stop.

It also happens when you set a keyboard shortcut for Always On Top and perform the shortcut on a window, but the behaviour then gets really weird.

**Comment by lenemter** [comment] 2023-08-27 08:54
Closing because I cannot reproduce the issue. Please reply here if you still encounter it.

**Closed by lenemter** 2023-08-27 08:54 UTC
