### ISSUE TITLE
Windows glitch out when trying to tile to a width smaller than the minimal width of the application.

### ISSUE THREAD

**Issue by blaine00** [elementary/gala#361] opened 2018-10-18 01:53 UTC
To create this issue, open AppCenter. Tile it to the left of the screen. Now, grab the right side and pull it out until AppCenter takes up 75% of the screen. Now, open System Settings. Try to tile it to the right. If you drag it to the right, you'll see an outline of the free 25% of the screen as though the app is about to tile to it, but it kinda glitch out for a moment instead. When moving it back, you'll may also notice some brief visual artifacts. Now, try tiling it to the right with the Ctrl+Super+Right key combination. You should really be able to see the glitching in action... especially if you hold down Ctrl+Super+Right.

Notes: When pulling out right left most application, you have to make sure the remaining space on the left is less than System Settings minimum width.

Humble Suggestion: Obviously, you can't have an application tile to a width smaller than it's minimum width. I think it would be more "user friendly" to have the application subtly pop forward when the user tries to tile to an impossible size. There can be a "ding" sound as well.

**Comment by lenemter** [comment] 2023-12-13 10:49
Duplicate of https://github.com/elementary/gala/issues/188.

**Closed by lenemter** 2023-12-13 10:49 UTC
