### ISSUE TITLE
[odin-beta] QT/KDE applications always get light window borders

### ISSUE THREAD

**Issue by gvansanden** [elementary/gala#1159] opened 2021-06-02 08:47 UTC
## What Happened
When you install an application like QTermanal or Konsole, you can set their theme to a dark one to match elementary's dark style.  But the window borders will always be the light theme, which looks quite bad.

## Expected Behavior
Either the default window decorations should follow the selected style in elementary or if possible match the style of the widgets in the toolkit (QT in this case).  I think the first option is the easiest and most sensible.

## Steps to Reproduce

1. Install Qterminal
2. Set Adwaita-Dark as widget theme
3. See the light decorations on an otherwise dark application

## Platform Information
6.0 Beta, updated to 2021-06-02

**Comment by cassidyjames** [comment] 2021-06-02 18:24
Thanks for reporting! This is actually a duplicate of #956.

**Closed** 2021-06-02 18:24 UTC
Labels: Status: Duplicate
