### ISSUE TITLE
Two workspaces right after booting

### ISSUE THREAD

**Issue by inad9300** [elementary/gala#728] opened 2020-03-01 16:03 UTC
Quite often, right after starting elementary OS, I see two workspaces initialized from the beginning, i.e. there is a blank workspace to the right which I haven't created.

![double-workspace](https://user-images.githubusercontent.com/3440331/75629028-dc976c80-5bde-11ea-8acf-1974a5d6d6c7.png)

**Comment by Blast-City** [comment] 2020-03-03 18:01
Hi.
Could you close this issue or add the picture to #506 since it is a duplicate.
Sorry.

**Comment by ryonakano** [comment] 2020-03-03 22:52
Closing as a duplicate of #506

**Closed by ryonakano** 2020-03-03 22:52 UTC
