### ISSUE TITLE
Add a gesture to drag window

### ISSUE THREAD

**Issue by Faelian** [elementary/gala#1366] opened 2022-01-17 17:53 UTC
### Problem

It would be nice to have a way to move windows without a double click.

Moving windows is one of the most common operations on an operating system, and double-clicking is an effort on trackpads.

### Proposal

On Mac OS, a 3 finger tap on the titlebar / headerbar of an application can be used to move a window.

This would allow users to move windows without double clicking, and provide a bigger surface where the user can click to drag the window.

Another solution could be to use a single click instead of a double click on the empty space of an headerbar / title to drag the window.

### Prior Art (Optional)

https://support.apple.com/en-us/HT204895#tppageswipe

**Comment by danrabbit** [comment] 2022-01-17 18:00
Closing as a duplicate of #1015

**Closed** 2022-01-17 18:00 UTC
