### ISSUE TITLE
Noisy background after login from suspend

### ISSUE THREAD

**Issue by xayden** [elementary/gala#208] opened 2018-03-21 11:59 UTC
This is what happens after suspending elementary

![screenshot from 2018-03-21 13-27-32](https://user-images.githubusercontent.com/23618008/37707668-a2ad3d72-2d0c-11e8-9d8d-8076fa37f4bc.png)
![screenshot 2018-03-21 13 34 21](https://user-images.githubusercontent.com/23618008/37707677-a9732982-2d0c-11e8-9265-2431ba837f09.png)

How to fix this?

**Comment by btkostner** [comment] 2018-03-21 13:54
nvidia graphics?

**Comment by peteruithoven** [comment] 2018-03-21 17:10
There are  many questions on Stack Exchange like this: https://elementaryos.stackexchange.com/questions/8952/artifacts-in-background

**Comment by xayden** [comment] 2018-03-29 05:14
Sorry for the really late response. Yes, I've got Nvidia graphics. I've tried to install a different driver and suspend doesn't work anymore.

**Comment by augustin-b** [comment] 2018-04-14 09:50
Here's a little workaround, but I'm not sure if this could help you:

https://github.com/elementary/gala/issues/156

Your issue could be something different.

Does it still happen even if you reload gala and then suspend your machine again?

I mean:

1. suspend your machine
2. resume
3. reload gala with gala --replace
4. suspend and resume your machine again

In my case it happens only for one time after resume.
When gala is reloaded the issue is gone for every subsequent suspend.

**Comment by cassidyjames** [comment] 2018-09-24 05:47
Duplicate of #21

**Closed by cassidyjames** 2018-09-24 05:47 UTC
Labels: NVIDIA
