### ISSUE TITLE
Auto-tiling feature like in Pop_OS!

### ISSUE THREAD

**Issue by reesericci** [elementary/gala#870] opened 2020-07-10 20:26 UTC
## Prerequisites
-  I have searched open and closed issues for duplicates. - check!

## Feature
**Is your feature request related to a problem? Please describe.**

I think it would be really cool if an option for auto-tiling windows was added like what is found in Pop_OS! 's gnome shell.

**Describe the solution you'd like**

When I enable this feature, it would automatically tile my windows in a preferred layout. (Select from common layouts found in tiling window managers; e.g. master & stack, bsp, etc)

**Existing work**
The Pop_OS! Gnome shell has this feature, but I'm envisioning choosing between layouts.

**Describe alternatives you've considered**
None

**Additional context**
Kinda like a tiling WM, slapped onto a DE (pantheon).

**Comment by reesericci** [comment] 2020-07-19 22:38
@elementary any update?

**Comment by Selduro** [comment] 2020-07-26 08:29
Having an such extensive tiling-manager would of course be awesome. I for now would be completely satisfied if I had the possibility to not only manually split the windows vertically but also horizontally so that the window automatically occupies a quarter of the screen in the corner that I pull it in.

**Comment by reesericci** [comment] 2020-08-02 23:08
any other response?

**Comment by Julioevm** [comment] 2020-08-31 13:49
I  think there are a couple of PRs with functionality to enhance the tiling aspect.

**Comment by reesericci** [comment] 2020-09-02 12:12
ok

**Comment by cassidyjames** [comment] 2021-01-27 18:56
Duplicate of #316

**Closed by cassidyjames** 2021-01-27 18:56 UTC
