### ISSUE TITLE
Lock of screen will not dim screen

### ISSUE THREAD

**Issue by vaclavhlobil** [elementary/gala#382] opened 2018-10-22 20:37 UTC
When I lock screen (with Win+L) I can see multiple screen blinking and after while login screen is shown. I suppose screen should stay dimmed until keypress or mouse move. (Juno final, fresh install.)

**Comment by lenemter** [comment] 2023-12-13 10:59
Closing because I cannot reproduce the issue in Os 7.1

**Closed by lenemter** 2023-12-13 10:59 UTC
