### ISSUE TITLE
expose workspaces doesn't work with second monitor

### ISSUE THREAD

**Issue by mpkh** [elementary/gala#82] opened 2017-09-20 06:22 UTC
early it was working now I only see main monitor windows (Im using win+tab for it but can't find in dconf where is it)
only `org.gnome.desktop.wm.keybindings show-desktop ['<Super>Tab']` but I guess it's not related

**Comment by matzipan** [comment] 2017-09-21 19:46
I hope I understood your bug correctly (there is no clear description of what the result and the xpected results are). 

Changing the workspaces only works on the main monitor by design. Closing as wontfix.

**Closed by matzipan** 2017-09-21 19:46 UTC

**Comment by mpkh** [comment] 2017-09-21 20:31
@matzipan no it's not, there is setting in mutter dconf (I don't remeber but was dicsussed in irc) which allows workspace to change on both monitors, it's ON by default, gala workspace-view mode can't deal with that, only with disabling dconf option gala's workspace-view works sane.

**Comment by matzipan** [comment] 2017-09-22 08:40
It's not that Gala _cant_ deal with it, it's that it _wont_ deal with it. By design.

**Comment by mpkh** [comment] 2017-09-22 09:12
@matzipan  okay, I don't really need that feature. I just didn't know how to disable workspace on both monitors, now Im fine. Is there gala roadmap somewhere?

**Comment by matzipan** [comment] 2017-09-22 09:16
Ok, can you clarify again what are you trying to do? You are trying to switch workspaces? Can you clarify what are the steps you are taking and what is the expected outcome and the actual outcome?

**Comment by mpkh** [comment] 2017-09-22 10:08
@matzipan Im running workspace-view thing just to pick some window (I use it instead of alt+tab) and if mutter dconf setting is set to use both monitors for workspaces then I see only gray screen on second (non main) monitor
