### ISSUE TITLE
No window previews in multitasking view after changing workspace

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1354] opened 2022-01-03 19:29 UTC
### What Happened?

When entering multitasking view, none of the windows have previews anymore after changing workspaces

### Steps to Reproduce

1. Open multitasking view
2. scroll to switch workspace
3. 
![Screenshot from 2022-01-03 11 28 53](https://user-images.githubusercontent.com/7277719/147971726-28e3779a-2950-4f63-8933-c38ee0ef571a.png)

### Expected Behavior

Window previews should remain even when switching workspaces

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by Tireg** [comment] 2022-04-25 20:33
Probably a duplicate of #1326 (all mutter versions impacted since mutter-40)

**Closed** 2022-10-05 16:09 UTC
