### ISSUE TITLE
Shortcuts don't work after using Alt+Tab until window is clicked

### ISSUE THREAD

**Issue by RobinBoers** [elementary/gala#1401] opened 2022-04-14 14:20 UTC
### What Happened?

When using the Alt+Tab switcher to switch windows the shortcuts for that window (like closing, maximizing etc.) don't work until the window is interacted with (by for example moving it).

### Steps to Reproduce

1. Open 2 or more windows
2. Use Alt+Tab to switch between them
3. Try to close or maximize it using shortcuts

### Expected Behavior

It works and does the thing I ask it to do.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

**Kernel:** Linux 5.13.0-39-generic
**CPU:** 8× AMD Ryzen 7 5700u with radeon graphics 
**RAM:** 16GB

**Comment by amz-x** [comment] 2022-04-29 11:50
Can also confirm this on Fedora 36.

**Comment by jeremypw** [comment] 2022-07-07 10:00
Confirmed for OS6.1 daily but does not occur in OS7 even though the same version of Gala is installed,  @tintou Could this be an unexpected consequence of #1407?

**Comment by RobinBoers** [comment] 2022-07-28 17:42
I got so annoyed by this issue (and several other things) that I decided to switch back to Arch Linux with a custom WM.

**Comment by activey** [comment] 2022-07-28 18:51
Yeah, lets create our own elementary, with black jack and hookers

**Comment by Obema12** [comment] 2022-08-23 12:49
I have the same problem with archlinux+pantheon and latest versions of gala.

**Comment by activey** [comment] 2022-08-26 14:39
Is it fixed in Elementary 6.1 recently released? ;) @danrabbit?

**Comment by activey** [comment] 2022-11-04 16:38
Btw, I can see there are over 400 issues reported in gala project, is there any... roadmap for fixing them? Are all of them still valid? @danirabbit ?

**Comment by marco4mp** [comment] 2023-02-01 20:27
Apparently I no longer have this problem on Elementary 7.

**Comment by lenemter** [comment] 2023-02-10 10:19
Seems to be fixed in OS 7 as reported by @jeremypw and @marco4mp.

**Closed by lenemter** 2023-02-10 10:19 UTC
