### ISSUE TITLE
Middle click to kill workspace (in overview) should be optional

### ISSUE THREAD

**Issue by hanaral** [elementary/gala#975] opened 2020-11-25 14:00 UTC
## Problem
When testing the gestures branch I've noticed how often I swipe up, lift my fingers off, and then place them back down on the touchpad. As you can probably guess, it is annoying to loose all the apps in a workspace because of a shortcut you didn't know about.

## Proposal
Just make it a toggle in the new gestures panel under 'mouse and touchpad' in settings

**Comment by ibrahimrahman** [comment] 2020-12-30 21:49
Making it a toggle is still a better solution than removing it altogether as suggested in #977, which would take away functionality from mouse users for whom gestures are of little use. I personally use the middle click in workspace overview a lot and hope that it would stay.

Something else that could be done is making mouse clicks register after the mouse button has been released. This way the app will not close unless you lift your fingers without moving them at all. 

IIRC, Windows, unlike elementary, doesn't take any action until the mouse button is released. On button press, it just gives a visual feedback relating to what was clicked. I think this is a much more pleasant approach as it gives an impression of something actually being pressed, while also giving users a chance to rectify a miss-click

**Comment by danrabbit** [comment] 2020-12-30 21:54
I haven't looked at the code yet, but yeah if it's activating on press instead of on release that's an issue

If that doesn't resolve it, we should probably make sure that we're only listening to mouse events and ignoring three finger taps

**Comment by cassidyjames** [comment] 2020-12-31 18:43
@danrabbit I don't know what the proper solution is here to ensure things don't conflict, but I personally use three-finger tap to close apps all the time; it would be super frustrating to lose that. I guess this is where I prefer four fingers for workspace gestures so there's less of a possibility of a conflict.

It might be non-ideal, but I wonder if we can only respond to a three-finger _physical_ click on touchpads, and just ignore the tap-to-click if we _have_ to ignore something. That would mean we retain the ability to three-finger close apps, but you just have to physically click down on a touchpad instead of accidentally tapping when trying to do a gesture.

**Comment by hanaral** [comment] 2020-12-31 22:11
>@danrabbit I don't know what the proper solution is here to ensure things don't conflict, but I personally use three-finger tap to close apps all the time; it would be super frustrating to lose that. I guess this is where I prefer four fingers for workspace gestures so there's less of a possibility of a conflict. ...

@cassidyjames my ThinkPads touchpad isn’t terribly accurate, so I some times kill my entire workspace by accident despite only having 4 finger gestures like you.

**Comment by cassidyjames** [comment] 2021-01-01 20:49
Ah yeah I forgot middle-click to close a _workspace_ was a thing in addition to closing windows. Yeah I think that's maybe more problematic. I don't ever close entire workspaces on purpose. 😅

**Comment by Freemason-12** [comment] 2023-02-05 15:11
This issue is there for 2 years. Will it be resolved soon? It's one of the main dealbreakers for me not to use elementary

**Comment by danirabbit** [comment] 2023-02-22 05:26
I think we can probably consider this closed after #1560. It's now much much harder to accidentally trigger a close. I can't reproduce the issue as described by OP any longer and I tried to reproduce with some really sloppy movements and couldn't trigger an accidental close

**Closed by danirabbit** 2023-02-22 05:26 UTC
Labels: Status: Confirmed, Needs Design
