### ISSUE TITLE
Focused PIP breaks alt tab

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#399] opened 2018-10-28 00:09 UTC
Reproduce:
1. Put PIP's source window in seperate workspace
1. Go to other workspace
1. Make sure there are other windows open on this workspace
1. Click on PIP popup, this will navigate you to workspace with PIP's source window
1. Navigate back to other workspace (using keyboard shortcut for example)
1. Try switching between windows using alt+tab. You'll weird effects.

**Comment by lenemter** [comment] 2023-08-27 08:43
Closing the issue because it's old and irreproducible. If you still encounter it, please reopen.

**Closed by lenemter** 2023-08-27 08:43 UTC
