### ISSUE TITLE
Legacy Windows have too strong shadows

### ISSUE THREAD

**Issue by lainsce** [elementary/gala#621] opened 2019-10-23 03:46 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Legacy windows have a stronger shadow than usual, making them quickly ugly.

### To Reproduce
Just open any legacy non-GTK window like an electron app or derivatives.

### Expected behavior
The shadows should match Files's window shadow

### Screenshots or screen recordings
![Screenshot from 2019-10-23 00 44 27](https://user-images.githubusercontent.com/4886639/67355740-69923100-f52e-11e9-8f8a-83e1f896a8d8.png)

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by ryonakano** [comment] 2019-10-23 11:38
Duplicate of #391?

Quoted [a comment](https://github.com/elementary/gala/issues/391#issuecomment-545281758) in that issue:

> It's not because of Snap, but because those apps are using legacy decorations.

**Comment by danrabbit** [comment] 2019-10-23 15:58
Yeah duplicate of #391

**Closed by danrabbit** 2019-10-23 15:58 UTC
