### ISSUE TITLE
Graphical Glitches and blank desktop after waking from suspend using Nvidia 390 Proprietary Drivers

### ISSUE THREAD

**Issue by Austint30** [elementary/gala#378] opened 2018-10-21 16:39 UTC
Using the proprietary Nvidia drivers seems to be very unstable while suspending and waking. Usually after being suspended for a long amount a time (a few hours or so), the lock screen fails to display correctly and has graphical corruptions. After unlocking, the desktop also has these graphical corruptions: the rounded corners of the screen display as white boxes; the background of the multitasking view is completely corrupted. Sometimes after an entire night of suspension, the lock screen just fails to display anything other than the desktop background.
Rebooting the computer fixes all of these problems. Also typing `gala --replace` temporarily fixes the graphical corruptions on the desktop, but after a suspend it gets corrupted again.

My System Specs
- Quad-Core Intel® Core™ i5-4590 CPU @ 3.30GHz
- Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)
- NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
- 16.2 GB memory
- nvidia-driver-390

**Comment by peteruithoven** [comment] 2018-10-21 16:42
Thanks for the report! This is actually a duplicate of https://github.com/elementary/gala/issues/21
Please check the existing issue queue before posting new issues.

**Closed by peteruithoven** 2018-10-21 16:42 UTC
