### ISSUE TITLE
Animation Lags Switching from Multi-task View to a Window

### ISSUE THREAD

**Issue by GavinXSF** [elementary/gala#1525] opened 2023-02-05 12:02 UTC
### What Happened?

Every time when I choose an application from the multi-tasking view, the animation of window focus lags no matter what the app is.
However, entering multi-tasking view is smooth.

### Steps to Reproduce

1. enter multi-tasking
2. choose an app to switch to the window

### Expected Behavior

The latency is too obvious.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Lenovo Laptop, AMD Ryzen R7-5800H, integrated graphics card.

**Comment by lenemter** [comment] 2023-02-05 12:08
Hello. Thanks for reporting. I'm going to close this as duplicate of #1136.

**Closed by lenemter** 2023-02-05 12:08 UTC

**Comment by GavinXSF** [comment] 2023-02-05 14:37
> 

I checked #1136 and found that you have merged #1498, isn't it included in OS 7?

**Comment by lenemter** [comment] 2023-02-05 15:52
@GavinXSF #1498 is included in OS 7 but as you can see perfomance issues are still there.

**Comment by GavinXSF** [comment] 2023-02-05 16:12
> @GavinXSF #1498 is included in OS 7 but as you can see performance issues are still there.

OK, I'll see if further updates improve this. Thanks for your help.
