### ISSUE TITLE
Dock flickering

### ISSUE THREAD

**Issue by Letterus** [elementary/gala#2080] opened 2024-09-20 15:58 UTC
### What Happened?

Dock sometimes gets in "flickering" mode when using an app in full screen. When moving the cursor to the bottom of the screen it appears shortly and immediately disappears so you can't click an icon anymore.

### Steps to Reproduce

Hard to reproduce. It appears with apps in full screen mode (Firefox f.e.), but not always.

1. Open an app in full screen mode (f.e. Firefox).
2. Try to use the dock (it may be in "flickering mode")
3. You can stop the flickering mode by enabling the application menu once, f.e.

### Expected Behavior

Dock should always appear smoothly and stay to await my clicks.

### OS Version

8.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Thinkpad X280
Wayland session, 1.25x scale, i915 graphics driver.

**Comment by leolost2605** [comment] 2024-10-07 14:52
If we are talking about maximized here (which I assume we are since with fullscreen the dock shouldn't show at all) two ways I can currently reproduce this is the one fixed in #2081 and right after gala was started if the first launched window is maximized (although that's not 100% of the time but quite often)

**Comment by leolost2605** [comment] 2024-10-07 15:30
> if there is no window on the workspace if the first launched window is maximized (although that's not 100% of the time but quite often)

This should be fixed by #2070 although that's purely coincidental :)

**Closed** 2024-10-24 12:48 UTC
Labels: Status: Confirmed, Priority: High

**Comment by Letterus** [comment] 2024-10-26 07:12
It is! This really improves UX instantly! Thanks a lot!
