### ISSUE TITLE
Grey screenshot when trying to capture YouTube on full-screen

### ISSUE THREAD

**Issue by inad9300** [elementary/gala#215] opened 2018-03-24 16:08 UTC
This is what I get when using the "print screen" key when a YouTube video is displayed full-screen on Firefox:

![screenshot from 2018-03-24 12-37-37](https://user-images.githubusercontent.com/3440331/37866021-e0f58916-2f84-11e8-98b5-4b0165b20605.png)

Funny enough, I was trying to capture the screen in order to report a different bug. In fact, to support a bug I have already reported but that was ignored (https://github.com/elementary/stylesheet/issues/209). (When you go full-screen on YouTube on Firefox, a message is displayed indicating this fact. This message contains a button which is fully unreadable.)

**Comment by mjwhodur** [comment] 2018-03-29 09:37
It seems not a bug but some kind of problem in MPEG codec lub some kind of drawing system (I'm not experienced in WMs). It often happens also on Windows and other OSes. It seems like some kind of protection system. Ie. you cannot PrtScr on some videos in Windows (i.e. Windows Media Player or VLC [if not using its internal mechanism]). In macOS you cannot Grab some pictures in QuickTime - they will be black or gray.

**Comment by inad9300** [comment] 2018-03-29 09:53
Thanks a lot for the feedback. I have no problems on Windows capturing YouTube videos on full-screen mode. Also, I have no problems capturing YouTube videos on elementary when they are not on full-screen mode.

So I don't think what you say is actually the case, although it is a very interesting insight. Any ideas on how to test your hypothesis?

**Comment by mjwhodur** [comment] 2018-03-29 10:51
Let me test on another OS, So I can reply :)

Happy Easter!

czw., 29.03.2018, 11:53 użytkownik Daniel M. <notifications@github.com>
napisał:

**Comment by lenemter** [comment] 2023-08-27 08:23
Closing because the issue is old and irreproducible.

**Closed by lenemter** 2023-08-27 08:23 UTC
