### ISSUE TITLE
White bar on top window of applications when using Dark mode

### ISSUE THREAD

**Issue by rleyvasal** [elementary/gala#1494] opened 2022-10-27 05:48 UTC
# Issue
White bar on top window of application still shows after choosing Dark mode in Settings.

# OS version
elementary OS 6.1 

# Steps to replicate

1. System Settings → Appearance →  Dark
2. Open installed application (e.g. VScode or Brave Browser)

# Expected result
Should have dark style on the top windows as well 

# Screenshot
![window top minimize bar not dark mode 2](https://user-images.githubusercontent.com/61335136/198201278-dbbcf174-f08a-482d-a2ef-c0382c07a7a0.png)

**Comment by lenemter** [comment] 2022-12-22 10:29
Duplicate of #956

**Closed by lenemter** 2022-12-22 10:29 UTC
