### ISSUE TITLE
Notify user when they left/right click desktop multiple times

### ISSUE THREAD

**Issue by steakscience** [elementary/gala#323] opened 2018-08-24 00:46 UTC
I understand elementary wants to have an empty desktop. However this is confusing to new users, a good way to help them out would be to have a tooltip appear after several left/right clicks on desktop, maybe saying something like "elementary doesn't support files on the Desktop, try using the Files app"

**Comment by cassidyjames** [comment] 2018-09-13 05:46
If we're going this route at all, I think I'd rather just add a context menu to the Desktop or Wallpaper settings. This would re-enforce that there's no file management going on here, but be less condescending and give them something they can actually do.

**Comment by danrabbit** [comment] 2019-12-12 00:22
Agreed. Closing as a duplicate of #113

**Closed by danrabbit** 2019-12-12 00:22 UTC

**Comment by cassidyjames** [comment] 2019-12-12 22:44
@danrabbit I think this is actually a dupe of #521; #113 looks like it's some custom menu feature request, but #521 is specifically about Display and Wallpaper settings.
