### ISSUE TITLE
Weird workspace transition with multiple monitors with different resolutions

### ISSUE THREAD

**Issue by tkashkin** [elementary/gala#428] opened 2018-12-14 15:54 UTC
I have a two displays with different resolutions:
* primary 3440x1440+1920+0
* 1920x1080+0+0

![image](https://user-images.githubusercontent.com/2003017/50012651-445c9a00-ffd0-11e8-97fd-b4d0b197ccd2.png)

Workspace transition is broken ([video](https://github.com/elementary/gala/files/2680737/transition.mp4.zip)).

Probably related to #326.

**Comment by lenemter** [comment] 2023-10-30 05:05
Closing because I cannot reproduce the issue in OS 7. If you still encounter it, please reply here.

**Closed by lenemter** 2023-10-30 05:05 UTC
