### ISSUE TITLE
Alt-Shift-Tab breaks window switching

### ISSUE THREAD

**Issue by joshuajaharwood** [elementary/gala#916] opened 2020-09-08 20:02 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Alt-tabbing to switch windows works fine. However, when using Alt-Shift-Tab, the switcher gets stuck and can only be fixed by clicking a program icon on Plank.

### To Reproduce
1. Press alt-tab, keep holding alt.
2. With alt held down, press shift on its own or in another combination (i.e. alt-shift-tab).
3. The selection screen will now be stuck.
4. You can free yourself from this by clicking an icon on Plank dock.

### Expected behavior

Either normal alt-tabbing behaviour or reversed alt-tab behaviour when using alt-SHIFT-tab, whichever is intended.

### Screenshots or screen recordings

The screen is stuck in this state, as described above:
![Screenshot from 2020-09-08 19 58 37](https://user-images.githubusercontent.com/1280942/92522140-e0e7b680-f20d-11ea-9355-e9d47d8a54bc.png)

### Logs

Available on request.

## Platform Information

![Screenshot from 2020-09-08 19 00 59](https://user-images.githubusercontent.com/1280942/92522222-f65ce080-f20d-11ea-9bda-50e53629db55.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version
- [x] I'm using the latest daily build (08/09/20)

**Comment by cassidyjames** [comment] 2020-09-08 20:54
This is a duplicate of https://github.com/elementary/default-settings/issues/4 which has been reported multiple times here (#18, #351, #873).

**Closed by cassidyjames** 2020-09-08 20:54 UTC
