### ISSUE TITLE
Crash when using Alt-tab in the last open window.

### ISSUE THREAD

**Issue by luiscastillovillena** [elementary/gala#1362] opened 2022-01-14 01:26 UTC
### What Happened?

When switching windows with Alt-tab, the desktop hangs for a moment, sometimes the desktop freezes and the login window is displayed. This happens when only one window is left open.

### Steps to Reproduce

1. Open more than one window / app
2. Use Alt-tab to switch windows
3. Close the window.
4. Repeat step 2 until only one window remains.
5. Using Alt-tab presents the error.

### Expected Behavior

The desktop should not freeze or log out

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No error messages
```

**Comment by TomiOhl** [comment] 2022-01-14 19:33
Can confirm, someone already opened an issue for this: https://github.com/elementary/gala/issues/1343

**Comment by TomiOhl** [comment] 2022-04-08 19:04
Seems to be fixed in Gala 6.3.1.

**Comment by lenemter** [comment] 2023-02-22 07:54
Duplicate of #1343

**Closed by lenemter** 2023-02-22 07:54 UTC
