### ISSUE TITLE
[Window Switcher] Even though dialogue windows are not displayed, an extra Alt+Tab is needed to reach other windows.

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#1157] opened 2021-05-26 13:09 UTC
## What Happened

By default Alt+Tab makes the window switcher switch to next windows in the current workspace. An extra Alt+Tab is needed when one of the windows have a dialogue in front of it even thought the window switcher doesn't show that window.

## Expected Behavior

If the window switcher doesn't show dialogue windows it shouldn't include it in the times that Alt+Tab is needed to be pressed to reach other windows.

## Steps to Reproduce

1. Open Calculator
2. Open Terminal and paste the following command: `sudo sleep 0`
3. Press Alt+Tab to switch to the Calculator. The Calculator window is focused.
4. Press Alt+Tab to switch to the Terminal. The Terminal window is focused with the dialogue in the front.
5. Press Alt+Tab to switch to the Calculator again. The Terminal window remains focused with the dialogue in the front.

## Platform Information

elementary OS 5.1.7 Hera

**Comment by lenemter** [comment] 2023-02-11 13:10
I can't reproduce the issue on OS 7. I guess the issue was resolved in OS 6.1 when new window switcher was presented.

**Closed by lenemter** 2023-02-11 13:10 UTC
