### ISSUE TITLE
Context and drop-down menus cause weird graphical artifacts (shadows remain on screen) 

### ISSUE THREAD

**Issue by ywarnecke** [elementary/gala#605] opened 2019-09-02 06:19 UTC
I just recently installed elementaryOS again and I really like it. It feels like feels like a perfect mixture between appearance and workflow. 

However I noticed a bug with the menus in elementaryOS.
If a context menu or drop down menu is opened and then closed again, a part of the shadow will remain on screen. This is not limited to one artifact at a time and is especially apparent in LibreOffice, where the Shadow will flash with the text-position cursor. 

![Bildschirmfoto von 2019-09-02 08-07-21](https://user-images.githubusercontent.com/54791614/64093727-c86ed180-cd59-11e9-875f-c20069a77ed3.png)

This is my current System with two displays:

![Bildschirmfoto von 2019-09-02 08-16-57](https://user-images.githubusercontent.com/54791614/64093846-1d124c80-cd5a-11e9-8bb7-a80a347375a5.png)

I am using the newest NVIDIA Drivers (nvidia-driver-430).

**Comment by Blast-City** [comment] 2019-09-02 15:10
I'm also seeing this issue, but I thought it was Firefox.
Do you have "ui.context_menus.after_mouseup" set to "true" in Firefox's about:config?

**Comment by marlock9** [comment] 2019-09-03 10:13
I have had the same bug in elementary's Files app sometime ago on Fedora 30, but after update gala to latest git snapshot I don't see this anymore (I hope). I'm not using LibreOffice or Firefox but I will install them and try to reproduce.

**Comment by worldofpeace** [comment] 2019-09-03 13:32
I've noticed this often in NixOS, using gala 50694796d4c8f0ca92517d5a628b0efdf748279c.
I'll see if updating to mutter to the tip of `gnome-3-28` branch changes anything, and it can still be reproduced.

**Comment by marlock9** [comment] 2019-09-04 06:05
Okay, I've tested Firefox and I have this bug.
gala a790d2d.

**Comment by Twicee96** [comment] 2019-09-04 17:16
Upon further inspection it only seems to happen with non-system menus (e.g. Firefox uses its own context menu). With Epiphany or elementary's file explorer there are no problems at all.

**Comment by stickway** [comment] 2019-09-05 05:02
I have the same problem too. Libreoffice and Firefox.

**Comment by worldofpeace** [comment] 2019-09-05 22:08
I'd like to note if you don't have any further detail to account than "me too", the thumbs up feature should be adequate.

**Comment by J0Ar** [comment] 2019-09-08 10:18
Duplicate of https://github.com/elementary/os/issues/214

**Comment by worldofpeace** [comment] 2019-09-08 10:20
What was version change in the updated mutter packages? Since it appears to be tied to this it's most likely a regression that could possibly be fixed in gala (assuming).

**Comment by J0Ar** [comment] 2019-09-08 10:29
> What was version change in the updated mutter packages? Since it appears to be tied to this it's most likely a regression that could possibly be fixed in gala (assuming).

At the moment i blocked the update of **libmutter-2-0** (sidenote: this prevents an update of gala too) and so i did not see any artifacts.
 
![Bildschirmfoto von 2019-09-08 12-23-22](https://user-images.githubusercontent.com/23266409/64486924-083f2880-d234-11e9-95cf-09c1b3761446.png)

**Comment by worldofpeace** [comment] 2019-09-15 22:28
I downgraded mutter to 3.28.2 in NixOS and the issue is gone.
Seems to be a regression for gala when using 3.28.4 :+1:

**Comment by worldofpeace** [comment] 2019-09-15 23:46
Found upstream bug report
* https://gitlab.gnome.org/GNOME/mutter/issues/536

They identified the bad commit as
* https://gitlab.gnome.org/GNOME/mutter/commit/527f6ef8357f614793035a999ec4409ef02470e2

I also ran git bisect with mutter and gala on NixOS and identified the same commit.

So what elementary OS could do is patch mutter by reverting the aforementioned commit.

**Comment by worldofpeace** [comment] 2019-09-16 00:33
We use the following [patch](https://github.com/NixOS/nixpkgs/blob/139806d89d77a3c59785e4e59c00c7186e8e9ea6/pkgs/desktops/gnome-3/core/mutter/0001-Revert-ClutterActor-Preserve-valid-paint-volumes-til.patch) in NixOS for this.

Someone could PR against https://github.com/elementary/os-patches/tree/mutter-bionic-patched
if they'd like the patch there as well.

**Comment by linhusp** [comment] 2019-11-03 18:56
Found somthing new here. Looks like the issue gone if we set this environment variable `MOZ_USE_XINPUT2="1"` or simply just use `MOZ_USE_XINPUT2="1" firefox` to run the browser.

**Comment by hanaral** [comment] 2020-12-27 18:09
**Moved from duplicate issue**

This bug seems to have been prevelant for a long time and I've been unsure whether  to report it since I'm not sure if it's a problem on the elementary side. 

## What Happened
On Mesa systems, it seems to be a common bug for Gala to continue to render the backdrops and outlines of overlay menus when they are drawn directly over the desktop, over Gtk apps (or in the case of WebKitGtk, only over header bars).
This is observed with overlays such as Gtk context menus, firefox's context menus and shadows, and also certan qt menus. I have observed this only with Gala, and with both Mesa and NVidia's drivers.

## Expected Behavior
Much like the GNOME compsitor Mutter (which Gala is based on), there should be no part of the UX that displays such artifacts.

## Steps to Reproduce

### Example 1:
1. Open a new workspace, and do not allow for Gala to re-draw the center of the screen (by opening a window, changing workspace etc)
2. Right click on the center of the screen
3. Hover over a few items, and then click off the menu
4. You should be able to observe the line east side of the menu either remaining there, or flickering as you do things outside the bugged area 

Video for referance:
https://user-images.githubusercontent.com/58219504/103150255-3e2a5800-476a-11eb-9c24-ee9fe485adfe.mp4



### Example 2:
1. Open evolution, or any app with a WebKitGtk view, and position it's window so it's context menu is either over plank and/or the desktop
2. Open a context menu close to the edge of the window
3. Observe the context menu's artifacts left behind 

Video for referance:
https://user-images.githubusercontent.com/58219504/103150259-4edace00-476a-11eb-81cc-1650defe80f6.mp4



### Example 3:
1. Open Firefox and position it's window with enough space on the desktop so that there is enough room for the context menu to render over the destkop
2. Open a context menu either from the titlebar or the browser contents
3. Observe the artifacting of the context menus over the firefox window, plank and/or the desktop

Video for referance:
https://user-images.githubusercontent.com/58219504/103150269-6619bb80-476a-11eb-9df2-9c20d8467581.mp4



### Logs
None that indicate anything abnormal:
![Screenshot from 2020-12-26 11-14-03](https://user-images.githubusercontent.com/58219504/103150374-8007ce00-476b-11eb-8143-cc295a1e1ea4.png)



## Platform Information
elementary OS 6 Daily 
Tested on Lenovo ThinkPad X240 with an i5-4300U CPU and Intel® HD Graphics 4400 (Used with default Mesa)

**Comment by hanaral** [comment] 2021-02-16 15:03
Can someone working on Gala please have a look at this? All the hardware I've tried experiences this issue with Gala and the problem persists both in elementary Hera and in the Odin dailies.
@tintou @jeremypw

**Comment by worldofpeace** [comment] 2021-02-16 21:18
I thought we already come to a conclusion that this was a mutter bug? Tried to make some noise on the mutter issue https://gitlab.gnome.org/GNOME/mutter/-/issues/536#note_724806 but it didn't seem to draw attention. I did also mention that budgie has had the same issue and they have [code to workaround it](https://github.com/solus-project/budgie-desktop/blob/master/src/wm/wm.vala#L640), so maybe we could hack around it in gala, or patch mutter in the elementary distribution. The final option is find someone willing to figure out the issue in mutter. In nixos we hold this patch https://github.com/NixOS/nixpkgs/blob/master/pkgs/desktops/gnome-3/core/mutter/3.34/0003-Fix-glitches-in-gala.patch.

**Comment by decathorpe** [comment] 2021-03-11 14:52
@worldofpeace thanks :100: to your patch, Pantheon on Fedora 34+ will not have those glitches - I applied it to the mutter 3.38 compat package since there's no movement at all about this in GNOME upstream ...

**Comment by yellowgh0st** [comment] 2021-03-21 18:54
This is still present in current 6.0 daily build.
Builded mutter from source with mentioned patch applied fixes the issue.

**Comment by yellowgh0st** [comment] 2021-03-21 18:58
What could be the appropriate way to implement this patch into elementary OS?
Could It be custom mutter binary package which would override the stock one?

**Comment by worldofpeace** [comment] 2021-03-22 13:54
> @worldofpeace thanks 100 to your patch, Pantheon on Fedora 34+ will not have those glitches - I applied it to the mutter 3.38 compat package since there's no movement at all about this in GNOME upstream ...

np @decathorpe :100:, I've been using it for sooo long at this point. It seems for downstream use of Pantheon our best solution is to keep a fork of Mutter, which I understand since Mutter upstream creates a new (better) wheel every release.

> What could be the appropriate way to implement this patch into elementary OS?
Could It be custom mutter binary package which would override the stock one?

@yellowgh0st  I've opened an issue at https://github.com/elementary/os-patches/issues/80 
If you look at the readme it should hopefully be a straightforward process.

**Comment by Zbergen-cli** [comment] 2021-03-25 00:53
I have the same problem when using the pantheon session on Archlinux, but the patch provided by @worldofpeace does not solve the problem.

**Comment by worldofpeace** [comment] 2021-03-25 11:03
@Zbergen-cli Which mutter version?

**Comment by Zbergen-cli** [comment] 2021-03-25 11:58
@worldofpeace, mutter 3.38.4-2, intel video card. Artifacts can only be seen in the pantheon session.

**Comment by hanaral** [comment] 2021-04-11 13:13
@worldofpeace Would you be able to provide a precompiled tarball? I don't have the space to compile it myself.

**Comment by JSN-1** [comment] 2021-05-03 20:33
so far i am unable to replicate this in latest Fedora 34

**Comment by hanaral** [comment] 2021-05-04 11:13
@JSN-1 Afaik fedora uses the patched version from 34 onwards

**Comment by bobby285271** [comment] 2021-10-08 02:59
Seeing https://github.com/elementary/os-patches/tree/mutter-focal-patched has no related update so far, just a note that the patch in NixOS has been updated in https://github.com/NixOS/nixpkgs/pull/73906/commits/344a5a731b138c2e3b701d5ac09a4fb6e1a8a8a1.

**Comment by danilomataveli** [comment] 2021-12-15 18:56
Im still with this bug on LibreOffice 7.2.4.1 (.deb and flatpack), using Elementary 6 (latest updates).

**Comment by Neeraj029** [comment] 2022-01-08 04:56
Facing same issue :disappointed: 
anyone found fix for this?

**Comment by JSN-1** [comment] 2022-05-18 22:52
I am seeing this issue again after i have upgraded to fedora 36.

`gala-libs-6.3.1-2.fc36.x86_64
gala-6.3.1-2.fc36.x86_64
kernel-core-5.17.7-300.fc36.x86_64`

`Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: Sunplus Innovation SPCA2085 PC Camera type: USB
    driver: uvcvideo
  Device-3: Chicony Integrated Camera type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.20.14 driver: X:
    loaded: intel gpu: i915 resolution: 1920x1080~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2)
    v: 4.6 Mesa 22.0.3
`

**Comment by lenemter** [comment] 2023-02-04 13:14
Fixed in OS 7.

**Closed by lenemter** 2023-02-04 13:14 UTC
