### ISSUE TITLE
Multiple workspace on separated monitor

### ISSUE THREAD

**Issue by kenedyroger** [elementary/gala#1267] opened 2021-10-06 17:00 UTC
### Problem

When user is working on machine witch has multiple monitors plugged in into. The main monitor can create many workspace as user want, but another secondary monitors cant create new workspace on it.

### Proposal

Allow secondaries monitors also create new workspace to be used on it, completely apart from main monitor.

### Prior Art (Optional)

![Screenshot from 2021-10-06 13 48 19](https://user-images.githubusercontent.com/12687905/136249858-c40c7e82-a858-4bef-a90d-c115a88e7f4a.png)

**Comment by Blast-City** [comment] 2021-10-10 08:49
Hi.

Is this the same issue as #26? If yes, could you please close this issue and add your proposal info to #26?

Thanks.

**Comment by lenemter** [comment] 2023-10-26 04:01
Closing as duplicate of #26

**Closed by lenemter** 2023-10-26 04:01 UTC
