### ISSUE TITLE
Picture-in-picture fails to follow cursor if moved too fast

### ISSUE THREAD

**Issue by m93a** [elementary/gala#1361] opened 2022-01-13 15:22 UTC
### What Happened?

If I drag a picture-in-picture too quickly over a window, it will get stuck behind until I return my cursor over it.

### Steps to Reproduce

1. Create a picture-in-picture of some window
2. Open another window
3. Click on the picture-in-picture **at the very edge** and hold
4. Drag the picture-in-picture over the other window, **quickly**
5. The picture-in-picture will stop getting mouse updates while your cursor is over the other window and will freeze in place
6. You can even release the mouse button while the picture-in-picture is frozen in place
7. Move your cursor back over the picture-in-picture and observe it's following your cursor once again

https://user-images.githubusercontent.com/1671665/149357725-3016aa65-6644-4d4d-9a03-cdca7f09f1de.mp4

### Expected Behavior

If I start dragging the picture-in-picture, it should still recieve mouse events until I release the button, no matter how fast I move the cursor.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-10-26 03:30
Closing because I cannot reproduce the issue in OS 7.

**Closed by lenemter** 2023-10-26 03:30 UTC
