### ISSUE TITLE
Default window sizes and placements for many apps are a bit odd 

### ISSUE THREAD

**Issue by moonmehta** [elementary/gala#472] opened 2019-02-27 08:53 UTC
On a fresh install, the default windows are neither centered nor sized consistently. Many of them like Files, AppCenter, Videos have seemingly random default sizes and placements.

![screenshot from 2019-02-27 07-13-25](https://user-images.githubusercontent.com/22585732/53477593-08978380-3a9b-11e9-9fb3-2393e0f0ad8e.png)

![screenshot from 2019-02-27 07-14-11](https://user-images.githubusercontent.com/22585732/53477595-0a614700-3a9b-11e9-887e-a29c9125d0e6.png)

**Comment by arshubham** [comment] 2019-02-27 09:53
Duplicate for https://github.com/elementary/os/issues/97

**Comment by lenemter** [comment] 2023-08-27 09:18
Closing as duplicate of https://github.com/elementary/os/issues/97.

**Closed by lenemter** 2023-08-27 09:18 UTC
