### ISSUE TITLE
Swiping Out of Multitasking View Closes Maximized Window

### ISSUE THREAD

**Issue by theuser18** [elementary/gala#1283] opened 2021-10-26 18:10 UTC
Frequently, swiping down with three fingers to get out of multitasking view will close my focused window.

For example. I have Firefox maximized. I three finger swipe up to get to the multitask view. Upon three finger swiping down, the Firefox window is closed. This is very annoying.

Please let me know how to take a log of this problem and if I need to install additional packages to take a proper log.

**Comment by danirabbit** [comment] 2023-04-01 14:19
Probably a duplicate of #975 or #977 which was recently fixed :)

**Closed by danirabbit** 2023-04-01 14:19 UTC
