### ISSUE TITLE
Broken screen

### ISSUE THREAD

**Issue by Slabi21** [elementary/gala#478] opened 2019-02-28 22:17 UTC
After removing the hibernation mode, the screen looks like this image. The bug is just that, it does not interfere with the work, at least until now.
![captura de pantalla de 2019-02-28 13-05-08](https://user-images.githubusercontent.com/48099877/53602290-14fc0900-3b8d-11e9-9477-963e360f3980.png)

**Comment by danrabbit** [comment] 2019-02-28 22:33
Transferring to Gala since this looks like maybe an issue with the background plugin

**Comment by peteruithoven** [comment] 2019-02-28 22:40
Thanks for the report! This was a known issue for Gala  and it should have been fixed.
Issue: https://github.com/elementary/gala/issues/21 
Fix: https://github.com/elementary/gala/pull/330

Are you sure you're up to date?

I'm assuming you have a NVIDIA card? Which driver are you using?

**Comment by Slabi21** [comment] 2019-03-18 15:47
Hello! Sorry for the delay of my answer, I was traveling.
I have everything updated, my video card is old and bad, it is nvidia 210.
I attached an image of my system

**Comment by Slabi21** [comment] 2019-03-18 15:47
![Captura de pantalla de 2019-03-18 12-46-24](https://user-images.githubusercontent.com/48099877/54543234-06c72e80-497c-11e9-81ea-4fdfd586eb5f.png)

**Comment by OrkanSaklan** [comment] 2019-09-30 14:09
try running
`sudo ubuntu-drivers autoinstall`
in your terminal

**Comment by lenemter** [comment] 2023-10-31 10:48
Closing because the issue is old and fixed.

**Closed by lenemter** 2023-10-31 10:48 UTC
