### ISSUE TITLE
In dark mode, the default window ribbon of other non-system programs is still in light mode

### ISSUE THREAD

**Issue by cisordeng** [elementary/gala#1676] opened 2023-05-20 17:48 UTC
### What Happened?

In dark mode, the default window ribbon of other non-system programs is still in light mode
![Screenshot from 2023-05-21 01 38 58](https://github.com/elementary/switchboard-plug-pantheon-shell/assets/42148024/df9671d7-9080-4dcf-bde9-02d5ca964201)
![image](https://github.com/elementary/switchboard-plug-pantheon-shell/assets/42148024/97f91ca5-7049-4d10-90d4-36efe20a9bad)

### Steps to Reproduce

1. Turn on the system dark mode
2. Open programs that use system windows other than the default system

### Expected Behavior

In dark theme mode, other window ribbons are also dark mode

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-05-21 07:25
Duplicate of #956

**Closed by lenemter** 2023-05-21 07:25 UTC
