### ISSUE TITLE
Application 'gala.desktop' killed by signal 11

### ISSUE THREAD

**Issue by dragonGR** [elementary/gala#1448] opened 2022-07-20 19:08 UTC
### What Happened?

During the crash, I had the following things enabled:
- Discord
- Terminal doing a compilation of a systemimage
- Spotify
- Several firefox tabs that one of them was playing a song through Youtube.
- My Oneplus 6 device connected in a ADB state

Out of sudden while I was talking with my friend over Discord, I got a black screen and was greeted with the "Log in" menu, upon entering the password I couldn't get the dock loaded So i performed CTRL+ALT+DEL to log out properly and It worked.

I went ahead and did a 'sudo cat /var/log/syslog > crash' to post that up here.

### Steps to Reproduce

There's no really a way to reproduce this, It just randomly happened.

### Expected Behavior

It shouldn't crash at all.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Log is too long. Posting a gist: https://gist.github.com/dragonGR/cd92c7e3d994e6f58f860b5b4f5ac4e8

Upon investigating, a segfault occured in gala. I suspect a desktop crash. Would take a proper look but no time for that for now.
```

### Hardware Info

AMD Ryzen 5 3600 6-Cores
Raden RX 580 Armor 4G OC
32GB RAM
1TB nvme m2

**Comment by ayoungethan** [comment] 2022-12-28 19:20
I've been getting segfaults in libmutter. I wonder if they are related?
`gala[1535]: segfault at 21c ip 00007f9bf3ed4a04 sp 00007ffffafc17b8 error 4 in libmutter-6.so.0.0.0[7f9bf3e4d000+fe000]
[38093.141195] Code: 0f af c0 01 f8 41 89 44 24 0c 48 83 c4 08 4c 89 e2 4c 89 e6 48 89 ef 5d 41 5c e9 97 fd ff ff 0f 1f 80 00 00 00 00 f3 0f 1e fa <f3> 0f 6f 87 1c 02 00 00 0f 11 06 c3 f3 0f 1e fa 41 55 41 54 49 89`

**Comment by lenemter** [comment] 2023-03-29 05:18
Closing because no steps to reproduce provided. We can't fix a bug if we don't know how to reproduce it.

**Closed by lenemter** 2023-03-29 05:18 UTC
