### ISSUE TITLE
Fractional scaling support

### ISSUE THREAD

**Issue by PlatonB** [elementary/gala#587] opened 2019-07-22 09:55 UTC
On some resolutions (for example, 1920x1080) the interface elements are very small. In KDE, Deepin and Gnome, the problem can be solved by setting 125% scaling. Is this planned for elementary OS?

![](https://aozoeky4dglp5sh0-zippykid.netdna-ssl.com/wp-content/uploads/2017/09/Screen-Shot-2017-09-22-at-00.39.31.png)

**Comment by peteruithoven** [comment] 2019-07-22 10:05
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/switchboard-plug-display/issues/117

**Closed by peteruithoven** 2019-07-22 10:06 UTC

**Comment by PlatonB** [comment] 2019-07-22 10:10
Sorry. I searched for similar issues only in the Gala section.
