### ISSUE TITLE
Confusion on getting latest release

### ISSUE THREAD

**Issue by worldofpeace** [elementary/gala#393] opened 2018-10-26 18:26 UTC
Unlike other repos, they're branches like `stable/juno` and `stable/loki` and no tags for an actual release.

Now obviously the latest would be the tip of `stable/juno` but this isn't consistent with other repos in elementary.

**Comment by danrabbit** [comment] 2019-12-12 00:28
Closing as a duplicate of #25

**Closed by danrabbit** 2019-12-12 00:28 UTC
