### ISSUE TITLE
Overview animation is stuttering

### ISSUE THREAD

**Issue by validatedev** [elementary/gala#1190] opened 2021-08-05 11:27 UTC
## What Happened

When you try to open the Overview (or Virtual Desktops) section of the DE, the whole animation stutters (like 30 FPS-15 FPS).

## Expected Behavior

It should react with a smooth animation.

## Steps to Reproduce

1. Open Workspace Overview with three-finger up with touchpad (or click the icon which is located the leftmost of Plank)
2. You can see the stutter

## Platform Information

I'm not on elementary OS 6.0 at the moment, but this problem is also there on 5.x. The problem is tested on one of the RC builds that I have built from scratch. The name of the ISO was `elementaryos-6.0-stable.20210729-rc.iso`. Using Intel i5 8265U - Intel UHD Graphics 620.
Edit: Also the problem is present on `elementaryos-6.0-stable.20210810.iso`.

## Additional Information
The problem is already reported on https://github.com/elementary/os-patches/issues/181. Also note that I have a HiDPI screen, and mutter has suffered the same problem until https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1441. Perhaps gala also lacks triple-buffering.

Video:

https://user-images.githubusercontent.com/29679552/128342256-4c0083eb-952a-4e2e-a6cb-8e185aa4df52.mp4

**Comment by lenemter** [comment] 2022-12-23 15:08
Closing as duplicate of #1136

**Closed by lenemter** 2022-12-23 15:08 UTC
