### ISSUE TITLE
Window Overview overlaps wingpanel

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#482] opened 2019-03-01 22:48 UTC
The windows in the Window Overview (<kbd>Super</kbd> + <kbd>W</kbd>) probably shouldn't overlap the wingpanel.
![screenshot from 2019-03-01 23 39 51 2x](https://user-images.githubusercontent.com/523210/53670842-6e8f3100-3c7c-11e9-8b8e-5d03ac8a3f96.png)

**Comment by lenemter** [comment] 2023-03-28 06:59
Closing because cannot reproduce in OS 7.

**Closed by lenemter** 2023-03-28 06:59 UTC
