### ISSUE TITLE
Notifications occasionally spawn in the wrong location on screen

### ISSUE THREAD

**Issue by Schykle** [elementary/gala#1239] opened 2021-08-30 06:43 UTC
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
From time to time, notifications can spawn on the left side of the screen rather than by the notifications center on the right as expected. I have noticed it typically happens more when there haven't been any notifications in a while. I've even sent test batches of hundreds of random notifications at once with the help of `notify-send` and some scripts (massive props to the notifications center being so resilient and handling this perfectly BTW), and none spawned on the left. 

### To Reproduce
1. Wait for a notification after a long period of time to spawn in an unexpected location

### Expected behavior
Notification placement is always consistent 

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/58709504/131295980-582ae980-691c-43f9-9471-73b3e416a828.png)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by danrabbit** [comment] 2021-08-31 17:33
Transferring to Gala, since the window manager is responsible for placing notification windows

**Comment by cassidyjames** [comment] 2021-08-31 18:04
Duplicate of #1229

**Closed by cassidyjames** 2021-08-31 18:04 UTC
