### ISSUE TITLE
Chrome freezing on fullscreen videos

### ISSUE THREAD

**Issue by viniciusn** [elementary/gala#414] opened 2018-11-15 12:50 UTC
When using Google Chrome version 70.0.3538.102 64 bits to reproduce videos on full screen the video freezes but the audio continues to play

![captura de tela de 2018-11-15 10-47-10](https://user-images.githubusercontent.com/6913039/48553874-f450c180-e8c3-11e8-9549-713c81c80113.png)

**Comment by peteruithoven** [comment] 2018-11-15 14:05
Thanks for the report! I'm afraid this a duplicate of https://github.com/elementary/os/issues/121

**Closed** 2018-11-15 14:06 UTC
Labels: Status: Duplicate
