### ISSUE TITLE
CTRL+ALT+SHIFT dont work on elementary OS 6 Odin

### ISSUE THREAD

**Issue by cjgomes** [elementary/gala#1307] opened 2021-11-13 20:53 UTC
### What Happened?

I working on my test environment on guacamole and when I press the combination Ctrl+Alt+Shift it doesn't work.
I install screenkey to see what the system doing when I press the shortcut and what I see is the Ctrl+Alt+ISO_Next_GROUP

![Captura de tela de 2021-11-13 16-39-14](https://user-images.githubusercontent.com/4334406/141658473-7ab551ff-ee33-424e-a6d7-9dd92ad7c275.png)

It works after I change the Altern keyboard shortcut to another combination.

### Steps to Reproduce

Install screenkey and open
Press Ctrl+Alt+Shift
Showing something different than Ctrl+Alt+Shift pressed.

### Expected Behavior

I expect that system reproduces my combintation command 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by JoseExposito** [comment] 2021-11-24 07:50
This is a side effect of the Keyboard > Layout > Switch layout keybinding being used. As a workaround, you can select in the first combo-box (see screenshot) the value "Disabled":

![image](https://user-images.githubusercontent.com/1335948/143196051-5d62c668-da4d-478d-9587-b61ddc5e87ed.png)

**Comment by m93a** [comment] 2022-12-05 09:35
This bug breaks the user experience in elementary 6 and 7, when the user tries to switch windows backwards in [Catts](https://github.com/elementary/gala/issues/1232) using Alt+Shift+Tab, and leaves the switcher in a [broken, unintuitive state](https://github.com/elementary/gala/issues/1345). I would argue that this is bad UX and a bad onboarding experience for Horus, as people coming from various different desktop environments expect Alt+Shift+Tab to work (or at least not to glitch out).

What would be the ideal solution for this? Personally, I wouldn't mind if the default "Switch layout" shorthand changed to "Alt+Space" or something similar, but since this hasn't been done, I assume others like the default shorthand the way it is? Are there other options to fix the Catts behavior while still preserving the default shorthand for switching the layout?

**Comment by peteruithoven** [comment] 2023-04-15 09:48
I think this is now a duplicate of: https://github.com/elementary/default-settings/issues/4

**Closed by peteruithoven** 2023-04-15 09:48 UTC
Labels: Status: Confirmed
