### ISSUE TITLE
在路径 org.ayatana.bamf.view 的对象上没有 /org/ayatana/bamf/application/1382123443 

### ISSUE THREAD

**Issue by Glovecc** [elementary/gala#734] opened 2020-03-04 14:24 UTC
After my latest update, I found that whenever I log in, there will be a process named  ``gala background service `` in plank for a long time. I looked through the logs and thought it should be caused by the problem here, but I don't know how to solve it.

```
Mar  4 22:09:02 junian gala[7234]: Unable to fetch children: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.ayatana.bamf.view 的对象上没有 /org/ayatana/bamf/application/1382123443 接口
Mar  4 22:09:02 junian gala[7234]: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: 在路径 org.ayatana.bamf.application 的对象上没有 /org/ayatana/bamf/application/1382123443 接口
```

**Comment by stsdc** [comment] 2020-03-04 18:06
Duplicate of #731

**Closed** 2020-03-04 21:48 UTC
