### ISSUE TITLE
Copying to clipboard using shortcuts doesn't work at all (eOS 6 Public Beta).

### ISSUE THREAD

**Issue by lilvadim** [elementary/gala#1137] opened 2021-05-13 06:48 UTC
Default shortcut `Ctrl + Print Screen` does nothing but animation of capturing an image (no sound though, but it's not an issue, I guess). Also, `Ctrl + Shift + PrtScr` does not copy anything to clipboard after choosing an area, `Ctrl + Alt + PrtScr` just does save as file. I've realized that screenshot does copy to clipboard if I manually take it with Screenshot app and click 'Copy to clipboard' button then.
By the way, as I remember, this issue took place in eOS 5.1.7.

**Comment by cassidyjames** [comment] 2021-05-14 18:59
I can confirm the shortcuts to copy to clipboard don't copy the image to the clipboard. but the copy action does work in the Screenshot app itself.

**Comment by cassidyjames** [comment] 2021-06-17 16:42
Duplicate of #1122

**Closed by cassidyjames** 2021-06-17 16:42 UTC
Labels: Priority: Medium, Status: Confirmed
