### ISSUE TITLE
Window switcher Alt + Shift + Tab issue

### ISSUE THREAD

**Issue by BarMal** [elementary/gala#1526] opened 2023-02-05 12:22 UTC
### What Happened?

Window switcher Alt + Shift + Tab does not reverse order of switching, and causes the window switcher to stay on screen even after releasing keys.

It doesn't disappear and doesn't allow user to interact with windows until a window is selected in the switcher itself.

### Steps to Reproduce

1. Have >1 apps open
2. User Alt + Tab
3. Apply Shift modifier
4. Window switcher stays on-screen

### Expected Behavior

Window switcher should reverse the direction of app-switching, and should disappear after the keys are released

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by TomiOhl** [comment] 2023-02-09 12:26
It does reverse the direction for me (latest OS7). However, the issue that it stays on screen is very much real since the new alt+tab switcher was introduced

**Comment by peteruithoven** [comment] 2023-04-15 09:27
> Window switcher Alt + Shift + Tab does not reverse order of switching, and causes the window switcher to stay on screen even after releasing keys.

These seem like 2 unrelated separate issues? Could you maybe split it?

**Comment by peteruithoven** [comment] 2023-04-15 09:43
The alt+shift+tab issue seems like a duplicate of https://github.com/elementary/default-settings/issues/4 which has been reported multiple times (https://github.com/elementary/gala/issues/18, https://github.com/elementary/gala/issues/351, https://github.com/elementary/gala/issues/873).

**Closed by peteruithoven** 2023-04-15 09:43 UTC
Labels: Status: Confirmed
