### ISSUE TITLE
Feature Request: super+ mouse scroll to switch workspaces

### ISSUE THREAD

**Issue by decembre-dhiver** [elementary/gala#1677] opened 2023-05-22 11:49 UTC
### Problem

I don't have any problem, just want to propose something that, I think, may improve usability =)

### Proposal

Allow to switch workspaces by using super+scroll (like 3 fingers swipe left or right, but using this shortcut). It' seems like a natural thing when using a mouse. It is more ergonomically IMO

**Comment by lenemter** [comment] 2023-05-22 11:52
Hello. Thanks for reporting. This is actually a duplicate of #1178.

**Closed by lenemter** 2023-05-22 11:52 UTC
