### ISSUE TITLE
Tiling an identically-sized window causes window to glitch

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#305] opened 2018-07-20 16:48 UTC
Originally reported by @ntilotta at https://github.com/elementary/os/issues/102

>elementary OS Juno 5.0 (Beta 1)
>
>If you open an electron-based app, this usually freezes after minimize/maximize, then for example Atom is transparent if you launch it maximized, and every application loses user' settings after you close and re-open it.

I've also noticed similar issues when tiling Google Chrome, both with and without the "system title bar and borders" option checked. I imagine it's the same bug since both are using Chromium and that cross-platform window code.

**Comment by Djaler** [comment] 2018-08-31 17:44
I noticed this with Insomnia. But this is not occure with Slack, for example

**Comment by GammaGames** [comment] 2018-09-25 06:05
I've had the tiling issues with both Chrome and VSCode

**Comment by GammaGames** [comment] 2018-10-19 00:40
I just found a slightly stranger issue, but I thought I'd report it here in case it is related. If it's not related it can be its own issue.

VSCode did the broken tiling thing again, so I opened the multitasking view so I could close the window. After I closed it it the window stayed on my desktop and won't go away. I can open and close more windows of VSCode but this phantom window remains.

![image](https://user-images.githubusercontent.com/7832163/47191417-702b0e80-d304-11e8-81c4-9cf0877578a6.png)

And, because I thought it was funny, here's Principles overlaying the phantom window:

![image](https://user-images.githubusercontent.com/7832163/47191520-31e21f00-d305-11e8-9574-3c192227f2f4.png)

**Comment by GammaGames** [comment] 2018-11-07 06:06
If you are able to find the edge of the window and resize it, the window will go to its correct position and correctly resize.

**Comment by suprko** [comment] 2018-12-17 18:13
I hope that this is helpful. I can get this to reproduce consistently:

1. Open Electron-based app that saves previous window width (e.g. Signal)
2. Tile the app left or right
3. Close the app
4. Reopen the app
5. Try to tile the app left or right => app wigs out

This can avoided by changing the app window size before tiling.

Because this specifically happens when the app window starts at the same size as it would be after tiling, I wonder if it's related to this other bug: [this comment](https://github.com/elementary/gala/issues/341#issuecomment-433566218) suggests that weird things are happening when there's an animation on a window whose size is exactly the same before and after an animation.

**Comment by carn1x** [comment] 2018-12-19 08:46
Getting this inconsistently but regularly with Thunderbird and Chrome.

**Comment by btkostner** [comment] 2018-12-19 16:03
@carn1x Terminal and AppCenter are not electron apps... That might be a different issue you are seeing, or the scope of this issue is different then what we thought.

**Comment by carn1x** [comment] 2018-12-20 13:21
@btkostner here's the steps I take:

1. Open AppCenter, snap to right-side of the screen, all is fine
2. Close AppCenter and reopen it, observe it is still in same window position/size
3. Snap to the right-edge again, either by mouse drag or keyboard shortcut, and observe the window freezes and is not interactive entirely (though the carousel aspect of App Center Home tab still seems to animate)
4. Use the Super+Up shortcut to maximize the window and regain interactivity and normal function.

**Comment by Djaler** [comment] 2018-12-20 13:42
@carn1x maybe this is the correct issue - #377

**Comment by peteruithoven** [comment] 2018-12-20 18:01
This sounds like the same underlying issue as: https://github.com/elementary/gala/issues/341
Which was fixed in: https://github.com/elementary/gala/pull/387 but it has not been merged yet.

**Comment by Mvrs** [comment] 2018-12-26 01:38
@carn1x and to anyone else:

Anytime the window freezes all you have to do is `super` + `UP`
This will reestablish functionality within that titled window

<strong> To prevent these freezes </strong>
* When you ctrl+super+Right to tilt the window right repeat the same command so the window centers itself back to the middle then crtl+super+left to tilt the window to the left
* When you have a program open (on the right) and you want to tilt that the new one to the left... before doing that make sure you `super` + `UP` to reestablish the window size then you can ctrl+super+left

**Closed** 2019-02-07 18:37 UTC
Labels: Priority: High, Status: Confirmed
