### ISSUE TITLE
Notifications don't overlap full screen Firefox?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/gala#134] opened 2017-12-02 13:57 UTC
Notifications don't seem to overlap Firefox in fullscreen mode, while they do overlap browsers like Chromium and Epiphany in fullscreen mode. 
With fullscreen I mean both regular websites and fullscreen video (like Youtube).
Is this something Gala can fix or is Firefox making this extra difficult?

**Comment by Astro-City** [comment] 2017-12-04 21:53
Hi.  

It shows on mine.  

Try this:  

Open the terminal in workspace 1 and firefox (fullscreen) in workspace 2

On the terminal type this:  

sleep 5 && ls 

After pressing enter immediately switch to the second workspace.  

I tried this on mine and it showed the notification on Youtube videos and just the browser on fullscreen mode.

**Comment by peteruithoven** [comment] 2017-12-04 22:29
@Astro-City That's basically how I tested this, I only didn't add the ` && ls`, but that doesn't influence the notification. (I did retry with the ` && ls` just to be sure, but that didn't change the situation).

```
Firefox: 57.0.1 (64-bit)
OS: elementary OS 0.4.1 Loki x86_64
Kernel: 4.14.3-041403-generic
GPU: NVIDIA GeForce GTX 960M (disabled, not listed in lshw -c video)
GPU: Intel HD Graphics 530
```

**Comment by Astro-City** [comment] 2017-12-05 02:37
Hi.  

I tried it again and it did happen to me, but as soon as i restarted Firefox it started showing notifications again.

**Comment by Astro-City** [comment] 2017-12-13 02:34
Have you resolved this issue?  

This seems to happen to me when i watch Twitch streams.  

It doesn't seem to affect only the notifications. The workspace switcher animation also gets disabled on the workspaces that suffer from this issue.

**Comment by peteruithoven** [comment] 2017-12-13 13:19
No, sorry, I wouldn't even know where to start. Restarting Firefox doesn't seem to change anything for me. 
I indeed also notice that the workspace switcher doesn't animate when navigating to or from the Firefox playing youtube video fullscreen.

**Comment by Astro-City** [comment] 2017-12-13 14:13
Hi.  

Thanks for replying.  

Yes it's the same for me, but i can't seem to replicate with youtube, just twitch.

**Comment by peteruithoven** [comment] 2017-12-13 14:23
Could be a difference between a HTML 5 vs. Flash player...

**Comment by Astro-City** [comment] 2017-12-13 14:45
Hi.  

I use HTML5 on both.  

On Youtube i tried with or without h264 and both showed the notification.

**Comment by Tidrek** [comment] 2017-12-21 18:54
In my case fullscreen mode in Chromium overlaps notifications. It doesn't matter whether it's the browser's F11 or elementary's fullscreen mode.

**Comment by Astro-City** [comment] 2018-01-08 23:02
> In my case fullscreen mode in Chromium overlaps notifications. It doesn't matter whether it's the browser's F11 or elementary's fullscreen mode. But it doesn't happen in Firefox :)

Hi.  

Even on Youtube videos?

**Comment by peteruithoven** [comment] 2018-10-16 03:05
This might be an interesting area to check:
https://github.com/elementary/gala/blob/master/plugins/notify/NotificationStack.vala#L59-L60

But I haven't been able to reproduce this issue consistently, making it hard to test.

**Comment by Blast-City** [comment] 2019-04-02 18:57
> This might be an interesting area to check:
> https://github.com/elementary/gala/blob/master/plugins/notify/NotificationStack.vala#L59-L60
> 
> But I haven't been able to reproduce this issue consistently, making it hard to test.

Steam games and video (video player not trailers) fullscreen and Retroarch fullscreen seems to replicate this issue every time. So it could be easier to diagnose.

Another thing that i noticed with this issue is that the minimize shortcut doesn't seem to work. In firefox you press Super+H, and the window only disappears if you move the mouse over were the dock is suppose to be (it's in the background at this moment).

**Comment by Blast-City** [comment] 2019-06-13 14:15
More on this issue:
#498

**Comment by lenemter** [comment] 2023-12-13 10:39
Closing because the issue is old and in OS 6 notifications server have been rewritten.

**Closed by lenemter** 2023-12-13 10:39 UTC
Labels: Status: Incomplete
