### ISSUE TITLE
Windows requesting decorations get double decorations

### ISSUE THREAD

**Issue by aggalex** [elementary/gala#244] opened 2018-05-07 06:16 UTC
When I ran PlayOnLinux on elementary OS Juno build I have I noticed gala givesit two decorations: one normally and one around the whole window, including the shadows. It is really ugly, and don't know if it applies to other apps.

![screenshot from 2018-05-07 08 47 22](https://user-images.githubusercontent.com/11951328/39687029-1234b372-51d5-11e8-8ee6-69f544e48644.png)

PS: Tried to see if other apps have the same problem, mainly non GTK3 apps, but the ones I tried (LibreOffice, VLC & "about XFCE4" that I found in the appcenter) don't have such problems. I believe it has to do with the too-small-default-sized window of it, thus making gala think elements go out of it and thus making gala think it needs another decoration for it as a second widget border. You can see how the list widget on the "PlayOnLinux Install menu" overlaps the it's parent window.

![screenshot from 2018-05-07 09 12 44](https://user-images.githubusercontent.com/11951328/39687372-d9335158-51d6-11e8-8300-48aa535d0094.png)

**Comment by davidmhewitt** [comment] 2018-05-07 09:58
I can confirm this, although I'm not sure whether it's a gala issue, a stylesheet issue or an issue with the applications themselves.

The further information I can add is that this seems to affect wxPython applications. For example, you can run the wxPython "Hello, World" application from their website and see the same effect: https://www.wxpython.org/pages/overview/#hello-world

**Comment by aggalex** [comment] 2018-05-07 10:41
Perhaps there is a way to patch it around, after all that problem didn't exist on Loki.

**Comment by lsrzj** [comment] 2018-07-16 17:59
Not only POL, MySQL Workbench too, and with the latest version, I'm using Loki from a clean installation. And it always happen in child windows, not on main windows.

![captura de tela de 2018-07-12 10-56-27](https://user-images.githubusercontent.com/18689770/42774665-a817ecd2-8908-11e8-9bb8-cbb24320fefd.png)

**Comment by davidmhewitt** [comment] 2018-09-24 13:27
Further information on this:
I can also reproduce this issue in Eclipse IDE, only with child windows like the above comment about MySQL workbench.

I've done some testing and ruled out the elementary stylesheet by running both Ubuntu Budgie and Ubuntu GNOME (both 18.04) and using the elementary stylesheet. In these cases, the issue cannot be reproduced. So it's something in the window manager or desktop environment.

The MySQL workbench case is interesting though, as I think that's a native GTK3 app, so I'll have to do a bit more digging into that one and see if there's anything obvious there.

**Comment by apellizcos** [comment] 2018-10-24 17:12
Para cuando una solución?

**Comment by cmcgarry** [comment] 2018-10-26 07:29
I'm seeing this issue with Juno now since recently doing a clean install. Used to run Playonlinux on Loki just fine. Any suggestions?

**Comment by rwoolf** [comment] 2018-10-30 16:07
I'm noticing the same problem with POL and Eclipse on Juno.  It seems there is a high percentage of apps that have this problem.  With POL it makes the app non functional.

**Comment by davidmhewitt** [comment] 2018-10-31 14:09
Found out some more information on this today. The affected applications are requesting extra window decorations via legacy Motif Window Manager hints. It's possible to build a Vala/GTK3 sample that reproduces the issue with the following code:

```
public class Application : Gtk.Window {
	public Application () {
		window_position = Gtk.WindowPosition.CENTER;
		set_default_size (350, 70);

		realize.connect (() => {
			get_window ().set_decorations (Gdk.WMDecoration.ALL);
		});
	}

	public static int main (string[] args) {
		Gtk.init (ref args);

		Application app = new Application ();
		app.show_all ();
		Gtk.main ();
		return 0;
	}
}
```

Still need to figure out why Gala does stuff with these when GNOME shell and Budgie don't.

**Comment by Jiab77** [comment] 2018-11-03 19:54
Same issue using the BOINC Manager Application.

I guess it also use wxPython.

**Comment by Jiab77** [comment] 2018-11-03 19:56
There is another open issue concerning the same problem: https://github.com/elementary/gala/issues/299

**Comment by MichelFrade** [comment] 2018-11-05 12:45
Same issue using Dbeaver 5.2.4, Eclipse and Play on Linux.

**Comment by davidmhewitt** [comment] 2018-11-13 12:33
Some further information:
This does *not* appear to be caused by Gala. The previous testing I've done with GNOME shell and Budgie have been under Ubuntu GNOME and Solus respectively, and windows do not get double decorations there.

However, if you install a GNOME session on elementary (still using the stylesheet and config, etc...), you still get the double decorations. I even installed an unpatched version of mutter and this still happens.

So it would appear that the issue lives in some config or other patched packages rather than Gala itself, as it can be reproduced with vanilla Mutter running on elementary.

**Comment by Jiab77** [comment] 2018-11-13 12:37
@davidmhewitt The issue was also present in the beta versions of Juno. So I think it was introduced again during the development of Juno. I never had this issue while running Loki. Same goes with GNOME Shell as you said, I didn't had this issue too.

**Comment by davidmhewitt** [comment] 2018-11-13 13:08
Okay, found the cause.

There's a shell script (`/etc/profile.d/gtk-csd.sh`) that exports `GTK_CSD=1`.

If you run an application you're having issues with `GTK_CSD=0 name-of-double-decorations-app`, this should resolve the issue. (e.g. `GTK_CSD=0 eclipse`)

I'll have to ask around and see why we have that shell script in elementary, it looks like it was proposed for removal a couple of years back and then put back. So I'll have to see what the effects of removing it are. But this issue can be moved to `default-settings` now.

**Comment by MichelFrade** [comment] 2018-12-05 13:22
Other software I use at work has presented this problem. SmartSVN

![captura de tela de 2018-12-05 11-19-50](https://user-images.githubusercontent.com/16271692/49516120-f503c480-f87f-11e8-98a7-7164b0bd3ec7.png)

**Comment by megatux** [comment] 2018-12-11 15:19
PlayOnLinux, smartsvn, Eclipse, dbeaver are all Java apps and, if I'm not wrong, using the same graphics toolkit, SWT (that uses Gtk+ in Linux). I think the problem lies there.

**Comment by megatux** [comment] 2018-12-11 22:00
Could Gala check if the app is using CSD api? maybe some window property, like the ones listed with `xprop` command?. e.g running dbeaver with & without  `GTK_CSD=0`, respectively,  gives me differences
![captura realizada el 2018-12-11 18 54 15](https://user-images.githubusercontent.com/850020/49832992-f8fb7f00-fd76-11e8-8546-f40bdeffd5e5.png)

**Comment by davidmhewitt** [comment] 2018-12-12 10:33
As I have written above, this is **not** caused by Gala, and trying to do anything in Gala to fix this would be really hacky if not impossible.

Fixing this involves patching GTK.

In vanilla GNOME, dialogs are coded to have CSD by default because they want put the action buttons in the headerbar (e.g. in the save dialog, the save button is in the top right of the window, in the titlebar). However, when you change the GTK setting that stops them from being in the headerbar (because this doesn't meet elementary UI guidelines), dialog windows become server side decorated by default, this is hardcoded into GTK.

So, to enforce CSD on dialogs, elementary exports `GTK_CSD=1` in the session, and either GTK or Mutter doesn't handle this well.

**Comment by megatux** [comment] 2018-12-13 03:41
I'm not sure if I follow you but if there is no way to have both apps with AND without CSD at the same time, for the same GTK 3.x version then I think it's a bug that should be fixed. I assume there is an open GTK issue for this.

**Comment by aggalex** [comment] 2019-01-05 15:05
May I suggest a very rough patch?
Till Gtk fixes their issue, elementary could make something like a list for apps prone to this problem,

**Comment by aggalex** [comment] 2019-01-05 15:08
Oops my fault for closing the issue... sorry...

**Comment by kkinder** [comment] 2019-01-21 16:18
> There's a shell script (`/etc/profile.d/gtk-csd.sh`) that exports `GTK_CSD=1`. I would highly recommend not deleting this shell script as it makes all of the dialog boxes look a bit weird and breaks the open file/folder dialog in some cases.

It still seems to me the solution should be deleting `/etc/profile.d/gtk-csd.sh` while patching whatever depends on that environment variable being set to not.

**Comment by bilelmoussaoui** [comment] 2019-01-21 18:54
That's probably the proper solution to this issue https://github.com/elementary/stylesheet/issues/468 (Haven't tried it).

**Comment by SyntevoAlex** [comment] 2019-02-27 15:52
Related SWT issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=542451

**Comment by SyntevoAlex** [comment] 2019-02-27 16:14
For reference, here's a GTK snippet written in C that shows the problem:

```
#include <gtk/gtk.h>

int main (int argc, char* argv[])
{
	gtk_init (&argc, &argv);

	// With 0, it works fine.
	// With 1, a "ghost" window appears around the expected window. 
	printf("GTK_CSD=%s\n", g_getenv("GTK_CSD"));

	GtkWidget* shellHandle = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	gtk_widget_show(shellHandle);
	g_signal_connect(shellHandle, "destroy", G_CALLBACK(gtk_main_quit), NULL);

	GdkWindow* gdkResource = gtk_widget_get_window(shellHandle);
	gdk_window_set_decorations (gdkResource, GDK_DECOR_MINIMIZE);

	gtk_main();
	return 0;
}
```

This is a very reduced code similar to what SWT does.
The same problem is seen on Ubuntu with `export GTK_CSD=1`

**Comment by ericwill** [comment] 2019-02-27 16:39
Hi, SWT-GTK maintainer here.

The reason we set this flag is that SWT supports various different style bit combinations for our Shells. The SWT style bits map to the GDK ones and then we set them via `gdk_window_set_decorations()`.

Now, I am wondering why GTK_CSD=1 is causing the problem here, because the [GTK docs](https://developer.gnome.org/gtk3/stable/gtk-running.html) state:

> The default value of this environment variable is 1. If changed to 0, this disables the default use of client-side decorations on GTK+ windows, thus making the window manager responsible for drawing the decorations of windows that do not have a custom titlebar widget. CSD is always used for windows with a custom titlebar widget set, as the WM should not draw another titlebar or other decorations around the custom one. 

If GTK_CSD is 1 by default, elementaryOS setting it in that script shouldn't cause any different behaviour. Is it possible this is a theming related issue as suggested a few comments above? Is it reproducible when running the Adwaita theme (default GTK theme shipped with GTK)? I am going to try and reproduce the issue on my Fedora 29 box with GNOME and export GTK_CSD=1.

**Comment by ericwill** [comment] 2019-02-27 17:05
I can confirm the issue does not reproduce natively using GNOME, Fedora 29, with both the Adwaita and Clearlooks-phenix themes. GTK_CSD=1 or GTK_CSD=0 makes no difference.

**Comment by SyntevoAlex** [comment] 2019-02-27 19:47
Reproducible on Fedora if you also `export GDK_BACKEND=x11`.

**Comment by ericwill** [comment] 2019-02-27 20:15
Ah yes I forgot to mention I am on Wayland.

**Comment by kapildverma** [comment] 2019-03-10 06:25
Any update about fix for this issue? I am facing the same issue with Eclipse on Elementary Juno:

![image](https://user-images.githubusercontent.com/7228801/54081471-015a4c00-42cb-11e9-864f-953abdd77e1d.png)

**Comment by SyntevoAlex** [comment] 2019-03-11 09:21
I fixed the problem in SWT: https://bugs.eclipse.org/bugs/show_bug.cgi?id=542451
Should be released with next Eclipse version.

**Comment by novusabeo** [comment] 2019-03-13 08:02
Having this same issue. I see there is a workaround but I'm not exactly sure how to go about it --- makes certain "non-curated" apps unusable for me.

**Comment by echavez2623** [comment] 2019-04-24 14:13
Pueden crear un script y pegarlo en /usr/share/playpnlinux/run.sh que contenga: 

Exex=env GTK_CSD=0 /usr/share/playonlinux/playonlinux

Solo desactivan en su gestor de menús que no abra la terminal.

**Comment by ajkr196** [comment] 2019-05-03 11:49
Can we expect fix for this in the near future update? Or it will be released in next version? In 6?

**Comment by a-tokarev** [comment] 2019-05-13 07:13
I have this issue in DisplayCAL calibration software. I have [Reported](https://hub.displaycal.net/issue/17331/#comment-718) it to the developer. His reply was:
--
_Hi,
not fixable by me:_

```
#!/usr/bin/env python2
import wx
app = wx.App(0)
f = wx.Frame(None)
f.Show()
app.MainLoop()
```

_Please report upstream to python-wxgtk3.0 package._

**Comment by ajkr195** [comment] 2019-05-21 20:26
So there is no possibility of its fix with regular updates?

**Comment by joe247** [comment] 2019-06-04 11:13
> Thanks @davidmhewitt for the workaround
> For those wondering how to change the .desktop file appropriately, set:
> `Exec=env GTK_CSD=0 <executable path>`
> For example for Eclipse I did this:
> `Exec=env GTK_CSD=0 /opt/eclipse/eclipse`

Worked in eOS 5.0 Juno

PlayOnLinux Modified Desktop Entry

`[Desktop Entry]`
`Version=1.0`
`Name=PlayOnLinux`
`Comment=Front-end application for the wine`
`Type=Application`
`Exec=env GTK_CSD=0 playonlinux %F`
`Icon=playonlinux`
`Categories=Utility;Emulator;`

**Comment by cmcgarry** [comment] 2019-06-05 22:35
This works for me as well. Finally, PlayOnLinux without the extra window. 

Thank you!

> > Thanks @davidmhewitt for the workaround
> > For those wondering how to change the .desktop file appropriately, set:
> > `Exec=env GTK_CSD=0 <executable path>`
> > For example for Eclipse I did this:
> > `Exec=env GTK_CSD=0 /opt/eclipse/eclipse`
> 
> Worked in eOS 5.0 Juno
> 
> PlayOnLinux Modified Desktop Entry
> 
> `[Desktop Entry]`
> `Version=1.0`
> `Name=PlayOnLinux`
> `Comment=Front-end application for the wine`
> `Type=Application`
> `Exec=env GTK_CSD=0 playonlinux %F`
> `Icon=playonlinux`
> `Categories=Utility;Emulator;`

**Comment by Akryum** [comment] 2019-07-19 09:03
Just to report it's still an issue on DBeaver, making it unusable (some buttons on dialogs are hidden no matter the size of the window).

**Comment by aggalex** [comment] 2019-07-19 11:09
@Akryum you can use the suggested workaround:

**Comment by Akryum** [comment] 2019-07-19 11:19
Yeah I did that, but still just a workaround :(

**Comment by aggalex** [comment] 2019-07-19 11:24
@Akryum better than nothing. Bear with, it at least for now. I've done this with POL, and didn't have to do anything else ever since, so I don't think it's such an annoying workaround.

**Comment by Akryum** [comment] 2019-07-26 10:25
It's pretty annoying, since I have to do it again every time I update DBeaver :sweat:

**Comment by Akryum** [comment] 2019-07-26 10:30
I have just hit another issue: with the `env GTK_CSD=0` workaround, DBeaver can't open System's File select dialog. For example, I tried executing a huge SQL script on a database:

![Screenshot from 2019-07-26 12-27-21](https://user-images.githubusercontent.com/2798204/61945632-c4080980-afa0-11e9-928f-0730c1a9ae63.png)

The folder icon does nothing when I add `env GTK_CSD=0` to launch DBeaver, but it opens the file select dialog when I don't use the workaround -- the DBeaver dialog still being unusable because the action buttons are below the visible area of the dialog.

Is there anything else I can try?

**Comment by amrit9193** [comment] 2019-12-23 07:26
I am not a developer, just a regular user using Hera recently upgraded from Juno. I am seeing this problem for **Veracrypt** and **Youtube-dl-gui**. Both these program show the following when started form terminal.

***** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug**

\I have also recently used pop OS! and this problem doesn't appear there.

**Comment by Khomyak-sibiryak** [comment] 2020-03-20 04:05
I am experiencing the same problem when using **veracrypt** as in the comment above. Has anyone been able to solve this problem?

**Closed** 2021-01-29 08:45 UTC
Labels: Priority: Low, Status: Confirmed

**Comment by cmburg** [comment] 2021-10-21 01:38
Problem exists in elementary os 5.1.7 with both kicad 4 from the std-source and 5.1 from the kicad ppa.
```BASH
e@e-ThinkPad-T430:~$ kicad
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

e@e-ThinkPad-T430:~$ 

```
