### ISSUE TITLE
Alt-tab is not accessible with Orca

### ISSUE THREAD

**Issue by ethindp** [elementary/gala#1876] opened 2024-03-10 02:50 UTC
### What Happened?

I'm using Elementary OS 7.1. When alt-tabbing, Orca does not read open windows/tasks. This is a pretty significant inconvenience since I have to let the window focus, then alt-tab again, and repeat ad infinitum until I find what I'm looking for, and given the alt-tab order changes whenever you focus an application... You can see the problem.

### Steps to Reproduce

Set up accessibility via alt-super-S.

### Expected Behavior

Focused applications are not read by Orca when in the alt-tab view. It is expected that Orca would read the opened windows that you "hover" over before focusing them.

### OS Version

7.x (Horus)

### Software Version

Older release (I have not run all updates)

### Hardware Info

Standard System76 Lemur Pro 10.

**Comment by lenemter** [comment] 2024-04-29 09:35
Thanks you for your report. This issue is a duplicate of https://github.com/elementary/gala/issues/1301 so I'll close this one.

**Closed by lenemter** 2024-04-29 09:35 UTC
