### ISSUE TITLE
memory leaking 

### ISSUE THREAD

**Issue by avstarovoitov** [elementary/gala#1271] opened 2021-10-13 20:56 UTC
### What Happened?

When the "Show all windows" option is enabled in Desktop -> Multitasking (for the upper left corner of the screen), a memory leak occurs. My laptop has 16GB of RAM and this is enough for only 4-5 hours of work, then the swap is actively used. Closing all programs does not help. The only solution is to log out and log back in. Moreover, the bug manifests itself only with the active use of this feature.

### Steps to Reproduce

1. Go to System setting --> Desktop --> Multitasking and set up "Show all windows"  for the upper left corner
2. Use this functionality while working 

### Expected Behavior

In a few hours all the RAM will be used up. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
no warning
```

### Hardware Info

System Information
        Manufacturer: Dell Inc.
        Product Name: Inspiron 13-5378

**Comment by avstarovoitov** [comment] 2021-10-16 14:46
Hi, I switched from "Show all windows" to "Multitasking view" and there is no memory leak in this version

**Comment by lenemter** [comment] 2023-02-10 10:17
Closing because cannot reproduce in OS 7.

**Comment by lenemter** [comment] 2024-07-10 10:12
I can confirm there is memory leak in window spread.

**Closed** 2024-07-10 10:21 UTC
Labels: Status: Confirmed
