### ISSUE TITLE
Low fps overview animation

### ISSUE THREAD

**Issue by adnan449** [elementary/gala#1204] opened 2021-08-12 11:16 UTC
## What Happened

After selecting an app from the overview mode, the animation to bring up the selected app is very laggy.

## Expected Behavior

Smooth animation

## Steps to Reproduce

1. Trigger the overview mode
2. Select an app
3. See the What Happened section

## Platform Information

* The version of elementary OS you are using, or other operating system

6.0

* The version of the software you are using such as "1.0", "Compiled from git", or "Latest release" if you're not sure but you have run updates

Gala 6.0.1

* Relevant hardware information such as graphics drivers, unconventional setups, etc.

AMD Navi 10 RX 5700XT.

[Sreencast](https://streamable.com/lrhtqt)

**Comment by validatedev** [comment] 2021-08-12 11:54
Duplicate of https://github.com/elementary/gala/issues/1190

**Comment by okitoxo** [comment] 2021-08-14 00:13
This would be main issue, older issues were in daily build or 5.x #1136 and #1190 
I have the same problem in Odin Stable and AMD RX 570.

**Comment by validatedev** [comment] 2021-08-14 23:35
It seems it is still the duplicate of https://github.com/elementary/gala/issues/1190 and my https://github.com/elementary/gala/issues/1190 is actually the duplicate of https://github.com/elementary/gala/issues/1136, but I do not want to close my issue because: 
1. The title of https://github.com/elementary/gala/issues/1136 is not updated.
2. I also proposed a solution on https://github.com/elementary/gala/issues/1190 and updated the explanation accordingly.
3. https://github.com/elementary/gala/issues/1204 and https://github.com/elementary/gala/issues/1190 are actually the same issues.

I will immediately close my issue after the original issue is structured properly. Thanks for noticing the older issue!

**Comment by lenemter** [comment] 2022-12-23 15:07
Closing as duplicate of #1136

**Closed by lenemter** 2022-12-23 15:07 UTC
