### ISSUE TITLE
Applications can't be dragged between screens on vertical arrangement

### ISSUE THREAD

**Issue by AlexFBP** [elementary/gala#252] opened 2018-05-17 21:10 UTC
I can't drag applications between screens if the disposition that appears in (Switchboard Display Plug) is  vertical. In horizontal, works as expected.
![image](https://user-images.githubusercontent.com/6588872/40192366-b96d44be-59c9-11e8-845b-e2c2c06df213.png)
With this setup, the mouse moves naturally between screens as my phisical distribution, but i can't grab a window from their title bar and move to the external monitor, this only allows me to maximize it (as i have to move it to the edge of my lower monitor). The closer attempt is when i use the multitask viewer, it in fact let me drag to up, a window, but when i release the mouse button, the window dissapears, like getting killed.
![image](https://user-images.githubusercontent.com/6588872/40192726-ca9106d0-59ca-11e8-9ad3-b888afef14a7.png)

Now that i see this screen capture while i wrote this issue, i see two things:
- the identifiers of both monitors, appears in the same monitor, instead of being in every one
- the window dragged by the multitask viewer method, in fact is appearing only on the screen capture, but not phisically.

Both things are noted in the left bottom corner of the last capture, trimmed here:
![image](https://user-images.githubusercontent.com/6588872/40203746-d0364f7a-59eb-11e8-8641-5358ee8772ed.png)
In the integrated screen i only see the browser and the monitor identifier red, but starting from "ard 19" "

**Comment by AlexFBP** [comment] 2018-05-17 21:18
If i move sligthly the screens (but keeping external at top), now the identifiers appears on every screen, but still i can't drag a window from the bottom screen

![image](https://user-images.githubusercontent.com/6588872/40204329-c9398050-59ed-11e8-8740-81508113fa36.png)

**Comment by cassidyjames** [comment] 2018-05-17 21:57
Thanks for the documenting and screenshots! If you switch the top display to be primary, does it work as you'd expect? I think this is a duplicate of #7.

**Closed** 2018-05-17 22:07 UTC
Labels: Status: Duplicate

**Comment by AlexFBP** [comment] 2018-05-18 00:07
Yes, it works, but instead of this, I conserved the integrated screen as main, I only swapped the disposition of screens in (Switchboard Display Plug).

I was looking for a similar bug but apparently failed, so i made this one... Anyways , Yes, workaround confirmed for issue #7, and the issue by itself.
