### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [elementary/gala#543] opened 2019-06-01 23:53 UTC
I think that it would be good to make new release with updated code base :)

**Comment by peteruithoven** [comment] 2019-06-02 07:35
I realize this repo doesn't use releases, which is a shame but the last release was 2019-05-16, see: https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+packages?field.name_filter=gala&field.status_filter=published&field.series_filter=bionic
Looking at the commits there was only one bug fix since then, and that was only merged yesterday: https://github.com/elementary/gala/commits/master
We usually don't release code with such recent changes.

**Comment by decathorpe** [comment] 2019-06-02 09:53
@peteruithoven that's not a release, that's a git snapshot build.

**Comment by kloczek** [comment] 2019-06-02 18:39
It would be really good to start making regiular releases :)

**Comment by worldofpeace** [comment] 2019-06-12 03:06
I also noticed this in https://github.com/elementary/gala/issues/393.

**Comment by danrabbit** [comment] 2019-12-12 00:28
Closing as a duplicate of #25

**Closed by danrabbit** 2019-12-12 00:28 UTC
