### ISSUE TITLE
The window switcher is confusing with non full screen apps (large screens)

### ISSUE THREAD

**Issue by dimitrov-adrian** [elementary/gala#64] opened 2017-08-30 13:41 UTC
I would like to suggest including option to switch to non-animated window switcher like the standard one of  GNOME, macOS and Windows. I found the behavior in elementary very confusing and after week work with Elementary, I still can't adopt it.

**Comment by peteruithoven** [comment] 2017-08-30 13:51
Work is done to improve the ux: https://github.com/elementary/gala/issues/52
A pull request that made  more things customizable was rejected: https://github.com/elementary/gala/pull/33

**Comment by matzipan** [comment] 2017-08-30 18:50
As per the [elementary OS Human Interface Guidelines](https://elementary.io/docs/human-interface-guidelines#avoid-configuration) we prefer to avoid configuration in. Instead, we make design decisions. 

Is there an issue you're having? What are you finding confusing?

**Comment by matzipan** [comment] 2017-08-30 18:51
Marked as incomplete as your initial description, "very confusing", is not very descriptive. Will remove once more details are given.

**Comment by dimitrov-adrian** [comment] 2017-08-31 09:55
Well, in elementary OS there is configuration to make the docker be on left (like in my case) so there are some configuration. I found confusing the way of the behavior, because I prefer to work with not maximized all the time app windows, and while switching bringing current selected to front and hiding others is confusing for me because loosing which are is my current active window. Also the docker is transformed to something like the standards switcher but it's placed (in my case on left) so I should move my view to the left side of the display.

I will not talk about the complete miss of way to navigate with keyboards while holding ALT+TAB no way to select with arrow keys and even on the exposed view.

**Comment by nkkollaw** [comment] 2017-11-11 14:48
@matzipan , I'm not sure the title is correct the way you changed it. I'm not sure "with non full screen apps (large screens)" has anything to do with it.

I just created #123, which has something to do with this.

I completely agree with both @dimitrov-adrian in what he said, and you that configuration is not the answer. In this case it just needs to be improved from an usability point of view. Honestly, I would just follow what all other OSes are doing, because it's a pretty established UI element and it's going to be hard to find a more intuitive solution than what everyone's used to.

**Comment by danrabbit** [comment] 2019-12-11 23:47
I'm going to close this as a duplicate of #72 since that's kind of where we're discussing design changes for Alt+Tab

**Closed by danrabbit** 2019-12-11 23:47 UTC
