### ISSUE TITLE
Make Window Switcher accessible

### ISSUE THREAD

**Issue by aral** [elementary/gala#1301] opened 2021-11-08 16:33 UTC
### What Happened?

Last week [Catts](https://github.com/small-tech/catts) was brought in-tree to gala as the default Window Switcher.

However, it is entirely inaccessible.

(e.g., for a person who uses a screen-reader, it does not exist at all)

I was able to cobble together some basic accessibility for Catts from whatever scant documentation and code I could find on the subject in the GNOME/Gtk/Vala/elementary OS worlds and, while it is better than nothing, it should be possible to improve it.

I hope that someone with the necesary knowledge can help with this and also share their knowledge to teach other developers both on the elementary OS core team and those making apps for the operating system how to create accessible widgets by default.

I’m opening this issue as per @cassidyjames’s request that [making the widget accessible should be tracked in a separate issue](https://github.com/elementary/gala/pull/1234#issuecomment-930397772).

Related: https://github.com/elementary/hig/discussions/51

### Steps to Reproduce

1. Use the Window Switcher with the screen reader

Nothing is heard.

### Expected Behavior

The Window Switcher should be accessible.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

n/a

**Comment by Tireg** [comment] 2022-04-25 20:32
Probably a duplicate of #1326 (all Mutter version impacted since Mutter 40)

**Comment by danirabbit** [comment] 2024-05-28 19:04
I wonder if we should make this UI element into a GTK subprocess like we've done with some other shell elements. That would give us a11y for basically free and we could remove a lot of custom drawing

**Closed** 2024-08-20 19:59 UTC
Labels: Status: Confirmed, Priority: High
