### ISSUE TITLE
Keyboard shortcuts to switch workspaces should work when Expose is open

### ISSUE THREAD

**Issue by marcinjahn** [elementary/gala#1172] opened 2021-07-01 07:34 UTC
I think that it makes sense to allow to use the shortcuts to switch to the next/previous workspace (and any other workspace-related shortcuts) while the workspaces view (Expose?) is open.
In my case, I have the bottom-right corner of the screen bound to open the Expose. It's easier for me to open it that way than clicking START+UP. However, switching the workspace is easier/faster with START+TAB than with the mouse.

**Comment by lenemter** [comment] 2023-02-11 13:23
Duplicate of #24 which has already been fixed.

**Closed by lenemter** 2023-02-11 13:23 UTC
