### ISSUE TITLE
App switching view is not intuitive

### ISSUE THREAD

**Issue by mshafat** [elementary/gala#867] opened 2020-07-07 18:38 UTC
When I click alt+tab I find it difficult to switch to my desired app with the default view of elementary. By default it only highlights the app that I'm on. It is very unintuitive. Please change it and make it human friendly. It is needed to see all the running apps side by side and the most recent two apps near one another. In current system I always have to see below the icon to locate how many tabs I have to click in order to go to my desired app icon. But when I focus on Icon I can hardly focus on the highlighted view. In windows and gnome desktops they show running apps overviews. Elementary OS also show overview then I go to multitasking view. For app switching view the same types of running apps overview is necessary. Please change the system.

**Comment by danrabbit** [comment] 2020-07-07 18:42
Closing as a duplicate of #72

**Closed by danrabbit** 2020-07-07 18:42 UTC
