### ISSUE TITLE
Plank is cut when using touchpad gestures

### ISSUE THREAD

**Issue by Richardsause** [elementary/gala#1333] opened 2021-12-03 01:29 UTC
### What Happened?

![IMG_20211202_221258](https://user-images.githubusercontent.com/89277764/144528709-69d1996d-eb56-4802-b895-5f567b22e747.jpg)
When you are in the middle of a 1:1 workspace switching gesture, if you look at plank you can see it gets some parts cut off, also the part that is cut changes with the gesture, its size is not always the same

### Steps to Reproduce

~~try switching workspaces via touchpad gestures and take a loot at plank~~
at least for me, it happens only when you have a fullscreen window open the workspace you're alternating from

### Expected Behavior

it should be normal

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Some specs :
11th gen Intel core I3-1115G4
intel UHD graphics (TGL G52) also 11th gen
I have uninstalled intel's xorg driver as i find xorg's mode setting more reliable, but issues like this one still persist on both

**Comment by lenemter** [comment] 2023-02-10 01:18
Closing as duplicate of #1287.

**Closed by lenemter** 2023-02-10 01:18 UTC
