### ISSUE TITLE
PiP: Shadow is too heavy when grabbing portion outside of window

### ISSUE THREAD

**Issue by worldofpeace** [elementary/gala#646] opened 2019-12-02 04:13 UTC
## Describe the bug
I personally think the shadow effect for windows in PIP could look better, or a different effect could be used for a better result.
In some cases, depending on window sizes, it appears the effect can devolve into a distorted looking shadow and gradient which isn't so great.

### Screenshots or screen recordings
Here's a screenshot where PIP has captured a portion of a terminal window.
I have them side by side to demonstrate the transparent shadow.
![Screenshot from 2019-12-01 22-57-00](https://user-images.githubusercontent.com/28888242/69929745-2d87af80-148e-11ea-92d8-8fe4f5c8d48a.png)

### Platform Info
OS: NixOS
OS Version: 20.03 Markhor (dev)
Gtk: 3.24.12
Mutter: 3.34.1 and 3.28.4
Gala: Latest off master

**Comment by cassidyjames** [comment] 2019-12-02 04:50
I have never seen this on elementary OS; I assume it is an issue with the GTK version, Mutter version, or something?

**Comment by worldofpeace** [comment] 2019-12-02 17:37
I'll also note that the capture is just a portion of the window to demonstrate the shadow.
Could you upload a screenshot from elementary OS?

I can upload some more here as well.

When I first noticed this I thought it was a bug because I was testing mutter 3.34, but I was able to reproduce it even before that. I found some reference videos of Pantheon on elementary OS and it seems to be the same shadow. I've updated the issue with that info.

**Comment by worldofpeace** [comment] 2019-12-02 17:49
Ok, so I don't think there's a visual difference with mutter 3.34. Though in all the screenshots it's using gtk 3.34.1.

Mutter 3.28.4 with a captured portion and a captured window.
![Screenshot from 2019-12-02 12 42 51](https://user-images.githubusercontent.com/28888242/69982196-df13f880-1501-11ea-9b86-f13d5b9d0dee.png)

Mutter 3.34.1 with a captured portion and a captured window.
![Screenshot from 2019-12-02 12 45 18](https://user-images.githubusercontent.com/28888242/69982257-010d7b00-1502-11ea-9023-0ff72555f2a5.png)

Not high accuracy because the window dimensions are different between the captures.

**Comment by worldofpeace** [comment] 2019-12-02 18:39
Built an elementary OS ISO with the same setup.
![Screenshot from 2019-12-02 13 38 27](https://user-images.githubusercontent.com/28888242/69985433-25208a80-1509-11ea-9fde-933a7e27cf92.png)

**Comment by cassidyjames** [comment] 2019-12-02 18:47
@worldofpeace ah I see now, yes I can actually reproduce that when grabbing a portion from outside of the window. My bad, I've never actually tried that before. :sweat_smile:

**Comment by worldofpeace** [comment] 2019-12-02 23:55
> @worldofpeace ah I see now, yes I can actually reproduce that when grabbing a portion from outside of the window. My bad, I've never actually tried that before. sweat_smile

Well at least there's an agreement on something :smile:.

My initial thoughts were that shadow effect is out of place in general.
Aesthetically, I don't think the PiP overlay needs to look different than any other window (extra shadow), because overlays in Pantheon are just not like this. (shadows on normal windows in Pantheon are looking great).

**Comment by cassidyjames** [comment] 2019-12-02 23:59
yeah it definitely looks like a bug

**Comment by danirabbit** [comment] 2023-04-04 19:19
Seems to be fixed in OS 7 both for CSD and SSD windows

![Screenshot from 2023-04-04 12 18 39](https://user-images.githubusercontent.com/7277719/229897702-9efdd936-c711-4258-b2ce-fb52bf353324.png)

**Closed by danirabbit** 2023-04-04 19:19 UTC
Labels: Status: Confirmed, Priority: Low
