### ISSUE TITLE
Header context menu on not-native apps

### ISSUE THREAD

**Issue by Djaler** [elementary/gala#174] opened 2018-02-14 20:02 UTC
In native apps we can open header context menu with some useful options like "Always on top". But with another apps we can't. Looks like this is only for GTK3 apps. But I remember that earlier, in previous version of elementary, we can do it with any app.

**Comment by artemanufrij** [comment] 2018-02-14 20:33
@Djaler It's also possible on third party apps...

![bildschirmfoto von 2018-02-14 21 32 58](https://user-images.githubusercontent.com/16517095/36226633-ab5459c8-11ce-11e8-94c8-03f28a0c0814.png)

**Comment by peteruithoven** [comment] 2018-02-14 21:15
@artemanufrij That app (GraphUI) is also made with GTK-3: 
https://github.com/artemanufrij/graphui/blob/master/CMakeLists.txt#L20

Examples would be Chromium and Electron based apps like Atom and Gitkraken.

**Comment by apcamargo** [comment] 2018-02-26 13:23
I can confirm that this happens to me in Firefox. This should be related with the fact that the title bar doesn't appear in screenshots.

![screenshot from 2018-02-26 10 20 44](https://user-images.githubusercontent.com/22940964/36672685-ff8c6ecc-1ade-11e8-96c9-a1fc37ed9845.png)

**Comment by ChristopherRogers1991** [comment] 2018-06-24 22:13
Just wanted to note that this also effects the menu button that can be added via dconf:

![image](https://user-images.githubusercontent.com/8608191/41824136-89b4e1cc-77d9-11e8-97a8-01bdff6b609c.png)

Repro:

1) With dconf, set org > pantheon > desktop > gala > appearance : button layout to: `close, menu:maximize`.
2) Open an non-gtk application (I've tested with Firefox and VLC)
3) Click the menu button

Expected behavior:

The window menu is displayed

Actual Behavior:

The menu is not displayed; pressing the button has no effect.

**Comment by danrabbit** [comment] 2018-09-17 22:03
Closing because this was fixed in #179

**Comment by cassidyjames** [comment] 2018-09-20 16:06
Reopening because apparently this wasn't ever fixed in #179, and #338 was opened as a dupe.

**Comment by jlnr** [comment] 2018-09-20 17:57
I've created a new virtual Juno installation with all the latest daily stuff, installed VirtualBox in the live session (it's a common non-GTK app), and right-clicked the VirtualBox title bar. No menu, but a new journal entry with every click:

![screenshot von 2018-09-20 19 53 51](https://user-images.githubusercontent.com/70772/45837230-25bb6f80-bd0f-11e8-9840-892587e28d52.png)

Not sure how to debug the daemon.

**Comment by cassidyjames** [comment] 2018-10-24 22:12
It appears Juno stable no longer has menus at all, on native or legacy decorations. I can open a new issue, but I'm not sure if this (or #339) is related.

**Comment by janxkoci** [comment] 2018-11-27 19:36
Actually I now found I don't have any context menus anywhere on headerbars nor titlebars, I have no idea why :O I'm super-puzzled now.

Edit: aha, I don't have them anywhere, even if i right-click on this page - so probably different problem..? Weird regardless

**Comment by nkkollaw** [comment] 2019-03-26 13:38
Hello, I'm also getting no menus at all in any app.
I am however using Gala on Xfce instead of Pantheon.
Any idea how I can fix this..?
Thanks!!

**Comment by janxkoci** [comment] 2019-03-27 13:07
Are you up to date? For me it solved itself after some reboots and/or updates.

**Comment by nkkollaw** [comment] 2019-03-27 14:08
Yup, I'm building from master on GitHub.

**Comment by cassidyjames** [comment] 2019-04-12 02:06
I am no longer able to reproduce this on a fresh Juno install, on loDPI or HiDPI. Is anyone else still seeing this in Juno? :grimacing: 

@nkkollaw if that's _all_ context menus—not just ones in titlebars/headerbars—then it would be a separate issue. Please file it so the developers can see it and take a look.

**Comment by janxkoci** [comment] 2019-04-15 11:27
I have titlebar menus everywhere just fine, even GTK2, snaps, flatpaks, all work.

**Comment by nkkollaw** [comment] 2019-04-15 12:33
Lucky you!

**Comment by danrabbit** [comment] 2019-12-11 23:51
This should be fixed again

**Closed by danrabbit** 2019-12-11 23:51 UTC

**Comment by sprite-1** [comment] 2019-12-13 10:22
> This should be fixed again

Has the fix been pushed in a prior update or is it yet to be released?
