### ISSUE TITLE
Gala forgets last window size for an application

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#473] opened 2019-02-27 09:01 UTC
Gala forgets application window size on every open.
1. This is Files app tiled to the left.
![screenshot from 2019-02-27 07-15-04](https://user-images.githubusercontent.com/22585732/53478034-f10cca80-3a9b-11e9-9b97-dee50d620442.png)

2. This is Files app closed and opened again.
![screenshot from 2019-02-27 07-15-09](https://user-images.githubusercontent.com/22585732/53478063-01bd4080-3a9c-11e9-94ca-a77a9b165991.png)

For someone who relies on the Files app heavily for day-to-day work, this bug is kind of annoying. :)

**Comment by peteruithoven** [comment] 2019-02-27 09:20
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/308
Relevant: https://github.com/elementary/granite/issues/224

**Closed by peteruithoven** 2019-02-27 09:20 UTC
Labels: Status: Duplicate
