### ISSUE TITLE
Black after resume

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/gala#1162] opened 2021-06-08 18:01 UTC
## What Happened
After resuming from sleep, the screen goes black after logging in. The mouse cursor is still visible and the workspace switcher appears when using the touchpad gesture, but the screen is otherwise black. This was happening infrequently under Hera, but now it's nearly every time I resume. It also seems to be a recent thing. It happened infrequently prior to recently under Odin as well.

## Expected Behavior
Screen should return normally after resume and login.

## Steps to Reproduce

1. Close laptop lid
2. Computer sleeps
3. Open lid
4. Login
5. See black screen

## Platform Information

Odin

**Comment by candiedoperation** [comment] 2021-06-09 01:00
Duplicate of https://github.com/elementary/gala/issues/1126

**Closed** 2021-08-13 13:14 UTC
