### ISSUE TITLE
Lock screen rotation

### ISSUE THREAD

**Issue by eliocamp** [elementary/gala#374] opened 2018-10-20 15:59 UTC
I'm testing Juno (congratulations!) on an USB before upgrading from Loki and found a breaking bug. My laptop has an accelerometer that is used to infer if it's on a flat surface or on my lap and change some cooling settings. Juno (and also Gnome Shell) detects it but get confused and thinks it's a tablet that is rotating and randomly rotates my screen. In Gnome Shell there's an obvious button to lock screen orientation but I see no toggle in elementary OS.

**Comment by peteruithoven** [comment] 2018-10-20 16:08
Thanks for the report! This is probably a duplicate of: https://github.com/elementary/switchboard-plug-display/issues/116

**Closed by peteruithoven** 2018-10-20 16:08 UTC

**Comment by dracinn** [comment] 2018-11-27 16:54
Happening on HP Beats computer as well with no accelerometer, hope it gets fixed soon had to disable desktop rotation myself.

**Comment by junk33e53** [comment] 2019-02-09 15:35
i have an asus VivoBook-Flip-14-ASUS-Flip-TP412UA. the desktop its ok but the login screen is rotated by 90 degrees clockwise

**Comment by peteruithoven** [comment] 2019-02-09 15:48
@junk33e53 why respond to this issue? 

I assume that laptop does have a touchscreen? So you an lock the rotation in System Settings? (On laptops without touchscreens the option is currently not shown see: https://github.com/elementary/switchboard-plug-display/issues/116)

Or is the issue that this setting is ignored in the login screen, in which case there is this issue: https://github.com/elementary/greeter/issues/216
