### ISSUE TITLE
empty workspaces do not get removed

### ISSUE THREAD

**Issue by btkostner** [elementary/gala#282] opened 2018-07-02 18:24 UTC
![screenshot from 2018-07-02 12 22 49](https://user-images.githubusercontent.com/3385679/42179999-d0fb61c2-7df2-11e8-8c8a-4856ef02e47c.png)

```
gala/bionic,now 0.3.1~r658+pkg44~daily~ubuntu5.0.1 amd64 [installed,automatic]
```

**Comment by lenemter** [comment] 2023-08-27 08:37
Closing because the issue is old and no irreproducible.

**Closed by lenemter** 2023-08-27 08:37 UTC
