### ISSUE TITLE
Weird crashes of Window Manager

### ISSUE THREAD

**Issue by mjwhodur** [elementary/gala#217] opened 2018-03-29 09:32 UTC
Hello,
I've been using elementary OS for quite a long time. However I have sometimes experienced weird crashes of Window Manager and saw that gala is using extensive amount of CPU or memory. I was primarily seeing it using IntelliJ PyCharm or IDEA. 

Are there any options for optimizations of gala or other parts of OS?
Currently, I have no idea how can I reproduce the problem, it seems pretty random. Sometimes it happened while using browser. Sometimes my computer was on for few days and the problem didn't occur... I've been using it on my ThinkPad T420, Dell Venue Pro 11 and iMac. iMac seemed most stable platform.

**Comment by lenemter** [comment] 2023-08-27 08:20
Closing because the issue is old and doesn't describe any particular issue in sufficient details.

**Closed by lenemter** 2023-08-27 08:20 UTC
