### ISSUE TITLE
multi screen with independant workspace

### ISSUE THREAD

**Issue by u007** [elementary/gala#643] opened 2019-11-23 19:34 UTC
o/s: elementary OS 5.0 Juno

hi, is it possible to have independent workspace for each monitor/screen?
right now the workspace is shared between two screen

**Comment by megatux** [comment] 2020-06-09 14:40
Right, only the primary display has workspaces. The others don't. Is this feature planned?

**Comment by lenemter** [comment] 2023-10-30 05:03
Closing as duplicate of #26

**Closed by lenemter** 2023-10-30 05:03 UTC
