### ISSUE TITLE
Visual glitches after waking up from suspend

### ISSUE THREAD

**Issue by Alecaddd** [elementary/gala#344] opened 2018-09-24 02:02 UTC
Using Juno Beta 2

To reproduce:

1. Use a HiDPI display
2. Let the computer go to sleep or suspend it, and wait for the monitor to go dark
3. Press a button wake up the computer

Issues in Greeter: The user/password field is usually covered by a noise patch like the area wasn't rendered properly. Clicking on the area makes it appear but the noise patch remains on top of the user's profile icon.

Issues in Vala: When activating the multitasking view, the background behind the workspaces presents the same noise texture.

![gala](https://user-images.githubusercontent.com/2527103/45935726-1c2a4580-bf63-11e8-8460-ba0330eed015.png)

I wasn't able to take a screenshot of the Greeter

**Comment by cassidyjames** [comment] 2018-09-24 04:50
@Alecaddd are you by chance on NVIDIA graphics?

**Comment by Alecaddd** [comment] 2018-09-24 04:55
Yes, I am, sorry I forgot to specify it.
Currently running nvidia-driver-390.48

**Comment by cassidyjames** [comment] 2018-09-24 05:47
Duplicate of #21

**Closed by cassidyjames** 2018-09-24 05:47 UTC
Labels: Status: Incomplete
