### ISSUE TITLE
Previous screen/apps is shown on login

### ISSUE THREAD

**Issue by Ppamungkas** [elementary/gala#1486] opened 2022-10-20 03:29 UTC
### What Happened?

When login into the elementary, the previous screen shown on login, after that the desktop is loaded normally.

https://user-images.githubusercontent.com/36324190/196849034-78205ca2-d76a-43e0-9193-568df9d6fee9.mp4

### Steps to Reproduce

1. Open several apps
2. Reboot the eOS without closing all the apps
3. Login normally
4. Previous apps will be previewed

### Expected Behavior

On login there should be no preview, it should go straight to the desktop cleanly.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-02-05 04:03
Closing as duplicate of #1423.

**Closed by lenemter** 2023-02-05 04:03 UTC
