### ISSUE TITLE
Execute global shortcuts even if a menu is open

### ISSUE THREAD

**Issue by sprite-1** [elementary/gala#500] opened 2019-03-27 18:30 UTC
When I have menus open, global shortcuts don't work, so for example, if I need to take a screenshot like this, I can't just hit the global shortcut key for taking screenshots.

![Screenshot from 2019-03-28 01 46 07](https://user-images.githubusercontent.com/33685433/55102316-14f61700-5101-11e9-9350-065bac155932.png)

I have to open the Screenshot app, set a delay in seconds, and crop the screenshot later. It's just one example of a use-case where having global shortcuts active would've helped a lot.

**Comment by peteruithoven** [comment] 2019-03-31 12:42
I don't think this is a Gala issue. As far as I understand it these keys are picked up by gnome media-keys daemon. I've asked to move this to http://github.com/elementary/os/

**Comment by peteruithoven** [comment] 2019-05-14 17:12
@danrabbit:
> As for accepting keyboard shortcuts while menus are open, it’s my understanding that this is a limitation of X11 and it is solved in Wayland.

**Comment by danirabbit** [comment] 2023-06-14 00:44
I can confirm that this is fixed in a Wayland session. So, I'm going to close this since it's technically fixed and there's nothing that needs to be done here to resolve it. It might take a while for the fix to ship in a stable release, but it is technically resolved

**Closed by danirabbit** 2023-06-14 00:44 UTC
