### ISSUE TITLE
[Bug] The latest update fixed the title bar context menu for most elementary apps but the "generic" apps' are still broken

### ISSUE THREAD

**Issue by sprite-1** [elementary/gala#430] opened 2018-12-17 18:17 UTC
The latest update to gala fixed the right click menu for most elementary OS apps.

![screenshot from 2018-12-18 02 09 36](https://user-images.githubusercontent.com/33685433/50106292-6a04d000-026a-11e9-803e-132a5af91850.png)

However, on "generic" apps, for example Simplenote, or PlayOnLinux, or Krita, the context menu still doesn't show up when the title baar is right clicke.

![screenshot from 2018-12-18 02 15 17](https://user-images.githubusercontent.com/33685433/50106550-1b0b6a80-026b-11e9-9cde-cd929911046a.png)

**Comment by danrabbit** [comment] 2019-12-12 00:25
Closing as a duplicate of #174

**Closed by danrabbit** 2019-12-12 00:25 UTC
