### ISSUE TITLE
Black screen and keyboard not working after login from suspend

### ISSUE THREAD

**Issue by ssmgcode** [elementary/gala#1064] opened 2021-02-28 19:41 UTC
## What Happened
When I wake my computer from suspend and enter my password, the screen turns black and just the mouse pointer shows.
I have Hot Corners activated (bottom left for multitasking view and top left for Applications Menu). When I go to the bottom left corner, it DOES show the multitasking view with all the windows I was working on. When I click on any window or on the mini applications group at the bottom, it goes back to the black screen.
When I go to the top left corner, it DOES show the Applications menu only if I'm in the multitasking view but when I click on any part of it, it seems it's not there because it clicks on the multitasking view and I can't scroll along applications icons as well.
The only solution for it is to force shut down holding the physical power button.

## Expected Behavior
Show the desktop after login.

## Steps to Reproduce
1. Suspend your machine manually or automatically
2. Wake up and enter your password

### Logs
![Screenshot from 2021-02-28 13 20 02](https://user-images.githubusercontent.com/77636802/109431057-2bcad580-79ca-11eb-98e2-06006a015fdc.png)
I have calculated the time since I suspend until I wake up and enter my password to read the logs.

## Platform Information
OS: version elementary OS 6 Early Access
Hardware: Intel iCore7 7th. Generation, 16 Gb RAM, 1TB hard disk, 27" external Dell Monitor

**Comment by ssmgcode** [comment] 2021-02-28 19:42
I think this should be marked as Critical or High Priority because users can't lock/suspend their machines while they are working to avoid to force shut down when it fails.

**Comment by ssmgcode** [comment] 2021-03-10 21:26
Update: I have realized the bug happens only when my laptop is connected to an external monitor.

**Comment by candiedoperation** [comment] 2021-05-04 05:43
Even I have the same problem, Issue https://github.com/elementary/gala/issues/1126

**Comment by cassidyjames** [comment] 2021-08-23 22:18
Since #1126 has more info and traction, I'll close this as a duplicate of #1126. In the future, @candiedoperation please don't open a new issue if one already exists, but comment with useful information here. It takes a lot of time and effort just to track and close off duplicate issue reports, let alone fixing them :sweat_smile:

**Closed by cassidyjames** 2021-08-23 22:18 UTC
