### ISSUE TITLE
Ardour 5.12 does not fit

### ISSUE THREAD

**Issue by bksubhuti** [elementary/gala#103] opened 2017-10-07 13:27 UTC
Ardour 5.12 does not fit in Elementary's screen window.
I am not sure if this is an Ardour Bug or something that is a Gala bug.
Surely they tested this, so I guess it is a Gala bug.

It is just a little too small and seems to not account for the wingpanel.  Also there is no maximize button.
I do not remember seeing this before hand.  It is with the newer release, but like I said, they test the stuff on other distros.

I am sure devs will send you a copy.  If not I can post the install file on my google drive.

I think this also happened with Krita (more easy to get)  that I downloaded and tried to play with.
Create a new document and the dialog box goes beyond what you can see.

**Comment by Philip-Scott** [comment] 2017-10-07 19:56
Can you post a screenshot and your screen's resolution?

**Comment by bksubhuti** [comment] 2017-10-09 02:51
I am not sure how to find out the resolution.  I checked amazon.  It is acer c1yf model.  The settings about does not say. It is a super cheap  laptop.  The picture of the ardour has been uploaded.
![ardour 5 12 no max](https://user-images.githubusercontent.com/18184280/31323869-16a15232-acd3-11e7-84e6-22fc2043b54d.png)

**Comment by bksubhuti** [comment] 2017-10-10 03:29
Here is the screen res
![resolution](https://user-images.githubusercontent.com/18184280/31368123-bbb98982-ada1-11e7-8fbf-f1c50eb44b2c.png)

**Comment by Nine-H** [comment] 2017-10-17 08:41
The issue is the size of your monitor, Ardour is requesting a window size that's greater than your resolution. this bug report recommends changing the size of your system font and changing the gui scaling in ardour http://tracker.ardour.org/view.php?id=6883

**Comment by bksubhuti** [comment] 2017-10-18 00:11
I will take this up with the ardour group.  The gui scaling does not work no matter how small you make it.  However, you can detach it and then the maximize button appears.  please leave this open for a little bit longer.

**Comment by danrabbit** [comment] 2017-10-18 18:23
There's nothing that Gala can do to change the minimum window size for Ardour. Closing as "Invalid" for Gala

**Closed by danrabbit** 2017-10-18 18:23 UTC
Labels: Status: Incomplete
