### ISSUE TITLE
Mutter 3.34 aka Mutter-5

### ISSUE THREAD

**Issue by SolarAquarion** [elementary/gala#614] opened 2019-09-24 18:42 UTC
It seems the hard max of gala currently is mutter 3.32, but mutter is now at 3.34, and not all systems want to maintain multiple libmutter's in the unofficial/official repo's

**Comment by worldofpeace** [comment] 2019-09-25 02:23
Duplicate of https://github.com/elementary/gala/issues/303

**Closed** 2019-09-25 03:20 UTC
