### ISSUE TITLE
Desktop is unresponsive after logging into a TTY

### ISSUE THREAD

**Issue by Biguibi** [elementary/gala#657] opened 2019-12-11 03:20 UTC
Logging into a TTY with the same user account (untested with other accounts) and coming back to the desktop seems to make the desktop completely unresponsive, you can only move the mouse but no other input is detected neither Plank responds to the cursor's position. Wingpanel is shown but doesn't seem to update. This issue also occurs sometimes randomly after waking the laptop from a suspend.
I've also seen another user [here](https://github.com/elementary/gala/issues/593) with a somewhat similar problem that could be related.

**Comment by lenemter** [comment] 2023-12-13 11:45
I'll close the issue because it's old and I cannot reproduce it in OS 7.1.

**Closed by lenemter** 2023-12-13 11:45 UTC
