### ISSUE TITLE
Unable to select window in multi-tasking view

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/gala#1442] opened 2022-06-29 21:43 UTC
### What Happened?

When in multi-tasking view, whether by trackpad gesture or Super key, clicking on a window does nothing whereas it used to bring that window to the fore in eOS 6.

### Steps to Reproduce

1. Press Super key or swipe three fingers up
2. Click on a window
3. Nothing happens

### Expected Behavior

Clicking on a window should exit multi-tasking view and bring that window to the foreground

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

I: Bus=0018 Vendor=04f3 Product=30f1 Version=0100
N: Name="ELAN1206:00 04F3:30F1 Touchpad"
P: Phys=i2c-ELAN1206:00
S: Sysfs=/devices/platform/AMDI0010:03/i2c-0/i2c-ELAN1206:00/0018:04F3:30F1.0001/input/input8
U: Uniq=
H: Handlers=mouse1 event6 
B: PROP=5
B: EV=1b
B: KEY=e520 10000 0 0 0 0
B: ABS=2e0800000000003
B: MSC=20

**Comment by jolang** [comment] 2022-08-01 20:14
Duplicate of #1413?

**Closed as completed** 2022-09-26 22:22 UTC
Labels: Confirmed
