### ISSUE TITLE
Notifications are not stored in the notification indicator unless the notification indicator is opened

### ISSUE THREAD

**Issue by ryonakano** [elementary/gala#329] opened 2018-09-06 04:24 UTC
## Actual Behavior & Steps to reproduce

Power on your Juno Beta1 and use some app that uses notifications, like Music or Mail.

![screenshot from 2018-09-06 13-06-31](https://user-images.githubusercontent.com/26003928/45134644-8b1f4480-b1d6-11e8-860f-57846b8ad1f2.png)

Notifications appear as bubbles but are not stored in the notification indicator, like this screenshot.

![screenshot from 2018-09-06 13-06-46](https://user-images.githubusercontent.com/26003928/45134645-8e1a3500-b1d6-11e8-90c7-e36e20436450.png)

They are stored in the notification indicator after the notification indicator is opened.

## Expected Behavior

Notifications should appear as bubbles and be stored in the notification indicator even if users don't open the notification indicator.

**Comment by cassidyjames** [comment] 2018-09-11 00:10
@ryonakano can you reproduce this in other apps? Music explicitly does not persist its notifications, as that would fill up the indicator with relatively useless data.

**Comment by ryonakano** [comment] 2018-09-11 10:49
@cassidyjames Here are some screenshots of other apps, including both elementary apps and GNOME components:

![screenshot from 2018-09-11 19-46-40](https://user-images.githubusercontent.com/26003928/45355504-87872580-b5fb-11e8-92fe-3046b602519e.png)

AppCenter

![screenshot from 2018-09-11 19-21-32](https://user-images.githubusercontent.com/26003928/45354213-1eea7980-b5f8-11e8-872f-f296078697f9.png)

Mail (For new message)

![screenshot from 2018-09-11 17-54-03](https://user-images.githubusercontent.com/26003928/45354207-1db94c80-b5f8-11e8-8e9d-2034a16a7b02.png)

Epiphany

![screenshot from 2018-09-11 19-19-55](https://user-images.githubusercontent.com/26003928/45354211-1e51e300-b5f8-11e8-9d5b-13053bd1ee51.png)

GNOME Power Management (Displayed when the battery charge is quite low)

I think we can confirm that notifications are not stored in the notification indicator from these screenshot.
Please let me know if you would like me to submit more screenshot in other apps.

**Comment by cassidyjames** [comment] 2018-09-11 19:15
@ryonakano I am unable to reproduce this with AppCenter, Epiphany, or Mail on an up-to-date Juno system.

![screenshot from 2018-09-11 13 14 50 2x](https://user-images.githubusercontent.com/611168/45382206-c9e14000-b5c4-11e8-8bde-3ace91465b59.png)

**Comment by cassidyjames** [comment] 2018-09-11 19:17
@ryonakano are you saying that if, in a session, you don't _first_ open the indicator (and then potentially close it again) that the notifications are not persisted?

**Closed as completed** 2018-09-11 19:26 UTC
Labels: Confirmed
