### ISSUE TITLE
Black square artifacts in multitasking view after resume (NVIDIA 340 LEGACY)

### ISSUE THREAD

**Issue by crmlt** [elementary/gala#156] opened 2018-01-12 13:14 UTC
Little black squares appears in multitasking view after resume from suspend on system running NVIDIA 340 LEGACY driver.

**Screenshot:**
[https://image.prntscr.com/image/9SBIWnRhSL2QD7zbT5LsVg.png](https://image.prntscr.com/image/9SBIWnRhSL2QD7zbT5LsVg.png)

I have noticed that the issue is gone after gala is reloaded with **gala --replace**.

**Reload gala after every resume isn't needed in this case.**

**Workaround - Reload Gala at Every Startup:**

A best way to achieve it is:

1. Add **gala --replace** into cerbere monitored processes

`gsettings set org.pantheon.desktop.cerbere monitored-processes "['wingpanel', 'plank', 'gala --replace']"`

2. No more black squares in multitasking view after resume

OS: elementary OS 0.4.1 loki, Kernel: x86_64 Linux 4.14.13-xanmod17
WM: (Gala), WM Theme: elementary, CPU: Intel Core2 Duo CPU P8600 @ 2.394GHz
GPU: GeForce 320M, RAM: 2530MiB / 7684MiB

**Comment by peteruithoven** [comment] 2018-02-11 15:13
Duplicate of: https://github.com/elementary/gala/issues/21 ?

Might be useful to add your workaround there and to: https://elementaryos.stackexchange.com/questions/8952/artifacts-in-background

**Comment by crmlt** [comment] 2018-05-17 19:26
It doesn't happen on 18.04 daily build.

**Comment by crmlt** [comment] 2018-07-04 21:50
Fixed in 5.0 Juno Beta 1

**Closed** 2018-07-04 21:51 UTC
