### ISSUE TITLE
Allow fullscreen apps have their CSD

### ISSUE THREAD

**Issue by aggalex** [elementary/gala#567] opened 2019-06-27 14:42 UTC
When apps go fullscreen (Like if you press f11 on elementary code) the apps are stripped off their CSD, which contain functions citical to the UI of the app. Please make it so that the app will have its CSD while fullscreen.

**Comment by Blast-City** [comment] 2019-06-27 20:08
Hi.

Did you set a fullscreen shortcut in the keyboard settings?

More info: elementary/switchboard-plug-keyboard#206

**Comment by aggalex** [comment] 2019-06-28 14:55
No
![image](https://user-images.githubusercontent.com/11951328/60351090-afe6e180-99cd-11e9-9a35-d6af65ed07e7.png)

**Comment by Blast-City** [comment] 2019-06-29 02:00
Oh Ok. I've only seen this issue when force fullscreen is set. For example Files. When an user force fullscreen, the csd disappears, but because by default it doesn't have a fullscreen shortcut (F11) this problem doesn't happen.

What other native apps did you saw this behaviour?

**Comment by aggalex** [comment] 2019-06-29 13:59
code, terminal, GIMP, inkscape, aisleriot. Also firefox, epiphany and photos, but these are intentional I believe.

**Comment by Blast-City** [comment] 2019-06-29 16:09
> code, terminal, GIMP, inkscape, aisleriot. Also firefox, epiphany and photos, but these are intentional I believe.

Hi.

Some of those apps are not native, but i can see that terminal doesn't show the csd in fullscreen.

The problem is, wouldn't show csd make fullscreen mode and maximize the same?

You should see the following thread. I think it resolves your issue.
elementary/wingpanel#93

**Comment by aggalex** [comment] 2019-06-29 20:28
I'm not saying to show csd at all times, just when the cursor goes to the top of the screen, only then will the CSD controls come down from the top like plank, just like in Mac OS

**Comment by Blast-City** [comment] 2019-06-29 22:40
> I'm not saying to show csd at all times, just when the cursor goes to the top of the screen, only then will the CSD controls come down from the top like plank, just like in Mac OS
> 
> BTW, I take it that by native you mean curated I guess

Hi.

Yeah i meant apps that are made by elementary. Sorry.
The link that I provided above seems to correspond to your issue.

**Comment by quequotion** [comment] 2019-09-08 16:34
> I'm not saying to show csd at all times, just when the cursor goes to the top of the screen, only then will the CSD controls come down from the top like plank, just like in Mac OS

Firefox does something close to this; when the window is full screen, the toolbars scroll down from the top if the mouse touches the top edge. It works surprisingly well with my autohiding wingpanel that works the same way (seems like firefox's target stays a pixel or so below wingpanel's). It's super handy. This allows you to have 100% of screen real estate for content without losing the ability to control the application.

Unfortunately, I think it's something the individual application developers have to do for their programs. Some of the elementary OS software suite are not curated but in fact in-house developments and adopted projects. I'd like to have this feature for the tab bar in pantheon-terminal and the navigation bar in pantheon-files.

**Comment by janxkoci** [comment] 2019-11-19 16:39
I see tabs in pantheon-terminal after pressing F11.

**Comment by danrabbit** [comment] 2020-05-25 20:28
Since CSD is by definition client-side, these apps would need to implement this themselves. The window manager (server-side) doesn't draw or control window decorations for client-side decorated apps.

Closing as "Out of scope" since this cannot be solved within the scope of Gala

**Closed by danrabbit** 2020-05-25 20:28 UTC
