### ISSUE TITLE
4 display on gala

### ISSUE THREAD

**Issue by torikulhabib** [elementary/gala#199] opened 2018-03-14 05:20 UTC
i hope can work 4 display.

![3pmc5b2duqo8bqzxg6barbuyok4](https://user-images.githubusercontent.com/26135527/37384435-6eafff2c-2781-11e8-8ff2-9722471c17ae.gif)

**Comment by peteruithoven** [comment] 2018-03-14 07:50
Duplicate of: https://github.com/elementary/gala/issues/105

I think you're referring to something that's usually called quarter tiling. This logic is handled by Mutter, which Gala uses. Recent update: https://gitlab.gnome.org/GNOME/mutter/issues/52#note_77121
The actual Mutter issue to track: https://bugzilla.gnome.org/show_bug.cgi?id=751857

**Closed** 2018-03-25 16:53 UTC
Labels: Status: Duplicate
