### ISSUE TITLE
Request: Enable searching in Windows overview/Show all Windows

### ISSUE THREAD

**Issue by mahajanudit** [elementary/gala#352] opened 2018-10-01 12:25 UTC
In Show All Windows and Windows overview where you can see all windows tiled nicely, please enable searching the windows for more productivity. Even in multitasking view.
This used to be a functionality back in compiz. A nice overview title/windows search.

**Comment by robertmeta** [comment] 2019-02-18 17:19
I was coming here to post exactly this.  This is one of the things I depend on in KDE day to day.  Being able to go to show all windows view and then start typing a part of the window title and having it dynamically reduce the windows in that interface.

**Comment by peteruithoven** [comment] 2019-06-13 21:55
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/218

**Closed by peteruithoven** 2019-06-13 21:55 UTC
