### ISSUE TITLE
The desktop session ends.

### ISSUE THREAD

**Issue by edgarpg** [elementary/gala#767] opened 2020-04-12 00:27 UTC
Hello!
Sorry my bad english.

When I use the OS and switch between desktops it suddenly seems like the session is restarted, just the apps stay in the foreground and plank and shell disappear for a moment and reload. Also sometimes the session ends and returns to LightDM.

**Comment by wout** [comment] 2020-04-13 10:19
Same issue as #766 I think?

**Comment by ryonakano** [comment] 2020-04-21 09:53
Closing as a duplicate of #766.

**Closed by ryonakano** 2020-04-21 09:53 UTC
