### ISSUE TITLE
Full screen applications leave behind empty workspace when closed

### ISSUE THREAD

**Issue by adityaravishankar** [elementary/gala#14] opened 2017-05-27 06:18 UTC
Anytime I open a video app (mpv or vlc) and quit the app while the video is in full screen mode, eOS stays behind on the newly created empty workspace instead of going back to the original workspace.

Currently on elementary OS 0.4.1 Loki

Reproduction steps

1. Open any video in mpv, and switch to full screen mode (using the F key)
2. While video is playing, quit mpv (Using the Q key)

MPV stays behind on a fresh/empty workspace (that was used for full screen), instead of returning to the original workspace from where mpv was started.

This same behavior was reproduced in VLC as well, so it's window manager related and not application specific.

**Comment by jlnr** [comment] 2018-09-21 08:43
This bug has gotten worse for me in Juno. If I create two workspaces by placing windows there, then toggle fullscreen mode in an app on the first workspace several times, I can create an arbitrary number of empty workspaces between the first and second workspace.

(I have a second screen with a few windows on it, in case that makes a difference)

**Comment by ibnesayeed** [comment] 2018-10-22 15:16
@jlnr I am facing similar issues on my recent Juno installation and have no way to kill those empty workspaces. I also have a secondary monitor, if that helps someone reproduce the issue.

**Comment by jlnr** [comment] 2018-10-23 18:16
I think this issue has already been fixed by #357, it's just that there has been no release of gala since then.

**Comment by lenemter** [comment] 2023-12-25 08:22
Closing because I cannot reproduce the issue in OS 7.

**Closed by lenemter** 2023-12-25 08:22 UTC
