### ISSUE TITLE
Window preview not show in multitasking view with mutter >= 40

### ISSUE THREAD

**Issue by mojahed-yavazi** [elementary/gala#1326] opened 2021-12-01 03:48 UTC
### What Happened?

Window preview hide in multitaskting view with mutter 40 and up.

https://user-images.githubusercontent.com/33109339/144168340-14a2241a-f1a8-484d-8007-bb8941d0665a.mp4

### Steps to Reproduce

1. Open multitasking view
2. Switch workspace
3. Switch back

### Expected Behavior

n/a

### OS Version

Other Linux

### Software Version

Compiled from git

### Log Output

```shell
clutter_paint_volume_set_width: assertion 'width >= 0.0f' failed
Dec 01 07:16:09 Archlinux gala[27845]: clutter_paint_volume_set_height: assertion 'height >= 0.0f' failed
Dec 01 07:16:13 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:13 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:13 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<GalaSafeWindowClone>:0x561dfd0eeb40] is on because it needs an allocation.
Dec 01 07:16:13 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<GalaSafeWindowClone>:0x561dfd0ee480] is on because it needs an allocation.
Dec 01 07:16:13 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:13 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:14 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:18 Archlinux gala[27845]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed
Dec 01 07:16:18 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<GalaSafeWindowClone>:0x561dfd0eeb40] is on because it needs an allocation.
Dec 01 07:16:18 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<GalaSafeWindowClone>:0x561dfd0ee7e0] is on because it needs an allocation.
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: clutter_actor_set_allocation_internal: assertion '!isnan (box->x1) && !isnan (box->x2) && !isnan (box->y1) && !isnan (box->y2)' failed
Dec 01 07:16:18 Archlinux gala[27845]: clutter_actor_set_allocation_internal: assertion '!isnan (box->x1) && !isnan (box->x2) && !isnan (box->y1) && !isnan (box->y2)' failed
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:18 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfcf184d0]' tried to allocate a size of -inf x -inf
Dec 01 07:16:19 Archlinux gala[27845]: ../mutter/clutter/clutter/clutter-actor.c:9240: Actor '<unnamed>[<ClutterClone>:0x561dfd151190]' tried to allocate a size of -inf x -inf
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaStage>:0x561dfbbf3c60] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<ClutterActor>:0x561dfbce0c80] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561dfbce0320] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561dfcf53310] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561dfcf5a320] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaStage>:0x561dfbbf3c60] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<ClutterActor>:0x561dfbce0c80] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x561dfbce0320] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x561dfcf53310] is on because it needs an allocation.
Dec 01 07:16:30 Archlinux gala[27845]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x561dfcf5a320] is on because it needs an allocation.
```

**Comment by danrabbit** [comment] 2022-05-23 20:21
Closing this as a duplicate of #1354 even though this is older just because that one is connected to projects and other issues and stuff

**Closed by danrabbit** 2022-05-23 20:21 UTC
