### ISSUE TITLE
Add keybinding for shortcut overlay

### ISSUE THREAD

**Issue by cassidyjames** [elementary/gala#114] opened 2017-11-02 15:53 UTC
We're looking at making a native GTK shortcut overlay applet that Gala could launch. We would need to add keybindings to Gala to launch this applet (probably configurable exec name in dconf, like the application launcher) when the Super key is held down.

**Comment by danrabbit** [comment] 2018-03-21 19:21
Closing because this is outside the scope of Gala and a duplicate of https://github.com/elementary/default-settings/issues/31

**Closed by danrabbit** 2018-03-21 19:21 UTC
Labels: Priority: Wishlist
