### ISSUE TITLE
gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed

### ISSUE THREAD

**Issue by davidak** [elementary/gala#59] opened 2017-08-14 08:39 UTC
I can't change the background image.

![screenshot from 2017-08-14 10 37 43](https://user-images.githubusercontent.com/91113/29264277-b07fb560-80dc-11e7-90db-7ba844528c49.png)

The image i want is displayed in the settings, but when i click on it nothing happens. Also when i click on other standard background images.

syslog
```
Aug 14 10:30:16 Latitude-E5470 gnome-session[1671]: (switchboard:11912): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
Aug 14 10:30:16 Latitude-E5470 gnome-session[1671]: (switchboard:11912): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
Aug 14 10:30:16 Latitude-E5470 gnome-session[1671]: (switchboard:11912): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
Aug 14 10:30:20 Latitude-E5470 gnome-session[1671]: ** (gala:1891): WARNING **: Preferences.vala:192: '/usr/share/themes/elementary/plank/dock.theme' is read-only!
Aug 14 10:30:27 Latitude-E5470 gnome-session[1671]: (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:30:59 Latitude-E5470 gnome-session[1671]: message repeated 15 times: [ (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed]
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /home/davidak/.local/share/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** (process:12011): WARNING **: FileEnumerator.vala:60: Could not process directory '/home/davidak/.local/share/contractor': Error opening directory '/home/davidak/.local/share/contractor': No such file or directory
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /usr/share/pantheon/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** (process:12011): WARNING **: FileEnumerator.vala:60: Could not process directory '/usr/share/pantheon/contractor': Error opening directory '/usr/share/pantheon/contractor': No such file or directory
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /usr/local/share/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** (process:12011): WARNING **: FileEnumerator.vala:60: Could not process directory '/usr/local/share/contractor': Error opening directory '/usr/local/share/contractor': No such file or directory
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: FileEnumerator.vala:39: Looking up contracts in: /usr/share/contractor
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/set-wallpaper.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/file-roller-compress.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/file-roller-extract-here.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/gnome-bluetooth.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/mail-attach.contract' loaded successfully.
Aug 14 10:31:23 Latitude-E5470 org.elementary.Contractor[1744]: ** Message: ContractSource.vala:65: Contract file '/usr/share/contractor/print.contract' loaded successfully.
Aug 14 10:31:30 Latitude-E5470 org.elementary.Contractor[1744]: (set-wallpaper:12017): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
Aug 14 10:31:30 Latitude-E5470 org.elementary.Contractor[1744]: (set-wallpaper:12017): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
Aug 14 10:31:30 Latitude-E5470 org.elementary.Contractor[1744]: (set-wallpaper:12017): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
Aug 14 10:31:31 Latitude-E5470 gnome-session[1671]: ** (gala:1891): CRITICAL **: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed
Aug 14 10:31:31 Latitude-E5470 gnome-session[1671]: message repeated 3 times: [ ** (gala:1891): CRITICAL **: gala_background_manager_swap_background_actor: assertion '_tmp0_ != NULL' failed]
Aug 14 10:31:32 Latitude-E5470 gnome-session[1671]: (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:31:32 Latitude-E5470 gnome-session[1671]: (gala:1891): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'width > 0' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_rowstride: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_pixels_with_length: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GdkPixbuf-CRITICAL **: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: (tumblerd:11985): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: **
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: tumbler-poppler-thumbnailer:ERROR:poppler-thumbnailer.c:362:poppler_thumbnailer_create: assertion failed: (pixbuf != NULL)
Aug 14 10:31:45 Latitude-E5470 org.freedesktop.thumbnails.Thumbnailer1[1744]: BAD status: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```

---

elementary OS 0.4.1 Loki (based on Ubuntu 16.04.2 LTS)
Kernel: Linux 4.10.0-32-generic
on Dell Latitude E5470 (Intel i5, 8 GB RAM)
with 2 external Dell displays

**Comment by Philip-Scott** [comment] 2017-08-14 14:51
Closing since it's a duplicate of #13 :smile:

**Closed by Philip-Scott** 2017-08-14 14:51 UTC
Labels: Status: Duplicate
