### ISSUE TITLE
Chrome window tiling/snapping issue

### ISSUE THREAD

**Issue by lasalvavida** [elementary/gala#425] opened 2018-11-28 22:36 UTC
I get the following behavior sometimes when snapping chrome windows (I've noticed this with a few other applications as well).

![snap-issue](https://user-images.githubusercontent.com/2489570/49186781-8aa8cc80-f333-11e8-996c-3f5a90f1220e.gif)

The UI is still responsive, but it seems like the cursor location isn't being mapped correctly into the window's coordinate space. The only way I have found to exit this state is to close the application and re-open it.

I am running Juno - this issue was not present in Loki.

If I resize the chrome tab to be smaller (fitting completely in the screen viewport), it behaves properly when I snap it.

**Comment by cassidyjames** [comment] 2018-11-28 22:38
Thanks for reporting! Please check existing reports before filing a new one. This is a duplicate of #305.

**Closed by cassidyjames** 2018-11-28 22:38 UTC
