### ISSUE TITLE
Window set to appear everywhere doesn't play nice with plank

### ISSUE THREAD

**Issue by janxkoci** [elementary/gala#531] opened 2019-05-09 15:32 UTC
I have plank setup such that it hiddes whenever any window touches it (so not just maximized nor foreground windows, but _any_ window). Not sure now if it's the default.

If I then set some window to appear on every desktop (by right-clicking the titlebar of that window and selecting corresponding option) and move it to touch/cover plank, the dock hiddes properly.

But when I switch to another workspace, the plank doesn't hide even though this window is covering it (so plank _should_ be hidden).

Not sure if it's gala or plank issue, but I couldn't find repo for plank, so I post it here.

**Comment by peteruithoven** [comment] 2019-05-09 19:21
Plank repo: https://launchpad.net/plank
(It's a independent project)

**Comment by janxkoci** [comment] 2019-05-13 09:00
@peteruithoven Thanks. Do you think I should cross-post it there or wait until somebody checks it's not gala?

**Comment by peteruithoven** [comment] 2019-05-13 14:39
I'm not sure. It would be interesting to check if there are existing Plank issues.

**Comment by janxkoci** [comment] 2019-05-31 15:41
Hi again,
sorry for the delay, I've been busy (PhD etc). So the only issue that looked _slightly_ relevant is [this bug](https://bugs.launchpad.net/plank/+bug/1009840) - however it's from 2012 so I dunno if it even applies to the current code.

But the issue I have is not reported there - now what?

**Comment by lenemter** [comment] 2023-12-13 11:04
Closing because I cannot reproduce the issue in OS 7.1

**Closed by lenemter** 2023-12-13 11:04 UTC
