### ISSUE TITLE
Large GTK menu unusable

### ISSUE THREAD

**Issue by kr428** [elementary/gala#495] opened 2019-03-25 09:04 UTC
Working with the Eclipse IDE, I regularly end up with *very* big context menus that extent beyond the lower screen border. In GNOME and most other GTK+ based desktops, I can scroll through the menu to reach entries hidden "below" the screen border. Elementary, however, seems to miss this feature so every entry "below" the screen border is unavailable / unreachable. 

Expectation: The menu behaviour is similar to other desktops to allow for scrolling or some means of navigating through menus larger than the screen height.

![gtk-menu-scroll](https://user-images.githubusercontent.com/685879/54907054-f1ef1b80-4ee4-11e9-9d65-2c921b40de3d.png)

**Comment by lenemter** [comment] 2023-10-31 10:55
Closing because I cannot reproduce the issue in OS 7.

**Closed by lenemter** 2023-10-31 10:55 UTC
