### ISSUE TITLE
Resizing with window aspect hints is glitchy

### ISSUE THREAD

**Issue by danirabbit** [elementary/gala#1277] opened 2021-10-26 17:22 UTC
### What Happened?

Setting window geometry aspect hints causes glitches when resizing a window

### Steps to Reproduce

Set geometry hints for a window as in:

```
var hints = Gdk.Geometry ();
hints.min_aspect = 1.0;
hints.max_aspect = 2.0;

main_window.set_geometry_hints (null, hints, Gdk.WindowHints.ASPECT);
```

Notice that `min_aspect` seems to work fine, but if you resize where `max_aspect` would be required, the window glitches out as it resizes

### Expected Behavior

Windows should resize smoothly both with in and max ratio

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-10-26 03:59
Closing because I cannot reproduce the issue in OS 7.

**Closed by lenemter** 2023-10-26 03:59 UTC
