### ISSUE TITLE
Menus leave artifacts on the screen when dismissed

### ISSUE THREAD

**Issue by willco007** [elementary/gala#1249] opened 2021-09-08 21:04 UTC
## What Happened
When a  contextual menu, window menu or application menu extends outside of the window frame and then is dismissed, it will leave part of the menu visible on screen until that part of the screen is redrawn (see screenshot).  Apologies if this isn't the correct repo to file this under.

## Expected Behavior
The menu is fully removed from the screen when dismissed

## Steps to Reproduce
1. Overlap two Files windows (see screenshot)
2. Right click on the right end of the file list so that the contextual menu shows off the window over the second window
3. Click again to dismiss the contextual menu
4. Observe menu artifacts left on screen (may take multiple attempts)

## Platform Information
- Elementary OS 6, update to date as of this report
- Integrated graphics (UHD 620) on a i3-8130U HP laptop
* EOS 6.0

![menu-artifacts](https://user-images.githubusercontent.com/4294739/132585220-9a4c94ef-afcb-48e4-a2fd-72fddbf43907.png)

**Comment by Blast-City** [comment] 2021-09-08 22:48
Hi.

Is this the same issue as #605? If yes, please close this in favor of #605 since it's a duplicate.

Thanks.

**Comment by willco007** [comment] 2021-09-08 23:10
Unsure, I'm only seeing artifacts on EOS styled menus (rounded, padded out menu items), not squared off menus from something like Chrome. In fact, I can't reproduce it in Chrome at first blush.

**Comment by Richardsause** [comment] 2021-12-01 19:17
im having the same issue, but im running a 11th Gen Intel i3-1115G4 with its own igpu, the same thing still happens after i uninstall intel's crappy xorg driver

**Comment by lenemter** [comment] 2022-12-23 03:37
Duplicate of #605

**Closed by lenemter** 2022-12-23 03:37 UTC
