### ISSUE TITLE
Cannot assign Alt+` or Alt+Shift+Tab for Backward Cycling of Windows

### ISSUE THREAD

**Issue by mshafat** [elementary/gala#802] opened 2020-05-16 17:25 UTC
I think it is a bug that I can't assign Alt+Shift+Tab for backward window cycling. It is a very common practice in Windows OS. I know by default there is no way to use this shortcut. But I have found the option Backward Cycling in keyboard shortcuts. But I cann'ot assign basically any shortcut in combination with "shift" key? Why's so? Isn't it a bug. Also, I have also tried to put " Alt+` " instead of Alt+Shift+Tab, it is also not assignable. Why's so? I don't want to use Alt+` for backward cycling, I want to use it for cycling between instances of same application windows (Just mentioned it for a feature request)

**Comment by davidmhewitt** [comment] 2020-05-16 17:32
This seems to be a duplicate of #18 

If you change "Switch Layout" to something other than "Alt + Shift" under "System Settings -> Keyboard -> Layout", then this should work properly.

**Closed by davidmhewitt** 2020-05-16 17:32 UTC
