### ISSUE TITLE
Screen Flickers Once When Unfolding Laptop

### ISSUE THREAD

**Issue by GavinXSF** [elementary/gala#1524] opened 2023-02-04 06:49 UTC
### What Happened?

I use eos7.0 on a Lenovo Yoga laptop. Each time I unfold the device and it wakes from suspension, the screen flickers, showing exactly the content before folding, and then jumps to login interface.

### Steps to Reproduce

1. Suspend when close the lid
2. Close the lid
3. Unfold the device and wake it from suspension

### Expected Behavior

The flicker should be gone.
The device directly jumps to login interface.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Lenovo YOGA 14s 2021 Laptop 
CPU: AMD Ryzen 7 5800H 
Mem: 16GB 512GB
Display: 2.8K 90Hz 14 Inch
No independent graphics card

**Comment by TomiOhl** [comment] 2023-02-04 13:43
Same as #1423

**Comment by lenemter** [comment] 2023-02-04 13:44
Thank you @TomiOhl. Closing as duplicate of #1423.

**Closed by lenemter** 2023-02-04 13:44 UTC
