### ISSUE TITLE
UX: Add ability to position switcher from bottom to mid 

### ISSUE THREAD

**Issue by mahajanudit** [elementary/gala#353] opened 2018-10-01 14:35 UTC
This is not a high priority issue but while switching, I have noticed that it takes some effort to look down and see other applications. Although the preview is really nice, it looses a bit of productivity. I thought I will get used to it, but it has been weeks now and I still find it a bit off the place. 
There should be an option to use it over center of the screen, just the position and no other change.

**Comment by donadigo** [comment] 2018-10-01 15:58
Part of https://github.com/elementary/gala/issues/72.

**Comment by mahajanudit** [comment] 2018-10-01 16:18
Aah, just checked out your repo and left few comments. I am looking to start some development, not sure if i will ever get time but if i do i will look into tinkering with your repo to start with.

**Comment by danrabbit** [comment] 2019-12-12 00:19
Yeah I'm going to close this as a duplicate of #72 since that's where we're doing Alt + Tab redesign discussion

**Closed by danrabbit** 2019-12-12 00:19 UTC
