### ISSUE TITLE
Show workspaces when window dragged to hot corner

### ISSUE THREAD

**Issue by tort-dla-psa** [elementary/gala#152] opened 2018-01-05 16:08 UTC
I suggest to show workspaces when window is dragged to corner (and if corner function is bind to "show workspaces") and allow user to drag window to another desktop.

Or implement the same but when window is dragged to the left/right edge of the screen.
It'll slightly improve UX.

**Comment by danrabbit** [comment] 2019-12-12 00:00
I'm gonna close this as a duplicate of #569 since that's linked to an in-progress PR :)

**Closed by danrabbit** 2019-12-12 00:00 UTC
