### ISSUE TITLE
chrome issue? workspace view shows empty workspace when actually there is a window there

### ISSUE THREAD

**Issue by megatux** [elementary/gala#674] opened 2020-01-07 12:35 UTC
## Prerequisites
- [ x] I have searched open and closed issues for duplicates.

## Describe the bug
The workspace switcher view don't show all windows. There is a Chrome window on it.
This is a very old issue. Example: I have a Chrome window in the 2nd workspace, it shows an _empty_ space. See 

![Captura de pantalla de 2020-01-07 09-32-16](https://user-images.githubusercontent.com/850020/71895746-aaaee000-3130-11ea-8d6f-5ca903b7a26a.png)

![Captura de pantalla de 2020-01-07 09-28-54](https://user-images.githubusercontent.com/850020/71895580-2bb9a780-3130-11ea-869b-5a3ad9899c1c.png)
![Captura de pantalla de 2020-01-07 09-28-37](https://user-images.githubusercontent.com/850020/71895581-2c523e00-3130-11ea-9c21-e6eb49caf9d9.png)

## Platform Information
![Captura de pantalla de 2020-01-07 09-27-47](https://user-images.githubusercontent.com/850020/71895512-ff9e2680-312f-11ea-8438-2fbacbe91579.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [ x] I'm using the latest released stable version

**Comment by lenemter** [comment] 2023-03-28 11:41
Closing since cannot reproduce in OS 7 and no such bug report were filed recently, so probably fixed. Reply here if you still encounter this in OS 7 please.

**Closed by lenemter** 2023-03-28 11:41 UTC
