### ISSUE TITLE
Window border and shadow glitch in multitasking mode when using three finger gestures

### ISSUE THREAD

**Issue by urandom0** [elementary/gala#1351] opened 2021-12-23 10:41 UTC
### What Happened?

There is no border shadow and the window frames get transparency when using three fingers touchpad gesture to switch multitasking mode. Please watch this video below

https://user-images.githubusercontent.com/93508883/147228886-14c0aef9-407d-4042-9a58-1db98a4a411a.mp4

### Steps to Reproduce

I don't know really...
1. Open some applications
2. Use three fingers gesture to switch overview mode
3. Sometimes work as expected, sometimes doesn't, I really don't know what causes this

### Expected Behavior

Proper window shadows and frames.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

System:
Host: ElementaryOS6 Kernel: 5.11.0-43-generic x86_64 bits: 64 Desktop: Pantheon Distro: elementary OS 6.1 Jólnir 
Machine:
Type: Laptop System: LENOVO product: 20AMS2L000 v: ThinkPad X240 serial: <superuser/root required> 
Mobo: LENOVO model: 20AMS2L000 v: 0B98401 PRO serial: <superuser/root required> UEFI [Legacy]: LENOVO 
Graphics:
Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
Display: x11 server: X.Org 1.20.13 driver: modesetting unloaded: fbdev,vesa resolution: 1366x768~60Hz 
OpenGL: renderer: Mesa DRI Intel HD Graphics 4400 (HSW GT2) v: 4.5 Mesa 21.0.3

**Comment by lenemter** [comment] 2022-12-23 14:12
Duplicate of #1203

**Closed by lenemter** 2022-12-23 14:12 UTC
