### ISSUE TITLE
Investigate and open issues for the problems described at Dedoimedo

### ISSUE THREAD

**Issue by inad9300** [elementary/gala#111] opened 2017-10-23 19:17 UTC
I encountered by chance this article -- https://www.dedoimedo.com/computers/elementary-0-4-loki-again.html

It describes several situations in which elementary OS can be improved or simply fails miserably (I've also had serious problems to make any use of Bluetooth at all). I think it should be checked and a few issues should be opened based on its content. Learning from first-timers that rapidly get a sense of a OS full of flaws is worth a lot if the goal is to improve.

P.S. Please point me out to the proper place where this kind of issues should be located, as this is clearly not a good one.

**Comment by danrabbit** [comment] 2017-10-23 19:26
These are all problems related to bad drivers or the live session. There's nothing that can be done in Gala to solve this. These are kernel-level.

Marking as "invalid" for Gala since there's no action that can be taken in this code base

**Closed by danrabbit** 2017-10-23 19:26 UTC

**Comment by inad9300** [comment] 2017-10-24 17:27
I knew beforehand it wasn't a problem with Gala, but I kindly asked you to point me to the right place where cross-project issues should go so that I do not make the same mistake again next time.

I haven't been able to spot anything specific to live session... Except perhaps the performance problems, but even then elementary did badly compared with others, the author says, which implies there is room for improvement.

Again about the "bad drivers", I only see one issue that could be related, which is Bluetooth. And the same person published another article on Loki, on the same laptop, in which the Bluetooth worked... (https://www.dedoimedo.com/computers/elementary-0-4-loki.html) So I wouldn't be so quick in saying that it is an issue with the drivers.

You missed a lot of other points... Your own Harvey tool quickly displays two "x"s when giving it the default Scratch colors as input; accessibility really suffers there. The choice of default browser is still clearly a bad one; it simply is not ready for the public. What about the issue he mentions with the music? Wrong number of songs, wrong song duration... Isn't that worth some investigation? What about the difficulties installing simple software? Coming from a person really used to running Linux is at least worrying. The extra padding on window screenshots? Not the first nor the last complain I hear about them; an option to remove them seems necessary.

You should value more critics like this, not just ignore them as you did. It translates in valuing more your users.

**Comment by danrabbit** [comment] 2017-10-24 17:53
It would be best to file issues against the appropriate repository. GitHub doesn't support moving issues, so there is no "catch all" issue tracker here.

Scratch uses the Solarized color palette which is intentionally low contrast because it is meant for using over extended time periods, [but it does pass WCAG AA](https://snook.ca/technical/colour_contrast/colour.html#fg=586E75,bg=FDF6E3)

Epiphany is the only currently maintained native web browser available, so debating its "readiness" is moot.

If you can reproduce an issue in music, please [open a new issue report in its issue tracker](https://github.com/elementary/music/issues)

Sideloading apps from the Internet is discouraged. Apps are available for installation from AppCenter.

The screenshot tool takes a screenshot of the whole screen, a selection, or the current window. A window's shadow is part of the window, drawn by the toolkit not the window manager. This is the expected behavior. He sees a black border instead of the window shadow due to bad video drives. If you want to screenshot only a portion of the window, you can use the area selection tool.
