### ISSUE TITLE
Touching window with three fingers in multitasking view closes the window

### ISSUE THREAD

**Issue by CodeVault** [elementary/gala#977] opened 2020-12-02 14:26 UTC
## What Happened

Touching window with three fingers in multitasking view closes the window

## Expected Behavior

Resuming to normal view or none
## Steps to Reproduce

1. Open two to three apps in one or more workspaces.
2. Swipe down with three fingers for multi tasking view.
3. Tap with three fingers on any open window. Window will close.

4. This can unexpectedly close running tasks.

## Platform Information

eOS 6 daily builds

**Comment by JoseExposito** [comment] 2020-12-02 17:27
I think this issue is similar to: https://github.com/elementary/gala/issues/975

By default, three fingers tap is equivalent to mouse wheel click. The default behaviour in the multitasking view is to close the clicked window.
IMHO this is not a bug, however, the inclusion of multitouch gestures makes easier to close a window by mistake.

Let's wait for the opinion of someone in the elementary team to see if it is worth it to remove this feature or they prefer to leave as it is.

**Comment by CodeVault** [comment] 2020-12-02 17:52
Thanks @JoseExposito for making touchegg. It will bring more fun in Linux laptop usability. I have posted one suggestion video for eOS gestures on twitter please do watch it 

https://twitter.com/_aditya_patil/status/1332943061685399553?s=20

**Comment by danrabbit** [comment] 2020-12-30 21:52
Yeah I'm going to close this as a duplicate of #975 so we can keep discussion in one place

**Closed by danrabbit** 2020-12-30 21:52 UTC
