### ISSUE TITLE
Cursor sizing

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/gala#819] opened 2020-05-26 02:48 UTC
I don't know if this happens because I have a 4k screen or something else, but every time I change the cursor size to the largest size available in the settings, the screen freezes for a long while then I get logged out and I can never log back in again after that. I'd have to drop into a tty session and use dconf editor to change the cursor size to something smaller then reboot then I am able to log back in.

**Comment by lenemter** [comment] 2023-10-31 09:54
Closing because the issue is old and no similar issues were reported.

**Closed by lenemter** 2023-10-31 09:54 UTC
