### ISSUE TITLE
Workspace switch animation gone when dynamic-workspaces were off

### ISSUE THREAD

**Issue by vaclavhlobil** [elementary/gala#1225] opened 2021-08-24 11:31 UTC
## What Happened

I don't like dynamic workspaces. So after installation of elementary OS 6, I switched it off with dconf-editor `org.gnome.mutter.dynamic-workspaces` (because `org.pantheon.desktop.gala.behavior.dynamic-workspaces` did nothing).

When I switched it off, desktop logged me out immediately from my session. After new login, workspaces were working fine (4 permanent workspaces), except of animation of workspace switching. There is no animation at all, workspaces switches instantly.

## Expected Behavior

Animated worspaces switching is expected.

**Comment by Waester** [comment] 2021-09-12 11:02
I noticed the same issue, with dynamic workspaces off the animations for workspace switching is gone.
I tried turning off dynamic workspaces in Hera and didn't experience same issue.
Seems to be new to Odin.

**Comment by lenemter** [comment] 2023-02-10 08:51
Closing because I cannot reproduce the issue on OS 7. Please reopen if you still run into this.

**Closed by lenemter** 2023-02-10 08:51 UTC
