### ISSUE TITLE
Feature request: power save / ultra power save mode for elementary OS

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/gala#1452] opened 2022-08-12 22:54 UTC
### Problem

This is more related to various OS functionality but as I ca't create issues in the `os` repository, I'm opening this issue here.

In order to save battery lifetime and charge cycles, I want my laptop battery to be drained as little as possible.
On other mobile devices, there is usually a battery saver, maybe sometimes even an "ultra power save" mode.

I want the same features natively in elementary OS.

### Proposal

Please add to the system apps two new shortcuts:
* Power Save Mode
* Ultra Power Save

The Power save should
* turn down display brightness to a configurable level
* turn of Bluetooth when no device is connected
* turn off WIFI when device not connected to a WIFI
* set CPU, RAM, Graphics card, HDDs to power save mode (e.g.: turn down CPU clock speed to the power saving mode / only use efficiency cores on modern CPUs)
* enable the options for display off / system sleep after idle which can already be configured in the system settings with elementary OS 6.x
* 

Ultra power save mode should:
* on devices with OLED display: enable "ultra dark theme in eOS and installed browsers like chrome, firefox, etc.). By ultra dark theme I mean that the dark part is made with RGB 0,0,0 color so the OLED can be completely off in the portions of the screen that will be black.
* all connections (optional... the user should be able to configure the ultra power save mode and this power save feature should be skippable by the user)
* turn off VPN clients like PIA etc. or the system internal VPN
* turn off unnecessary services (to be identified and configured by the user. Maybe add an export option to the power save settings dialog where the user can select services from a list which should be disabled during ultra power save)
* enable power save mode in all IDEs (at least IntelliJ offers this feature) 

### Prior Art (Optional)

There are some applications that can help save power on laptops: 

* tlp
* many others

**Comment by danirabbit** [comment] 2022-10-05 16:10
This is a duplicate of https://github.com/elementary/switchboard-plug-power/issues/204

And it's already been fixed, so look forward to this feature in OS 7! :)

**Closed by danirabbit** 2022-10-05 16:10 UTC
