### ISSUE TITLE
Invalid app definition in the notification center

### ISSUE THREAD

**Issue by BrusAndr** [elementary/gala#61] opened 2017-08-16 17:17 UTC
If notification comes in telegram, it is defined as notification from IntelliJ IDEA.

Telegram version: 1.1.19. Downloaded from oficial site. Extracted to /opt/Telegram/.
IntelliJ IDEA version: 2017.2.2. Downloaded from JetBrains ToolBox App.
elementaryOS version: 0.4.1 stable. All updates are installed.

**Comment by Philip-Scott** [comment] 2017-08-16 17:24
@BrusAndr Can you post the contents of the InteliJ IDEA's .desktop file? 

It should be located under `/usr/share/applications` or under '/home/your-user/.local/share/applications` :) 

Thanks

**Comment by BrusAndr** [comment] 2017-08-16 17:25
@Philip-Scott 

[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA Ultimate
Icon=/opt/JetBrains/apps/IDEA-U/ch-0/172.3757.52/.icon.svg
Exec="/opt/JetBrains/apps/IDEA-U/ch-0/172.3757.52/bin/idea.sh" %f
Comment=Capable and ergonomic Java IDE
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-idea

**Comment by Philip-Scott** [comment] 2017-08-16 17:29
Can you remove the `"` from the Exec line, reboot and test if you can still reproduce it? :)

**Comment by BrusAndr** [comment] 2017-08-16 17:38
OMG
It really works :)

**Comment by png2378** [comment] 2017-08-16 17:43
@Philip-Scott so, whose is that bug? Gala or 3rd party app? 😊

**Comment by Philip-Scott** [comment] 2017-08-16 23:18
@png2378 It's really a 3rd party bug since they're making an invalid .desktop file, but i think we should be catching that error and just ignoring that app instead of gala saying that it's this invalid app's notification

**Comment by peteruithoven** [comment] 2018-02-09 10:41
You could use the [AppEditor](https://appcenter.elementary.io/com.github.donadigo.appeditor.desktop) application to locate and edit the desktop file.

Don't forget to open an issue in the issue queue of the third party app.

**Comment by Philosoft** [comment] 2018-02-09 11:31
For history. @Philip-Scott 

> Arguments may be quoted in whole. If an argument contains a reserved character the argument must be quoted. The rules for quoting of arguments is also applicable to the executable name or path of the executable program as provided.


quoted from [spec](https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s07.html)

seems legit to me

**Comment by jlnr** [comment] 2018-02-09 20:40
I was bored and wanted to see how the notification system works, so: What was happening in the wingpanel indicator is that Utils.vala looked at `app_info.get_executable ()`, which returned a string in quotes for IntelliJ (the first part of Exec). Since the code didn't consider this an absolute path (it started with `"`, not `/`) it tried to look up this binary (the full quoted string) in `$PATH`, finding `null`. Since it couldn't find Telegram in `$PATH` either, the notification was attributed to IntelliJ (matching executables: `null == null`).

The linked PR should fix it, anyway :+1:

**Comment by cmonagle** [comment] 2018-04-25 20:53
It looks like the PR to resolve this issue was closed... will this be resolved in Juno?

**Comment by donadigo** [comment] 2018-04-25 20:55
This should probably be closed because the PR to fix this was merged to master: https://github.com/elementary/wingpanel-indicator-notifications/pull/44, (another words, yes, resolved in Juno).

**Closed** 2018-04-27 23:14 UTC
