### ISSUE TITLE
gap around windows when comming out off workspaces view

### ISSUE THREAD

**Issue by codesardine** [elementary/gala#941] opened 2020-10-21 10:35 UTC
### To Reproduce
Go to workspace view, launch a application while on workspace view, then go to that workspace.

### Screenshots or screen recordings
![Screenshot_2020-10-21_11-42-30](https://user-images.githubusercontent.com/4250006/96709424-94f26a80-1392-11eb-9819-7a7feaae4389.png)

Expected behaviour, when entering the workspace, windows should go back to their intended position at 0.0, minimising and maximising the window fixes their position on screen.

## Platform Information
Gala 3.3.2
Manjaro

**Comment by lenemter** [comment] 2023-10-31 09:46
Closing because I cannot reproduce the issue on OS 7. Please reply here if you still encounter the issue.

**Closed by lenemter** 2023-10-31 09:46 UTC
