### ISSUE TITLE
Every application crashes session

### ISSUE THREAD

**Issue by ArtemPopof** [elementary/gala#469] opened 2019-02-25 13:06 UTC
I have fresh installation of Elementary OS 5.0, when I trying to open Files, Epiphany, Music or any other app, display blinks and I end up at login screen.

CPU: intel pentium G2020
GPU: NVIDIA GT1030

**Comment by ArtemPopof** [comment] 2019-02-25 13:09
terminal application seems to work

**Comment by peteruithoven** [comment] 2019-02-25 13:09
Could you try this: https://github.com/elementary/os/issues/182#issuecomment-464466858
and share the results?

**Comment by ArtemPopof** [comment] 2019-02-26 10:12
Here's the log: [issueNEW.log](https://github.com/elementary/gala/files/2904890/issueNEW.log)

**Comment by ArtemPopof** [comment] 2019-02-26 10:14
I don't have this problem when using live usb with elementary.

**Comment by peteruithoven** [comment] 2019-02-26 10:28
Ah, good idea. Maybe you could compare logs between normal login and starting application to doing that from a live usb.

Things that catch my eye:
- `Invalid MIT-MAGIC-COOKIE`
- `PROCESS 'wingpanel' CRASHED`
- `PROCESS 'plank' CRASHED`
- `'wingpanel' exceeded the maximum number of crashes allowed (5). It won't be launched again`

**Comment by ArtemPopof** [comment] 2019-02-26 10:40
I check running with integrated Intel GPU and issue is gone.

**Comment by ArtemPopof** [comment] 2019-02-26 10:48
Live usb don't use my gpu, because it draws UI very slow, so I think it's software rendering when using live usb. For me it looks like a problem with nvidia driver, that comes with Elementary OS 5.0 installation. Maybe it has something to do with poor wayland support by nvidia?

**Comment by peteruithoven** [comment] 2019-02-26 11:27
There are plenty of people using NVIDIA that don't experience this issue though. So there must be another contributing factor. Maybe try switching between proprietary and opensource driver? Maybe try another version?

> Maybe it has something to do with poor wayland support by nvidia?

elementary OS doesn't use Wayland.

**Comment by ArtemPopof** [comment] 2019-02-26 16:12
I installed proprietary nvidia drivers and now everything works fine.

**Comment by peteruithoven** [comment] 2019-02-26 16:13
Great to hear that fixes it for you. I'm closing this issue, as there is a small change this is actually caused by Gala.

**Closed by peteruithoven** 2019-02-26 16:13 UTC
