### ISSUE TITLE
Gala have an abnormally high cpu usage if there is no shortcuts on Plank

### ISSUE THREAD

**Issue by Blast-City** [elementary/gala#135] opened 2017-12-04 00:01 UTC
Hi.  

On idle, Gala have a marginal cpu usage, but if there is no items on Plank the cpu usage increases.and the Gala process is always on the top.

I tried this on the following scenarios:  

- Kernel 4.4 with LTS X Stack

- Kernel 4.4 with HWE X Stack

- Live USB with Kernel 4.10 and HWE X Stack

All gave me the same result.

How to replicate:  

- With no applications open check the cpu usage of Gala.  

- Remove all shortcuts from Plank either by mouse or deleting all files in .config/plank/dock1/launchers/

- Log out  

- Next time you log in check the top command and compare the cpu usage of Gala with the value in the first step.

**Comment by lolwhoami** [comment] 2018-06-19 10:36
This bug still exists.
I described it [here](https://elementaryos.stackexchange.com/questions/15763/gala-and-xorg-high-cpu-usage-on-lenovo-x220/15773).

**Comment by Astro-City** [comment] 2018-06-24 23:56
Thanks for the pictures.  

How weird is to find such bug? haha

**Comment by lenemter** [comment] 2023-12-13 10:46
Closing because I cannot reproduce the issue in OS 7.1

**Closed by lenemter** 2023-12-13 10:46 UTC
Labels: Status: Incomplete
