### ISSUE TITLE
Mouse Quarter Tiling / Ctrl-Drag-Tile

### ISSUE THREAD

**Issue by andreasfelix** [elementary/gala#591] opened 2019-08-06 13:19 UTC
I think it would be a useful addition if **Ctrl-Drag** could be used to tile windows. I did a [first implementation](https://github.com/andreasfelix/gala/commit/16be4b9673a9db784c59a7a7f4600696fce42600) which is based on https://github.com/elementary/gala/pull/579.

The ctrl-tile-left/right action is especially useful for multi-monitor setups where the edge-tiling can get a bit inconvenient.

A problem is that [Mutter does not expose an API for tiling](https://gitlab.gnome.org/GNOME/mutter/issues/657), so the windows are not "really" tiled (compared to the edge tiling).

If the idea gets accepted, I could do a PR.  

![mouse_quarter_tiling](https://user-images.githubusercontent.com/24651767/62541776-bf720980-b85a-11e9-830c-430c12cec990.gif)
*Ctrl is pressed while dragging the window*

![tile_sketch](https://user-images.githubusercontent.com/24651767/62542523-36f46880-b85c-11e9-9de0-a91db6876e17.png)

**Comment by donadigo** [comment] 2019-08-06 17:57
I personally think that tile top shouldn't be the default action for dragging to the top as this action is much less desirable than actually maximzing the window.
From the above GIF I conclude that your tiling works based on the window position. I suggest that it should work on mouse position and also make the margin for triggering the tile much lower, it should not cause accidental tiles.

Anyway, I think we would definitely merge it if it worked well.

**Comment by andreasfelix** [comment] 2019-08-06 18:18
@donadigo The tiling is based on the mouse position. Maybe I should be more specific, but this does not aim to improve/replace the edge tiling. Instead when pressing down **Ctrl** while dragging a window, it gets resized to the area where the cursor is currently in. (see second picture).

**Comment by cassidyjames** [comment] 2021-01-27 18:57
Duplicate of #105; let's try to keep discussions on original issues/discussions instead of opening new ones. ;)

**Closed by cassidyjames** 2021-01-27 18:57 UTC

**Comment by andreasfelix** [comment] 2021-01-27 20:51
I opened a new issue, because I proposed a different tiling mechanism than in the mentioned issue: Instead of moving the window to an edge of the screen, the window is tiled corresponding to the area which the mouse pointer is currently in.

Anyway for the current implementation see #963  :)

**Comment by cassidyjames** [comment] 2021-01-27 22:09
@andreasfelix I understand, but the underlying "want" is the same: for quarter tiling. It's easier to track if the discussion is in one place instead of spread across several different issues.
