### ISSUE TITLE
Fast moving of the mouse while dragging the PiP view breaks moving the view

### ISSUE THREAD

**Issue by eppixx** [elementary/gala#1490] opened 2022-10-25 21:33 UTC
### What Happened?

While using the PiP and moving the window by dragging fast, the mouse detaches from the view and stops moving the view around.

### Steps to Reproduce

1. use the PiP by pressing super+f
2. make selection (it's easier to break when using a small selection)
3. hover the mouse over the view
4. press and hold the left mouse button
5. move the mouse fast
6. the mouse detaches from the view and becomes attached when moving back to the view

### Expected Behavior

The view should follow the mouse around even if the mouse updates to a pixel other than the view.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-02-11 12:26
Closing as duplicate of #1361.

**Closed by lenemter** 2023-02-11 12:26 UTC
