### ISSUE TITLE
 All screenshots should go in the 'Pictures > Screenshots' folder

### ISSUE THREAD

**Issue by uncertainquark** [elementary/gala#216] opened 2018-03-25 09:43 UTC
Currently
1. Screenshots taken through the "PrtScr" button go in the 'Pictures' folder:
![screenshot from 2018-03-24 15-50-57](https://user-images.githubusercontent.com/22585732/37862948-a272df8a-2f7b-11e8-9e60-5f167841c076.png)

2. While the ones taken through the "Screenshot app" go in the 'Pictures > Screenshots' folder:
![screenshot from 2018-03-24 15-51-01](https://user-images.githubusercontent.com/22585732/37862951-b1db2766-2f7b-11e8-908b-029335386d21.png)

The user is left confused with inconsistency in screenshot behavior. If the issue can't be fixed in Gala, the screenshot tool can be made to save screenshots in the Pictures folder for consistency as suggested in https://github.com/elementary/screenshot-tool/issues/71

**Comment by peteruithoven** [comment] 2018-09-28 19:00
Also, isn't this a duplicate of https://github.com/elementary/gala/issues/210 ?

**Comment by peteruithoven** [comment] 2019-02-06 01:05
This has finally been fixed with: https://github.com/elementary/gala/pull/459

**Closed by peteruithoven** 2019-02-06 01:05 UTC
