### ISSUE TITLE
Wrong virtual desktop switching with dual monitor setup.

### ISSUE THREAD

**Issue by xXNurioXx** [elementary/gala#919] opened 2020-09-16 01:40 UTC
Desktop switching is not working properly with a dual monitor setup.

Cause I have a dual monitor, when I press the ` Win + Right arrow` shortcut to move to the next desktop, I expect to move it on the active monitor. But it's working only on the primary monitor.

**Comment by ryanfelder** [comment] 2020-09-16 14:26
This was a design decision (compromise) made a number of years back. Virtual desktops only affect the primary monitor.

"The panel, dock, and workspaces appear only on the primary display. Any other attached displays act as standalone workspaces."

Source : https://elementary.io/docs/learning-the-basics#multitasking

"This is intentional for the reasons you pointed out. At the moment we can't have independent workspace switching. The window manager sees multiple displays as one big workspace in Luna. This can be frustrating because one of the big benefits of having another display is to have a place for things you always want to see like documentation or chat or your email. So in Freya, we made the compromise of making the primary monitor the only one with workspaces."

Source : Daniel Foré - https://elementaryos.stackexchange.com/questions/2732/workspaces-seem-to-only-apply-to-the-primary-display-is-this-a-feature-or-a-bug

**Comment by xXNurioXx** [comment] 2020-09-16 15:12
> This was a design decision (compromise) made a number of years back. Virtual desktops only affect the primary monitor.
> 
> "The panel, dock, and workspaces appear only on the primary display. Any other attached displays act as standalone workspaces."
> 
> Source : https://elementary.io/docs/learning-the-basics#multitasking
> 
> "This is intentional for the reasons you pointed out. At the moment we can't have independent workspace switching. The window manager sees multiple displays as one big workspace in Luna. This can be frustrating because one of the big benefits of having another display is to have a place for things you always want to see like documentation or chat or your email. So in Freya, we made the compromise of making the primary monitor the only one with workspaces."
> 
> Source : Daniel Foré - https://elementaryos.stackexchange.com/questions/2732/workspaces-seem-to-only-apply-to-the-primary-display-is-this-a-feature-or-a-bug

I see... I would like to have every monitor independently like MacOs. As long I understand that's a GNOME functionality, not ElementaryOS. :disappointed:

**Comment by janxkoci** [comment] 2020-09-17 15:18
> As far as I understand that's a GNOME functionality

Yes, afaik GNOME does the same thing.

**Comment by cassidyjames** [comment] 2020-09-18 18:22
Duplicate of #26. Please ensure you're searching a bit for existing issues before opening new ones.

**Closed by cassidyjames** 2020-09-18 18:22 UTC
