### ISSUE TITLE
Date format (24 hours) not honored on the lockscreen.

### ISSUE THREAD

**Issue by tyrefors** [elementary/gala#296] opened 2018-07-12 15:01 UTC
When locking the screen, with 24 hour clock set in preferences, the clock show is in the 12 hour format.
[Image of it in action](https://imgur.com/a/QwK4N93)

**Comment by danrabbit** [comment] 2018-07-12 17:02
This is a duplicate of https://github.com/elementary/greeter/issues/52

Closing as "Out of scope" because Gala does not control the clock on the greeter.

**Closed by danrabbit** 2018-07-12 17:02 UTC
