### ISSUE TITLE
Onboard goes crazy when it's resized over wingpanel

### ISSUE THREAD

**Issue by yellowgh0st** [elementary/gala#222] opened 2018-04-10 08:51 UTC
Onboar window goes completely crazy if you resize it over WingPanel.
It continuously changes its position from left to right and it never stops.

See WebM video:
https://my.mixtape.moe/gsbsbx.webm

**Fix**
1. Change Onboard window height to only 300px

`gsettings set org.onboard.window.landscape dock-height 300`

**Comment by 4ugustin** [comment] 2018-10-30 13:59
This is still present in Juno.

**Comment by lenemter** [comment] 2023-12-13 10:48
Closing because I cannot reproduce the issue in OS 7.1

**Closed by lenemter** 2023-12-13 10:48 UTC
