### ISSUE TITLE
Task switcher rounded corners are glitchy in dark mode

### ISSUE THREAD

**Issue by floi** [elementary/gala#1324] opened 2021-11-30 13:51 UTC
### What Happened?

The task switcher's rounded corners don't render properly. Sometimes it gets the top corners mostly right, but never all four:

![image](https://user-images.githubusercontent.com/33099408/144058522-ff460861-1397-4db8-bdb6-5c2ce5781cbd.png)
![image](https://user-images.githubusercontent.com/33099408/144058844-0a3c4b5c-0cb5-4d73-b943-58d1c1b788df.png)
![image](https://user-images.githubusercontent.com/33099408/144058903-7b75a468-185e-4680-9f41-05716298a918.png)

### Steps to Reproduce

1. Have a couple of windows open
2. Press Alt+Tab to open task switcher

### Expected Behavior

Properly rounded corners like other windows.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

GPU: NVIDIA Quadro P1000 Mobile running the proprietary 470.82.00 / 470.86 drivers

**Comment by JonathanOldenburg** [comment] 2022-01-04 20:13
i have the same issue on my dell with an NVIDIA 920M card. Didn't test in intel graphics yet.

**Comment by TomiOhl** [comment] 2022-05-05 00:15
I have the same issue on the latest 6.1 build with i5-8250U's integrated GPU, too. Seems like it's not (just) an nvidia iisue.

**Comment by danirabbit** [comment] 2023-04-11 15:09
Duplicate of #1355

**Closed by danirabbit** 2023-04-11 15:09 UTC
Labels: Status: Confirmed
