### ISSUE TITLE
Settings Schema is not installed

### ISSUE THREAD

**Issue by Gusaroo** [elementary/gala#1198] opened 2021-08-10 21:55 UTC
So after installing every dependency and building gala, I did the final step of “gala —replace” but it failed in an error stating “Settings schema ’org.gnome.settings-daemon.peripherals.touchscreen’ is not installed. Is there anyway to fix this error?

**Comment by davidmhewitt** [comment] 2021-08-10 22:12
Please include details of what OS you are building gala on and what library versions it has.

**Comment by Gusaroo** [comment] 2021-08-10 22:16
Well I’m building it on Xubuntu 21.04

**Comment by pimvullers** [comment] 2021-09-24 10:20
SImilar issue on Gentoo.

It is my suspicion that this is related to Gnome40 changes to gesttings schemas.

**Comment by tintou** [comment] 2021-09-24 10:22
Duplicate of https://github.com/elementary/gala/issues/1187

**Closed by tintou** 2021-09-24 10:22 UTC

**Comment by pimvullers** [comment] 2021-09-24 17:19
This is not a direct duplicate. The mouse schema has been moved/renamed to deprecated. For touchscreen it seems still to be present somehow (i.e. it is not marked as deprecated), but cannot be found for some reason.

**Comment by pimvullers** [comment] 2021-09-24 17:36
My environment:
 - gala-6.2.0
 - mutter-40.3
 - gsettings-desktop-schemas-40.0
 - gnome-settings-daemon-40.0.1

Touchscreen schema seems to be in place:
```
# grep -n4 touchscreen /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.peripherals.gschema.xml 
2-<schemalist>
3-  <schema gettext-domain="gnome-settings-daemon" id="org.gnome.settings-daemon.peripherals" path="/org/gnome/settings-daemon/peripherals/">
4-    <child name="smartcard" schema="org.gnome.settings-daemon.peripherals.smartcard"/>
5-    <child name="keyboard" schema="org.gnome.settings-daemon.peripherals.keyboard"/>
6:    <child name="touchscreen" schema="org.gnome.settings-daemon.peripherals.touchscreen"/>
7-  </schema>
8-  <schema gettext-domain="gnome-settings-daemon" id="org.gnome.settings-daemon.peripherals.smartcard" path="/org/gnome/settings-daemon/peripherals/smartcard/">
9-    <key name="removal-action" enum="org.gnome.settings-daemon.GsdSmartcardRemovalAction">
10-      <default>'none'</default>
--
34-      <summary>Keyboard Bell Custom Filename</summary>
35-      <description>File name of the bell sound to be played.</description>
36-    </key>
37-  </schema>
38:  <schema gettext-domain="gnome-settings-daemon" id="org.gnome.settings-daemon.peripherals.touchscreen" path="/org/gnome/settings-daemon/peripherals/touchscreen/">
39-    <key name="orientation-lock" type="b">
40-      <default>false</default>
41-      <summary>Whether the tablet’s orientation is locked, or rotated automatically.</summary>
42-    </key>
```

In contrast to:
```
# grep -n4 mouse /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.peripherals.gschema.xml 
42-    </key>
43-  </schema>
44-
45-  <!-- Deprecated schemas/keys -->
46:  <schema id="org.gnome.settings-daemon.peripherals.mouse.deprecated">
47-    <key name="left-handed" type="b">
48-      <default>false</default>
49-      <summary>Mouse button orientation</summary>
50:      <description>Swap left and right mouse buttons for left-handed mice.</description>
51-    </key>
...
```

**Comment by pimvullers** [comment] 2021-09-24 17:39
@Gusaroo can you check mutter in your environment?
Since for me this gives similar error to gala, so the issue might not be in gala, but in some mutter functionality it uses.
```
$ mutter --replace

(mutter:9820): GLib-GIO-ERROR **: 19:37:30.060: Settings schema 'org.gnome.settings-daemon.peripherals.touchscreen' is not installed
Trace/breakpoint trap
```
