### ISSUE TITLE
System going to Suspend even when audio or video is playing

### ISSUE THREAD

**Issue by tmak99** [elementary/gala#838] opened 2020-06-04 14:36 UTC
## Describe the bug
System going to Suspend even when audio or video is playing

### Expected behavior
The System should not go to suspend state when a music or video is playing

## Platform Information
![image](https://user-images.githubusercontent.com/66071754/83770524-b0253d80-a670-11ea-80dc-c4fe9dd86e65.png)

**Comment by cassidyjames** [comment] 2020-08-25 03:00
@tmak99 what app is paying the music or video?

**Comment by tmak99** [comment] 2020-08-27 14:25
@cassidyjames  - I am using elementary music for playing audio and VLC for watching videos
@weatheralex1  - For now i have set the setting to never suspend, but i think it should not be the case as the system is running even if am not using it. So i think the system should know whether any it is used or not and go to suspend state on its own.

Thanks

**Comment by stsdc** [comment] 2020-09-05 09:41
Can confirm this with stock Video app.

This is inconvenient when laptop is connected to e.g. TV and you have to rush to it when suspend notification pops up.

**Comment by ralxxx** [comment] 2020-09-27 14:14
I can confirm this as well for stock applications ('Video") as well as non-stock such as Zoom, Skype, Tuner and others.

**Comment by jeremypw** [comment] 2020-09-27 14:30
Hopefully this is now fixed for native Video app by https://github.com/elementary/videos/pull/214 (not yet released)

**Comment by danrabbit** [comment] 2020-09-27 15:30
As far as Gala's responsibility is, this is now fixed in elementary OS 6

Closing this issue report since if someone app is still not working it needs a fix in that app

**Closed by danrabbit** 2020-09-27 15:30 UTC
Labels: Status: Incomplete
