### ISSUE TITLE
The app started in maximized state will not be moved to new workspace

### ISSUE THREAD

**Issue by sauntor** [elementary/gala#1720] opened 2023-07-09 13:44 UTC
### What Happened?

In `Settings`,  `Multitask`,  turn `Maximized` on,  if you maximize an app and close it, then reopen it again, the app would not be moved to new workspace

### Steps to Reproduce

As `What happened` says

### Expected Behavior

The app should be moved to workspace

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-07-11 11:55
Duplicate of https://github.com/elementary/gala/issues/573.

**Closed by lenemter** 2023-07-11 11:55 UTC
Labels: Status: Duplicate
