### ISSUE TITLE
Multitasking view breaks when switching displays & strange Wingpanel position

### ISSUE THREAD

**Issue by TomiOhl** [elementary/gala#1518] opened 2023-02-02 19:04 UTC
### What Happened?

The multitasking view breaks when an external monitor is connected and I attempt to switch to the external monitor only. On the multitasking view, the wallpaper is not shown anymore.  ~~Also, the opened app cards aren't clickable on the external monitor. - reported in #1519~~

### Steps to Reproduce

1. Be on the desktop, optionally open some apps
2. Toggle the switch displays button (laptops typically have this, it's fn + f5 on my Acer, but it's possible to set a shortcut in System settings, too). First it will switch to a view where the dock is on the laptop display and the wingpanel is on the external monitor. This also definitely shouldn't happen.
3. Toggle the switch displays button again. It will switch to external monitor only.
4. Enter multitasking view and see

Note: if I click on the wingpanel in the second step, it will crash and reappear on the laptop display. After that, switching to external monitor only will work as expected and the described symptoms won't be shown.
Note2: the Wingpanel is on the bottom of the screen sometimes in multitasking view. I'm not sure how to reproduce it but I feel like it's relevant here
Note3: moving all the windows to a new workspace also "fixes" the issue in a sense that the new workspace will have a wallpaper

### Expected Behavior

Wingpanel always at the top of the screen and working multitasking view with wallpaper

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Laptop + external monitor

**Comment by diogopessoa** [comment] 2023-02-04 11:46
Please, could you make a short video to demonstrate the error?

**Comment by TomiOhl** [comment] 2023-02-05 23:05
Sure! This is how it looks like after switching to the external monitor:

https://user-images.githubusercontent.com/6696659/216850986-6ce81262-1757-4b63-844b-fcdfeb3d0f94.mp4

**Comment by fayjie92** [comment] 2023-02-09 11:41
Any update on this? It's really a great issue at this moment for now.

**Comment by colinkiama** [comment] 2023-03-13 23:26
I can also confirm the wingpanel position bug too. Displays at the bottom of the screen for me when I have an external monitor connected and I open the multitasking view. 

In my case the external monitor is extending the internal display.

Maybe this issue should be split into two?

**Comment by anhel-strauke** [comment] 2023-05-02 04:16
I have a similar issue. I'm using an external monitor as a main display. External screen is 4K, built-in panel is 1920×1200. When I activate Multitasking View, no windows are shown on the secondary (in my case built-in) monitor, just a gray background. "Show all windows" works fine. Not sure if the issue is _exactly_ the same though.

_Sorry for the video quality, shot by a phone, weirdly the OBS Studio does not capture the Multitasking View at all._

https://user-images.githubusercontent.com/469912/235578015-d3b7677b-f713-4bf4-89d5-59ac4b6098ba.mp4

**Comment by lenemter** [comment] 2023-05-02 11:54
@anhel-strauke This issue was fixed in #1640. I hope the new release will be released tomorrow. Thanks for reporting it though.

**Comment by fayjie92** [comment] 2023-08-13 20:28
The issue of TomiOhl (first commented user) is still there in my case. If I disconnect my external display with workspaces on my primary monitor (suppose a laptop), I get the issue in my primary monitor when I open multi-tasking view.

**Closed** 2023-11-07 19:46 UTC
Labels: Status: Confirmed
