### ISSUE TITLE
Computer suspends despite disabling suspend in Gala settings

### ISSUE THREAD

**Issue by jhmenke** [elementary/gala#475] opened 2019-02-28 07:00 UTC
edit: This is a duplicate of https://github.com/elementary/switchboard-plug-power/issues/89
Sorry i did not look in that repository. Please close this.

I was trying to run a simulation overnight and had the power setting "Suspend when inactive for:" set to *Never*.
This morning i came back to the laptop and had to log back in (that's okay because i locked the screen). But my simulation has not continued, it seems it has suspended the activities for the time i was away

`79%|███████▉  | 197/250 [20:31:02<239:32:24, 16270.66s/it]`

I have a suspicion another computer with elementary running also suspends when inactive for a time, despite disabling the relevant setting. 

I am running the newest elementary os with all updates on a Huawei Matebook X Pro

**Comment by peteruithoven** [comment] 2019-02-28 09:26
Like author requested, closed as duplicate of 
[elementary/switchboard-plug-power#89](https://github.com/elementary/switchboard-plug-power/issues/89)

**Closed by peteruithoven** 2019-02-28 09:26 UTC
