### ISSUE TITLE
Switch between windows of the same app

### ISSUE THREAD

**Issue by agrawalsourav98** [elementary/gala#786] opened 2020-04-29 18:26 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

Currently there is no shortcut to switch between windows of the same app. To switch it i have to go the dock,left click and select the window or cycle through all the open apps to reach the window.

**Describe the solution you'd like**

A shortcut key which enables this feature would be awesome.
**Existing work**

I used to use this a lot on ubuntu. The shortcut was "alt + `"
**Describe alternatives you've considered**

The current alternative is to cycle to all the open applications until i reach the window.
**Additional context**

**Comment by Blast-City** [comment] 2020-04-30 01:42
Hi.

Could you close this issue since it is a duplicate of #536. Sorry.

Thanks.

**Closed** 2020-04-30 03:09 UTC
