### ISSUE TITLE
Split screen into 4 

### ISSUE THREAD

**Issue by murbanowicz** [elementary/gala#624] opened 2019-10-31 18:31 UTC
this is the feature which is really missing. 
Easily done with KDE with simple shortcuts when you're able to put window into one of four corners. Totally impossible with ElementaryOS... 

To be clear, I think about being able to achieve this:
![DellP4317Q-2-768x540](https://user-images.githubusercontent.com/9385106/67975773-06cb2480-fc15-11e9-9d1e-09e65d6563bd.jpg)

**Comment by danrabbit** [comment] 2019-10-31 19:16
Closing as a Duplicate of #105

**Closed by danrabbit** 2019-10-31 19:16 UTC
