### ISSUE TITLE
Short-time freezes of the screen

### ISSUE THREAD

**Issue by deniskoronets** [elementary/gala#454] opened 2019-01-29 12:43 UTC
I'm getting some issues with the screen while running on Juno x64:
Time to time, screen freezes for few seconds. This happens often and somehow correlates with mouse/keyboard input. When I watch videos, audio doesn't stop, but screen could freeze for just few seconds, then resume. If you make some input (move mouse or press ctrl), video doesnt freeze. 

My configuration is:
Gala 0.3.1
Quad-Core Intel® Core™ i5-7600 CPU @ 3.50GHz
Intel Corporation HD Graphics 630 (rev 04)
I use VGA cable for connecting with monitor.

**Comment by peteruithoven** [comment] 2019-01-29 12:49
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/os/issues/121

**Closed by peteruithoven** 2019-01-29 12:49 UTC

**Comment by deniskoronets** [comment] 2019-01-29 12:51
sorry, didn't find duplicates by searching in issues by keyword "freeze"
